### ISSUE TITLE
Localization issue on Mac OS X

### ISSUE THREAD

**Issue by Skrypt** [mono/mono#10200]
## Steps to Reproduce

1. Simply run Environment.GetEnvironmentVariables() from the VS debugger
2. Compare with `printenv` environment variables values through Mac Terminal

<img width="1452" alt="capture-d_ecran-2018-08-20-a-09 16 54" src="https://user-images.githubusercontent.com/3228637/44361555-3f596500-a48c-11e8-94b0-e46c7ed45c1f.png">

### Current Behavior

When debugging with Visual Studio for Mac an app made with ASP.NET Core I get the wrong current system culture. Instead of "fr-CA" it returns only "fr".

### Expected Behavior

Should return fr-CA

## On which platforms did you notice this

[x ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

5.12.0.298

**Comment by Therzok** [comment]
I think this is a side effect of child processes inheriting env vars of VSMac. cc @slluis

**Comment by Therzok** [comment]
[MonoTargetRuntime.GetEnvironmentVariables](http://source.monodevelop.com/#MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntime.cs,2e62ea759f16e525) propagates to the [execution environment](http://source.monodevelop.com/#MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntime.cs,de6a252605d621e6,references) so they end up being used [here](http://source.monodevelop.com/#MonoDevelop.Core/MonoDevelop.Core.Execution/MonoPlatformExecutionHandler.cs,41), [here](http://source.monodevelop.com/#MonoDevelop.Debugger.Soft/SoftDebuggerEngine.cs,76)

So that's a VSMac bug, I think. Didn't trace yet where it leaks to dotnet commands

**Comment by akoeplinger** [comment]
This issue was moved to mono/monodevelop#5725
