### ISSUE TITLE
Make managed stack walking machinery use MonoError 

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#10220]
The crash reporter would love to be able to only upload an unmanaged stack trace if the managed stack is totally trashed. Our use of g_assert, particularly around domains, does not admit an easy "try-and-see-if-it-worked" approach.  

Making these use MonoError would be the most reliable way to support fallbacks to attempts to walk a stack.

**Comment by lambdageek** [comment]
This issue is very open-ended right now, so it's difficult to say anything definitive, but: it could be that the needs of the crash reporter (survivability in unfriendly terrain) is distinct from the needs of more pedestrian runtime code (maintenance of invariants).

For much of the runtime, running without a domain is really unusual.

On the other hand, we have a lot of situations (before Mono finishes initializing; on some utility threads (like the profiler); during AOT) when "the runtime" is really operating without a managed execution engine around (so domains, managed allocation, etc don't necessarily apply).  So if those things go wrong, we should be able to collect crashes.

**Comment by alexanderkyte** [comment]
I think that a lack of an ability to recover from errors in stack walking makes us more brittle overall. The crash reporter isn't the only place where we have doubts about stack integrity and need to be able to create a stack trace. Any time we're handling exceptions that are propagated to managed, there's a chance that some pinvoked code was related to it somehow. Making correctness all or nothing is disadvantageous compared to using MonoError.

**Comment by alexanderkyte** [comment]
This has been fixed and merged
