### ISSUE TITLE
Custom MSBuild task built with netstandard 1.3 dependencies fails on latest preview with missing method exception

### ISSUE THREAD

**Issue by Therzok** [mono/mono#10352]
@PureWeen commented on [Sat Aug 25 2018](https://github.com/mono/monodevelop/issues/5773)

```
System.MissingMethodException: Method not found: void System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
```

### Reproduction Steps

1) Compile SomeBuildTask
2) Compile MSbuildError

Works fine on: Version 7.6.1 (build 9)
Fails on: 7.8 Preview (7.8 build 129)

### Notes
- If I copy  *System.IO.FileSystem.Primitives.dll* from nuget 2.0.3 netstandard into the bin directory where *CopyLocalLockFileAssemblies* copies everything then everything works fine and msbuild is able to use the custom task
- In our case we are using Mono.Cecil ( which is netstandard 1.3) and we have CopyLocalLockFileAssemblies set to true on our project, but our project is netstandard 2.0 so it seems like it should be copying the netstandard 2.0 version of this library not the 1.3 version.
```
Copying file from "/Users/shane/.nuget/packages/system.io.filesystem.primitives/4.3.0/lib/netstandard1.3/System.IO.FileSystem.Primitives.dll" to "bin/Debug/netstandard2.0/System.IO.FileSystem.Primitives.dll".
```

- this compiles fine on stable but doesn't compile on alpha

Our Xamarin Forms project having issues
[MsbuildError.zip](https://github.com/mono/monodevelop/files/2320276/MsbuildError.zip)

It's using https://github.com/jbevain/cecil/

> VS bug [#672062](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/672062)

---

@mrward commented on [Tue Aug 28 2018](https://github.com/mono/monodevelop/issues/5773#issuecomment-416667134)

Unable to repro the build error with VS Mac 7.8.0.249 and Mono 5.12.0.301.

Will try alpha channel versions of VS Mac 7.8 and Mono 5.16.

---

@PureWeen commented on [Tue Aug 28 2018](https://github.com/mono/monodevelop/issues/5773#issuecomment-416672839)

@mrward   ugh sorry I uploaded the wrong zip for the simpler one :-/ let me fix that

In the mean time
https://github.com/mono/monodevelop/files/2320276/MsbuildError.zip

should still cause the error  but not sure if you already tested that one

---

@mrward commented on [Tue Aug 28 2018](https://github.com/mono/monodevelop/issues/5773#issuecomment-416676936)

I tested both projects from the two zip files. They both build OK with Mono 5.12.0.301.

Installing Mono 5.16.0.113 and the project fails to build with VS Mac 7.8.0.249 and VS Mac 7.6.1.

This problem can be reproduced from the command line just using msbuild so it looks like something has changed in Mono 5.16.

**Comment by marek-safar** [comment]
@radical is that due to 4.7.x bump ?

**Comment by radical** [comment]
@marek-safar nope.

**Comment by Therzok** [comment]
Needs to be fixed in 2018-06. Xamarin.Forms cannot be built if this isn't fixed.

**Comment by radical** [comment]
The difference between the 5.12 and 5.16 build is that for the task assembly (loaded from `MsbuildError/MsbuildError/../SomeBuildTask/bin/Debug/netstandard2.0/SomeBuildTask.dll`):

5.12: mono loads the dependency (of `Mono.Cecil.dll`) `System.IO.FileSystem.Primitives`(`Version 4.0.1.0`) from mono's own facades: `/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/4.5/Facades/System.IO.FileSystem.Primitives.dll`. This typefowards to `corlib`. (Version: 4.0.1.0)

5.16: Due to the new loader changes(IIUC), mono first looks in the directory containing that task assembly and loads the dependency from there. (Version: 4.0.2.0)

**Comment by marek-safar** [comment]
Yeah, this looks like the fix just exposed an issue we had for some time. I am not sure why there is no System.IO.FileSystem\lib\netstandard1.3 while there is one for System.IO.FileSystem.Primitives though.

**Comment by marek-safar** [comment]
This is according to msbuild team by design. Creating MSBuild tasks which target .NET Standard is not supported.
 
Consider what happens if you depend on a bait-and-switch NuGet package.  The .NET Standard build task wouldn’t have the implementation for that package on any platform.  I think the failures you’re seeing with .NET Standard are probably a similar issue even if you may be able to hack around these specific issues.
 
What I recommend, and what we do for the .NET SDK build tasks, is to multitarget the task to .NET Framework and .NET Core, publish it to different folders, and then use the MSBuildRuntimeType property to figure out which one to load:
 
```
    <MicrosoftNETBuildExtensionsTasksAssembly Condition="'$(MicrosoftNETBuildExtensionsTasksAssembly)' == '' AND '$(MSBuildRuntimeType)' == 'Core'">$(MSBuildThisFileDirectory)\tools\netcoreapp2.0\Microsoft.NET.Build.Extensions.Tasks.dll</MicrosoftNETBuildExtensionsTasksAssembly>
    <MicrosoftNETBuildExtensionsTasksAssembly Condition="'$(MicrosoftNETBuildExtensionsTasksAssembly)' == ''">$(MSBuildThisFileDirectory)\tools\net46\Microsoft.NET.Build.Extensions.Tasks.dll</MicrosoftNETBuildExtensionsTasksAssembly>
```
