### ISSUE TITLE
[iOS] CalendarTest.Hijri and CalendarTest.UmAlQura fail

### ISSUE THREAD

**Issue by BrzVlad** [mono/mono#10448]
## Steps to Reproduce

1. build mono-2018-08 branch from xamarin/xamarin-macios
2. make -C tests/ runner
3. Run **link sdk** tests

**Comment by lambdageek** [comment]
This is likely due to 
https://github.com/mono/mono/blob/1d7145413201516976e7d07408cd448beeee96dc/mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate.cs#L611-L616
the X509Certificate code links strongly to `HijriCalendar` and `UmAlQuraCalendar`.
I've a WIP patch to use strings and `Activator.CreateInstance` instead.
