### ISSUE TITLE
Recent regression: ```ProvidedField has invalid vtable method slot 20 with method none``` 

### ISSUE THREAD

**Issue by dsyme** [mono/mono#10495]
We're seeing a failure in Mono 5.19.0.290 (mono-weekly tag on travis) that was passing in all previous Mono. It looks like a regression has slipped in 

I'm seeing this in CI for project https://github.com/fsprojects/FSharp.TypeProviders.SDK/ 

![image](https://user-images.githubusercontent.com/7204669/45174585-2b8b5e00-b203-11e8-95ce-1325588b5584.png)

We CI that repo using mono-weekly to make sure we see mono regressions before they are too late.

```ProvidedField has invalid vtable method slot 20 with method none``` 

## Steps to Reproduce

1. Clone https://github.com/fsprojects/FSharp.TypeProviders.SDK/
2. set USE_MSBUILD=1  (not sure if it's relevant)
3.  `./build.sh Pack`

### Current Behavior

```

/home/travis/build/fsprojects/FSharp.TypeProviders.SDK/examples/BasicProvider.Tests/BasicProvider.Tests.fs(12,39): error FS3033: The type provider 'ProviderImplementation.BasicErasingProvider' reported an error: Type ProviderImplementation.ProvidedTypes.ProvidedField has invalid vtable method slot 20 with method none [/home/travis/build/fsprojects/FSharp.TypeProviders.SDK/examples/BasicProvider.Tests/BasicProvider.Tests.fsproj]
```

### Expected Behavior

Tests pass

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

See above  - 5.19.0.290

**Comment by lambdageek** [comment]
@MaximLipnin `ProvidedField` in the error message here is a custom `FieldInfo` subclass.  Could this be related to your recent CoreFX System.Reflection work?

**Comment by lambdageek** [comment]
So my guess is that this is a regression since #10370 related to https://github.com/mono/mono/pull/10370/files#diff-d734a56e2e46fe93fa6696019ba1a9b0R62
That line adds a new abstract `GetFieldOffset` method to `FieldInfo` which is not present in .NET Standard.

@MaximLipnin that makes it impossible for custom FieldInfo subclasses to be created by downstream projects.

In this case it's a runtime error, rather than compile time error because this project builds against .NET Standard (which doesn't have the `GetFieldOffset` internal method), but then runs against Mono.

**Comment by MaximLipnin** [comment]
It's existing method that was made abstract in this [commit](https://github.com/mono/mono/pull/10370/commits/928a72670bf9ec497920317c3a0263065d01b834) during review comment addressing. It's strange that I didn't catch that issue by any of unit tests.

**Comment by lambdageek** [comment]
We don't have any tests that make custom subclasses of System.Reflection types.

**Comment by dsyme** [comment]
@MaximLipnin I tried 5.19.0.290 and still see a failure - should that version have had the fix?  Thanks!
