### ISSUE TITLE
thread-suspend-suspended.exe and thread-suspend-selfsuspended.exe fail a lot on Windows i386

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#10508]
## Steps to Reproduce

1. Run thread-suspend-suspended.exe and thread-suspend-selfsuspended.exe tests on 32bit Windows (it doesn't happen on 64bit!)
2. The tests time out very often.

Might be related to the recent switch to hybrid suspend.

### Current Behavior

The tests time out after 5 minutes. Examples:

- https://jenkins.mono-project.com/job/z/label=w32/7844/testReport/
- https://jenkins.mono-project.com/job/z/label=w32/7843/testReport
- https://jenkins.mono-project.com/job/z/label=w32/7841/testReport
- https://jenkins.mono-project.com/job/z/label=w32/7838/testReport/
- https://jenkins.mono-project.com/job/z/label=w32/7837/testReport

### Expected Behavior

No failure.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ X ] Windows i386 (not x64!)

**Version Used**: master

/cc @lateralusX

**Comment by lateralusX** [comment]
Looks like first failure of one of these tests occured here (might not be directly related though):

https://jenkins.mono-project.com/job/z/label=w32/7657/

Will try to reproduce this in the debugger during the week.

**Comment by lateralusX** [comment]
Still no local repro, but investigated the code heavily under debugger and could force a couple of scenarios that could (at least in theory) happen under wow64 related to thread suspend failing. This scenario is then not handled by sgen (and very uncommon and only observed under wow64) but could get us into either a deadlock or asserts when doing the GC in scenarios like the once's hit by the test. Will need to spend some more time investigate this a little deeper in the debugger, but looks like this boils down to a potential case when mono_threads_suspend_begin_async_suspend returns FALSE (could happen for various resons under wow64).

**Comment by lateralusX** [comment]
@lambdageek One things that I noticed when digging in this issue. On MSVC compiled mono runtime (the one that is actually run and tested on CI), hybrid suspend is NOT the default, so its still using premptive suspend on both 32 and 64 bit Windows MSVC build runtime. The reason for this is that winconfig.h doesn't have the flag ENABLE_HYBRID_SUSPEND set. Setting that flag in winconfig.h gives us another problem with an unimplemented feature on MSVC that will cause failures when trying to use hybrid suspend and coop suspend on Windows. Looks like SAVE_REGS_ON_STACK is not defined for MSVC, mono-threads-coop.c:39. I could (hopefully) implement something similar on MSVC. So __builtin_unwind_init dumps all registers on the stack so GC will find references in registers when scanning the stack instead of what it previously did when scanning the captured MonoContext object for a thread, correct?

**Comment by jaykrell** [comment]
RtlCaptureContext.

**Comment by lambdageek** [comment]
I debugged `thread-suspend-suspended` a little today.  Apparently, `mono/utils/mono-threads.c is_thread_in_critical_region` returns TRUE from the `mono_threads_platform_in_critical_region()` branch when `sgen-stw.c:321` is looking at thread `t1` (see the testcase source). 

Which means that we end up resuming `t1` back to BLOCKING and then I incorrectly only run the MOPUP phase of hybrid suspend which doesn't expect to see any blocking threads - it expected all of them to be preemptively suspended the first time through.

I think the correct plan is for me to do two-phase suspend after a restart.

It makes sense that we only saw this fail on windows i386 on CI because that's the only platform with `mono_threads_platform_in_critical_region` that ever returns TRUE.

**Comment by lateralusX** [comment]
On CI we run msvc build runtime for tests that currently only runs premptive suspend and recovers when mono_threads_platform_in_critical_region returns TRUE without errors. Regarding the assert seen in stw together with hybrid suspend, that will cause a resume thread logic that (as you say above) will trigger the assert in stw suspend logic. I easily hit that on msvc build runtime since the callback used in mono_thread_info_safe_suspend_and_run, async_suspend_critical never sees the thread as currently in managed code (probably something else that is missing on msvc hybrid suspend) so that will trigger an interrupt request and a return of MonoResumeThread that will restart thread and race with stw suspend loop as well, so same end result but two different ways hitting it. The problem I have seen could happen on both x64 and x86 builds.

**Comment by lateralusX** [comment]
As said, by default msvc build runtime is still using premtive suspend and that is whats running on CI, only mingw build runtime follows the new hybrid suspend, but that is not the runtime running the tests on CI. I have https://github.com/mono/mono/issues/10684 for fixing hybrid suspend on msvc so we could switch default for that version of the runtime as well.

**Comment by marek-safar** [comment]
@lateralusX could you disable the test for now on windows to reduce PR builds failures

**Comment by lateralusX** [comment]
https://github.com/mono/mono/pull/10716

**Comment by lambdageek** [comment]
Okay, so we need to fix two separate things:
1. with preemptive suspend, the test hangs sometimes - this issue.
2. with hybrid suspend, the test asserts (`Thread 00006484 in unexpected state RUNNING with PEEK_BLOCKING_SUSPEND_REQUESTED`) - new issue #10722

**Comment by lateralusX** [comment]
A couple of finings and observations around the preemptive suspend issue. When running the test on CI with some additional diagnostics it turns out that the tests doesn't deadlock but takes a long time to complete (tipping over the 300 s timeout) for x86 while the x64 always complete much quick on the same hardware. The Windows builders only have 2 virtual cpu's and I can emulate this problem by setting thread affinity on my local machine to 1 core and I also tried on a Windows 2016 azure server image with 2 virtual cores and get similar results, x86 test takes long time to complete while x64 completes much quicker.

The design of these tests includes one thread that will spinn in a very tight loop consuming 100% CPU time on one core while the other threads are doing a lot of context switching consistently yielding time to the spinning thread that could, on a machine with a low core count (that is virtualized), significantly increase the execution time of the test. The wow64 layer present on x86 version of the test also increase kernel mode transition times compared to the x64 version that in turn could increase the context switches. When I looked at the test running slow on a one core machine, the time spend on each thread seems correct and each thread (when debugged) still did what's expected and didn't end up doing extra work etc. I will debug this even more and also try to sort out how much the threads are just sitting in ready state waiting to be scheduled. This scenario with low core count and a thread hogging one cpu could still hit a bug related to wow64, but nothing I have identified so far. Reducing the process hooging in thread t1 makes the test complete much quicker on x86 as well as x64.

**Comment by jaykrell** [comment]
Why wow64 increase kernel time? That rarely, but sometimes, makes sense. It is usually an extremely thin layer and all usermode.

**Comment by lateralusX** [comment]
Correct, was refering to the additional user mode work needed to transition from 32 -> 64 and back (even if its still should be a thin wrapper), not direct increased kernel mode execution time.

**Comment by lateralusX** [comment]
Did some additional interesting investigation and observation around the tests. First, the same behavior could be reproduced using regular .NET Framework runtime, so this is indeed not a mono related problem but a behavior the test triggers on machines with low core count (or setting the affinity for the mono process to just schedule on one core).

I did a analysis of the scheduling of threads when hitting the repro of a slow executed test under wow64. Looking at thread execution times revealed some interesting information. First dump of user mode time looked like this (excluded unrelated threads):

  Thread       Time
    4:2354     0 days 0:00:19.234		(t1 hogging the core)
    0:a4e4     0 days 0:00:00.296		(main thread)
    5:9568     0 days 0:00:00.046		(t2 periodically running GC)

Then let the test run for some more time gives us the following result (excluded unrelated threads):

  Thread       Time
    4:2354     0 days 0:00:46.250		(t1 hogging the core)
    0:a4e4     0 days 0:00:00.296		(main thread)
    5:9568     0 days 0:00:00.109		(t2 periodically running GC)

This shows that the hogging thread gets plenty of scheduled CPU time while the other threads get very small amounts of CPU time. The main thread hasn’t got any measurable amount of time at all during this period and since it doesn’t run that frequently it won’t progress the test and won’t trigger any additional GC collections for t2 that will just spin and yield. Continuing to look at the thread schedule times for the test shows the same pattern, a lot of time given to t1 (that should be frequently suspended) while the other two threads get small amount of time causing very slow progression of the test under wow64.

Doing the same thread analysis under x64 shows a different behavior. Under x64 the time is much more evenly distributed between the threads and the hogging thread doesn’t get the same amount of “exclusivity”, meaning that the test will also progress much quicker since both GC as well as main thread will get more scheduled CPU time.

Starting to analyze where the additional time (mainly wait time in this case) shows that ResumeThread takes a long time to complete for the main thread when resuming t1, but since t1 still gets a lot of execution time, the wait within Win32 ResumeThread call seems to occurs after t1 has been resumed, but before returning back from ResumeThread call. Looking at the numbers shows that all additional time that the test takes under wow64 with 1 core ends up in ResumeThread (called from main thread). Doing a normal Resume Thread not hitting this issue takes normally < 10 micro seconds, but when hitting this issue, ResumeThread takes between 45 000 and 90 000 micro seconds and the total accumulation of that time ends up in the long test runs. NOTE, this behavior is not reproducible on a machine with an additional free cores.

A couple of things that mitigates the problem is to switch from Yield to Sleep (1) in main thread. Doing this instead of Yield will put the thread into a different state (not ready and not directly rescheduled if core is still free) that will make the scenario behave differently, not triggering the longer execution times of ResumeThread. Having that said I believe the best would be to rewrite the test into a more stable version consistently testing the suspend-suspended, suspend-selfsuspended scenario. That version of the test will behave more stable on systems having low to high core count. The current way of “synchronizing” between the thread using atomics and Yield will not cause deterministic execution behavior, especially on Windows in scenarios where threads gets different cores and since Yield will only give up the time slice on current core if there are threads available in the ready queues and rescheduled on the same core, there is a risk that the main thread will pass it’s Yield call without stopping moving directly into Thread.Resume before the GC thread had its chance to run, so then we will get into a scenario where we are not testing suspend-suspended since t1 might actually be running when GC runs.

A fix of the tests that appears more stable on all platforms is availalbe in https://github.com/mono/mono/pull/10646.

**Comment by lateralusX** [comment]
Mitigated by https://github.com/mono/mono/pull/10646.
