### ISSUE TITLE
How do I programmatically determine if and where Mono 64 bit is installed in Windows?

### ISSUE THREAD

**Issue by robbor78** [mono/mono#10535]
I found these registry settings

[HKEY_LOCAL_MACHINE\SOFTWARE\Mono]
"Installed"=dword:00000001
"Version"="5.10.1.47"
"SdkInstallRoot"="C:\\Program Files\\Mono\\"
"FrameworkAssemblyDirectory"="C:\\Program Files\\Mono\\lib\\"
"MonoConfigDir"="C:\\Program Files\\Mono\\etc\\"
"Architecture"="x64"

Assuming the user installed the Mono 64 bit MSI, can I in C# code read the registry and rely on that key and those values being present?

Are these settings stable?

## On which platforms did you notice this

[ X] Windows only

**Version Used**:
5.10.1.47

(Also asked on Stackoverflow https://stackoverflow.com/q/52254395/572332)

**Comment by akoeplinger** [comment]
Yes that key is stable. The only thing to be aware of is to read the correct parts of the registry since it'll differ depending on whether your C# app is 32bit or 64bit. E.g. in a 32bit C# app running on 64bit Windows the registry will be redirected automatically and you need something like https://stackoverflow.com/questions/11808462/avoid-registry-wow6432node-redirection to get the real registry key.

Hope that helps!
