### ISSUE TITLE
Can't install 5.16.0 to Raspbian9

### ISSUE THREAD

**Issue by hachikou** [mono/mono#11776]
## Steps to Reproduce

1. Download Raspbian9 and write the image to micro-SD, attach it to Raspberry Pi.
2. After finish initializing the Raspbian, add the Mono repository as you mentioned in https://www.mono-project.com/download/stable/#download-lin-raspbian
3. Do "sudo apt install mono-devel"

### Current Behavior

Build sequence runs too heavy - almost freeze - while "Mono precompiling /usr/lib/mono/4.5/Microsoft.CodeAnalysis.CSharp.dll".
On that situation, top command shows almost no-memories are available and kswapd0 process comes top cpu-eater.

I tried to disable swap with "sudo systemctl stop dphys-swapfile.service", but the result was equal.

I'm using 2018-06-27-raspbian-stretch.img for Raspberry Pi, and current stable mono (5.16.0.179).
My Raspberry Pi is Raspberry Pi 3 Model B 1GB RAM.

### Expected Behavior

Should be finish installing in several minutes as 5.14.0.
(Yes, it had no trouble till 5.14.0 with same Raspbian.)

## On which platforms did you notice this

[ ] macOS
[x] Linux - Raspbian 9
[ ] Windows

**Version Used**:

5.16.0.179

## Stacktrace

N/A

**Comment by lewurm** [comment]
Thanks for your report @hachikou. On 5.16 we started to use LLVM for the Ahead-of-Time-Compiler for pre-compiling the Base-Class-Library at installation time. While it should give you better performance, there is a much higher one-time cost at installation-time due to LLVM doing more optimizations and thus being slower. That is a problem on smaller devices such as Raspberry Pi unfortunately.

We've disabled LLVM as the default on 5.18. Could you try the Preview repository and see if it's still an issue for you?
https://www.mono-project.com/download/preview/#download-lin-debian

**Comment by equiclouds** [comment]
@hachikou I installed mono 5.16 to Raspbian9 by enable more virtual memory. 
Microsoft.CodeAnalysis.CSharp.dll and Microsoft.CodeAnalysis.VBasic.dll cost too much memory to build, so we should set bigger swapfile.

**Comment by hachikou** [comment]
Thank you for your useful informations.

@lewurm  I'll try 5.18 this night.
@equiclouds  That's what I planned to do next.  Disabling swap file, the situation went worse, so I thought the same idea as you mentioned. (but there were no time to try it last night...)

Anyway, I'll report soon.

**Comment by hachikou** [comment]
Mono 5.18(current preview) works fine. I installed it within 15 min.
Later I'll try install 5.16 with large swap.

**Comment by hachikou** [comment]
Finally I did install 5.16 with 2GB of swap file.
(I don't know how much time I spent on it because I was defeated at sleepiness...)

Thanks again for your apt answer.
