### ISSUE TITLE
Include the FileSize, Timestamp for each managed module in crash report

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11919]
Managed modules are PE images, and the standard symbol server indexing process uses the Optional Header “SizeOfImage” field and the IMAGE_FILE_HEADER “TimeDateStamp” field.  By having the filename, SizeOfImage, and TimeDateStamp we can pull archived binaries from the symbol server instead of having to download the entire mono or VS for Mac packages to resolve symbols.

/cc @leculver

**Comment by leculver** [comment]
The end result should probably look something like this:

        {
          "is_managed" : "true",
          "guid" : "81BA78C8-DC79-4B7F-9F7B-530C53DB0F84",
          "token" : "0x6001763",
          "native_offset" : "0x482",
          "il_offset" : "0x00093",
          "filename": "foo.dll",
          "sizeofimage": "0x12345678",
          "timestamp": 0x87654321
        },

We don't need the full filepath (so not "/usr/lib/foo.dll"), just the module name ("foo.dll") so that we know where the frame came from in case we can't symbolize the result.  We should still leave in the guid, since other tools use it now.

**Comment by alexanderkyte** [comment]
Fixed by https://github.com/mono/mono/pull/12126

**Comment by alexanderkyte** [comment]
Fix is on https://github.com/mono/mono/pull/12125
