### ISSUE TITLE
build on windows error

### ISSUE THREAD

**Issue by srxqds** [mono/mono#12040]
I am building mono step by  https://www.mono-project.com/docs/compiling-mono/windows/

## Steps to Reproduce

1. checkout mono with git clone --recursive https://github.com/mono/mono/
2. ./autogen.sh --prefix=$PREFIX --host=x86_64-w64-mingw32 --enable-msvc --disable-boehm
3. make -j4
4. 

### Current Behavior

could not find win32_net_4_x__corlib.dll.sources file

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:

Mono JIT compiler version 5.16.0 (Visual Studio built mono)

## Stacktrace

```
Makefile:20: 警告：覆盖关于目标“test-local”的配方
../../build/library.make:203: 警告：忽略关于目标“test-local”的旧配方
Makefile:20: 警告：覆盖关于目标“test-local”的配方
../../build/library.make:203: 警告：忽略关于目标“test-local”的旧配方
F:/trunk_branch/custom_software/mono/mono/mini/mono-sgen.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
F:/trunk_branch/custom_software/mono/mono/mini/mono-sgen.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
F:/trunk_branch/custom_software/mono/mono/mini/mono-sgen.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
F:/trunk_branch/custom_software/mono/mono/mini/mono-sgen.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
F:/trunk_branch/custom_software/mono/mono/mini/mono-sgen.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
F:/trunk_branch/custom_software/mono/mono/mini/mono-sgen.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
make[8]: *** 没有规则可制作目标“../../build/deps/win32_net_4_x__corlib.dll.sources”，由“../../build/deps/win32_net_4_x__corlib.dll.response” 需求。 停止。
make[7]: *** [../../build/rules.make:215：do-all] 错误 2
make[6]: *** [../build/rules.make:236：all-recursive] 错误 1
make[5]: *** [build/rules.make:236：all-recursive] 错误 1
make[4]: *** [Makefile:56：profile-do--net_4_x--all] 错误 2
make[3]: *** [Makefile:52：profiles-do--all] 错误 2
make[2]: *** [Makefile:639：all-mcs] 错误 2
make[2]: 离开目录“/cygdrive/f/trunk_branch/custom_software/mono/runtime”
make[1]: *** [Makefile:572：all-recursive] 错误 1
make[1]: 离开目录“/cygdrive/f/trunk_branch/custom_software/mono”
make: *** [Makefile:502：all] 错误 2

```

**Comment by jaykrell** [comment]
Short answer:

Add something like one or both of these to $PATH:

`C:\cygwin64\usr\i686-w64-mingw32\sys-root\mingw\bin`
`C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\bin`

You might have to adjust the `c:\cygwin64` part.
Verify they contain libgcc*dll.

Long answer:
This is effectively a cross build.

The "build" system, in autoconf terminology, is Cygwin.
The "host" is specifically mingw.
The "build" system cannot run the "host" binaries.

It is true, that is Windows all around, but it is slightly divergent environments.

Polluting $PATH like this is normally dangerous, but there appears to be a lack of overlap of leaf file names, so it is ok. The Cygwin .dlls start with `cyg`.

Someone should get build=mingw and/or host=cygwin builds to work.
i.e. so that cross builds aren't as common.

And you should try the msbuild support.
And cmake would be nice some day.
