### ISSUE TITLE
Japanese calendar era change

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#12300]
The Japanese Calendar has Japanese Era Names that coincide with the reign of the Emperor.  For most of the modern age of computing that has been the Heisei era, however the Emperor is expected to step down on April 30, 2019.  Which will bring about the beginning of a new era.  Fortunately, this is a rare event, however it means that most software has not been tested to ensure that it will behave with an additional era.

For full details https://blogs.msdn.microsoft.com/shawnste/2018/04/12/the-japanese-calendars-y2k-moment/

CoreCLR fixes:
- https://github.com/dotnet/coreclr/pull/18209
- https://github.com/dotnet/coreclr/pull/19976

CoreFX Tests:
- https://github.com/dotnet/corefx/pull/32304
- https://github.com/dotnet/corefx/pull/29998

**Comment by atsushieno** [comment]
The CoreCLR issue has nothing to do with this era change. The issue is about date formatting to match Japanese style i.e. we Japanese use "元年" (U+5143 U+5E74) instead of "1年" for the first year. I'm not sure if we want that. There is no date format specifier that reflects eras. This is the closest thing I know of:

```
csharp> new DateTime (1989, 1, 8).ToString ("yyyy-mm-dd gg", new CultureInfo ("ja-JP").DateTimeFormat); 
1867-00-01 A.D." 
```

 (it did not even print "平成", meaning that this kind of formatting never worked. I don't think we Japanese expect that to happen. Of course JapaneseCalendar.GetEras() should return the expected values that will include the new value.)

The new era would be just a matter of up-to-date CLDR data which can be generated at `tools/locale-builder`. The latest CLDR seems to already contain a "stub" value for the upcoming era in `common/main/ja.xml`.

```
						<era type="232">明治</era>
						<era type="233">大正</era>
						<era type="234">昭和</era>
						<era type="235">平成</era>
						<era type="236">ＱＱ</era>
```

**Comment by MaximLipnin** [comment]
@atsushieno Thank you for the clarification. 
@marek-safar Should I generate CLDR data as mentioned?

**Comment by marek-safar** [comment]
@MaximLipnin I included more changes made and I think you will most likely have to do both, add new handling and add new data
