### ISSUE TITLE
mono --response does not work with UTF8 response files (or characters)

### ISSUE THREAD

**Issue by dellis1972** [mono/mono#13082]
Related to https://github.com/mono/mono/issues/13081.

As part of the Xamarin.Android effort to reduce the length of our command line arguments when calling the cross compilers we have tried to use `--response`. If a user has non-Ascii characters in the path and/or they use a utf8 formatted file the response file will not be parsed correctly.

## Steps to Reproduce

1. Download and extract 
[ResponseUnicode.zip](https://github.com/mono/mono/files/2884154/ResponseUnicode.zip)
2. Open a mono command prompt and navigate to when you extracted the file.
3. run `mono --response=resp.txt`

### Current Behaviour

If the `resp.txt` file is formatted as `ASCII` you will get the following error.
`Cannot open assembly 'Execütable\Program.exe': Illegal byte sequence.`

If the file is formatted as `utf8` you will get the following error
`Cannot open assembly 'ï»¿ExecÃ¼table\Program.exe': No such file or directory.`

### Expected Behaviour

What should happen is the `Program.exe` should run and print `Hello`

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

Mono JIT compiler version 5.18.0 (Visual Studio built mono)

**Comment by lateralusX** [comment]
Did some investigation, if I remove the BOM in the UTF version it works as expected running the program using the response file as argument. I will add support to ignore the BOM mark if one exist in the file to make sure similar problems are avoided (since saving in UTF8 from editors tends to add that mark into the file). I will also implement logic to handle the parameters in the response file in similar way as we handle parameters in main method. That will most likely take care of the problems seen in https://github.com/mono/mono/issues/13081 as well.

**Comment by lateralusX** [comment]
Assumption will be that the --response file must be encoded in UTF8 (or ASCII), no other encodings will be handled, at least not for now.

**Comment by lateralusX** [comment]
Should be fixed by, https://github.com/mono/mono/pull/13132.
