### ISSUE TITLE
GB18030 INTERNAL ERROR (should not happen)

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#13144]
For certain user data we are getting `SystemException` with the following message:

`GB18030 INTERNAL ERROR (should not happen): GBX 84 32 81 30`

Unfortunately I don't have the original data, but I assume it will be possible to make a sequence to trigger it. <strike>This looks like UTF-8 encoding incorrectly treated as GBX, which could be error in the input data (eg. wrong "charset" specified in email header and the actual content encoded using UTF-8).</strike>

What is certainly problematic is the exception type. This is exposed through `System.Text.Encoding` classes which are not supposed to throw bare-bones `SystemException`.

**Comment by filipnavara** [comment]
Repro:
```c#
using System.Text;

namespace GBTest
{
	class MainClass
	{
		public static void Main(string[] args)
		{
			var encoding = Encoding.GetEncoding("GB18030");
			var str = encoding.GetString(new byte[] { 0x84, 0x32, 0x81, 0x30 });
		}
	}
}
```

**Comment by filipnavara** [comment]
Looks like the character is not defined in the GB18030 charset. NetFX translates the character to `?`.

**Comment by MaximLipnin** [comment]
.Net Core also returns `?` for this repro.

Mono has own support for `GB18030` which uses mapping from http://source.icu-project.org/repos/icu/data/trunk/charset/data/xml/gb-18030-2000.xml :
https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/I18N/CJK/GB18030Source.cs#L99-L135

Mono mapping doesn't contain this range:
`<range uFirst="10000" uLast="10FFFF" bFirst="90 30 81 30" bLast="E3 32 9A 35" bMin="81 30 81 30" bMax="FE 39 FE 39"/>`. 
I'm not sure if it makes any sense but after adding that range mentioned exception disappears.

Other "workaround" is to return some negative result instead of throwing an exception here:
https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/I18N/CJK/GB18030Source.cs#L191
Then further logic would return replacement character `?`.

Possibly @atsushieno can recall anything about it?

**Comment by filipnavara** [comment]
According to Wikipedia the character is in "reserved range" and I believe that's still the case even for recent versions of the GB18030 specification. I would be fine if the code returned '?' or some error code that would later be translated to '?' in the higher layers. Throwing any kind of `ArgumentException` would work for us too, but it's probably not an option for compatibility reasons.

**Comment by atsushieno** [comment]
Sounds like it is simply throwing SystemException where EncoderExceptionFallback or EncoderReplacementFallback is taken into consideration?

(excuse: they were very new in .NET 2.0 while we were at .NET 1.x when we dealt with encodings...!)
