### ISSUE TITLE
AOT of framework assemblies fails with: mono: symbol lookup error: /usr/lib/libmono-llvm.so: undefined symbol: mini_method_is_default_method

### ISSUE THREAD

**Issue by brianrob** [mono/mono#13940]
## Steps to Reproduce

Build dockerfile at https://gist.github.com/brianrob/3b9d7a583e3c59acf469b22b005b5d6e.

### Current Behavior

When running ```for i in /usr/lib/mono/gac/*/*/*.dll; do mono --aot=llvm $i; done``` to AOT the framework, there are a number of assemblies fail with the error ```mono: symbol lookup error: /usr/lib/libmono-llvm.so: undefined symbol: mini_method_is_default_method```.

### Expected Behavior

All framework assemblies are precompiled without any errors.

## On which platforms did you notice this

[ ] macOS
[ X ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.3.0.77 (tarball Sat Apr  6 10:29:10 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by brianrob** [comment]
@directhex, @alexanderkyte, @marek-safar

**Comment by brianrob** [comment]
Thanks @directhex.  With #13955 do things start to work or is System.Core still broken?

**Comment by directhex** [comment]
13955 fixes your specific issue, but there are no Linux packages including the change yet.

**Comment by brianrob** [comment]
Great.  Is that something that I'll need to wait until tomorrow for?

**Comment by directhex** [comment]
I can force a nightly to dispatch once it successfully builds on Mac (the nightly job uses "last successful Mac build" as the commit to use), then it'll be a few hours & might still fail due to other factors (Roslyn interacts super badly with our memory model on ARM so ARM builds often crash the compiler)

**Comment by brianrob** [comment]
Thanks @directhex.  Let me know when there's a nightly with this fix and I will try it.

**Comment by directhex** [comment]
I've forced a dispatch of a Linux build, 6.3.0.115 is the one to watch

**Comment by brianrob** [comment]
Is there a build status page or something that I can watch for completion and publishing?

**Comment by directhex** [comment]
The latest .115 build failed again due to the Roslyn-on-ARM issue (aaaaaaaaaAAAAaaaAAAAaaaAAAAaaaAAAAAaaaAAAAAaaAAAAAaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAaaa)

Rather than re-dispatch it, since we now know we need a newer version (.134) I'm going to wait for that to try and build in its own time, and check in on it in the morning.

**Comment by brianrob** [comment]
Sounds good.  Thanks.

**Comment by directhex** [comment]
Marking this closed, since it's definitely fixed, and the fixed build is almost done publishing.
