### ISSUE TITLE
Help wanted (.Net Standard project Build in linux and deploy it to windows)

### ISSUE THREAD

**Issue by tharanga2006** [mono/mono#14154]
Background
I'm using my build agent as bamboo. It is running on linux,
Currently I have a project which is developed on .Net 4.5 /.net standard 2. ( It is a wcf project )

Problem
I need to build this project through bamboo agent that is running on linux.
To build project I have used xbuild command.
But It build binaries for linux os. But I need to build binaries for windows cause I wanted to deploy them in windows. 
I think their should be a way to tell that xbuild to build my binaries for windows.
Please give me some light on this,

**Comment by nkosi23** [comment]
What do you mean? .net binaries are cross-platform by design, you can use the binaries built on linux for your windows environment. .net does not compile to native code (unless you use AOT compilation), your executable is an Intermediate Language that then gets executed by the .net runtime (mono or  .net). So the binary you use on both platforms are the same. 

We used to build in Visual Studio and run the binaries on Unix using mono without problem. The other way should work the same, just copy and paste your binaries.

**Comment by tharanga2006** [comment]
Hi nkosi,
Thanks you are correct. 
I have use my bamboo agent run on linux and used  Linux docker pre-install mono and cake to build my .net standard and core project.
