### ISSUE TITLE
Profiler does not work for Windows (5.20.1 Stable)

### ISSUE THREAD

**Issue by markmwilkinson** [mono/mono#14225]
## Steps to Reproduce

1. Install latest Stable Mono Release 5.20.1 Stable (5.20.1.19) for Windows (Mono-64-bit (no GTK#))
2. Using the hello world example from https://www.mono-project.com/docs/getting-started/install/windows/ to create hello.exe 
3. run mono --profile=log hello.exe  (or mono-sgen --profile=log hello.exe)

### Current Behavior
output.mlpd file is not generated 
Additionally, there are no error messages

### Expected Behavior

output.mlpd file is should generated 

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ x ] Windows

**Version Used**:
5.20.1 Stable (5.20.1.19) for Windows 
Mono-64-bit (no GTK#)

## Stacktrace

none

**Comment by lambdageek** [comment]
@lateralusX could you take a look at this

**Comment by lateralusX** [comment]
Yes I can take a look, I believed this has been a known issue for a while since it was never been ported over to Windows when profiling support was refactored.

**Comment by markmwilkinson** [comment]
Hi lateralusX :) Did you get a chance to check if your expectation is correct please?
Thanks
MarkW

**Comment by lateralusX** [comment]
Yes, I verified that the log profile is not included on Windows builds and the mechanism used by new profiler infrastructure is quite Unix specific (at least to find symbols in current executable). I will fix this to make sure it will work under Windows build. Until then you should be able to build log profiler on your own as a DLL, export needed methods and make sure it is loadable, the default log profiler should be named mono-profiler-log.dll. Another alternative (if you build from source and use Mono runtime as a dynamic linked library, default) is to add the log profiler source into the build of dynamic library. I also noticed that there are some constructs in the current log profiler implementation that doesn't work well on Windows without adjustments, so that is also work that needs to be done.

**Comment by markmwilkinson** [comment]
Thank you very much for all this info and suggestions :)

**Comment by lateralusX** [comment]
I added it to the project board, but not planned yet. I guess you didn't manage to include it on your own? If you are looking into just profiling code execution you could use full AOT and regular profiling utilities on Windows will work since it is then native code including symbol information. If you are looking into profiling internal Mono runtime event's you will need the log profiler or use alternative statistics counters. What is your timeframe? I will try to get to looking into fixing it this or next week.

**Comment by markmwilkinson** [comment]
I have not tried to make a log profiler dll yet ... that might be my next task. I asked for an ETA simply to check if your proper fix might be arriving quicker than it would take me to make the dll :) What I need to profile is Garbage Collection and get info about what is on the heaps. the project is set up to use mono embedded and AOT

**Comment by lateralusX** [comment]
Fixes to fix log profiler, https://github.com/mono/mono/pull/14425. This will at least make sure the log profiler can run on Windows, but there might be other issues with the actual profiler on Windows. If that's the case it's a bigger work item going through the complete support.

**Comment by lateralusX** [comment]
https://github.com/mono/mono/pull/14425 merged.
