### ISSUE TITLE
Document/fix functions currently not doing GC safe enter/exit around blocking OS API calls.

### ISSUE THREAD

**Issue by lateralusX** [mono/mono#14377]
During work porting hybrid/coop suspend over to Windows I looked over the GC safe enter/exit used through Mono runtime code. I found a couple of places where we don't do it, and after some further investigation I believed that most seemed fine (at least the same behavior on Windows/Unix), but we miss documentation around these calls why they are not using GC enter/exit safe. Below is just a dump of methods that doesn't use GC enter/exit (might be more) for various reasons when calling into OS API's that could block. We should at least document why they don't need or shouldn't do it or if there is no reason not do it, add GC safe transition around OS API calls that could block (for any reason):

mono_dl_open_file
mono_file_map_error
mono_file_map
mono_file_unmap
mono_mprotect
mono_coree_set_act_ctx
mono_load_coree
open_handle
mono_mmap_open_file
mono_mmap_close
mono_mmap_flush
mono_mmap_map
mono_mmap_unmap
mono_process_create_process
ves_icall_System_Diagnostics_Process_ShellExecuteEx_internal
ves_icall_System_Diagnostics_Process_GetProcesses_internal
ves_icall_System_Threading_Semaphore_CreateSemaphore_icall
ves_icall_System_Threading_Semaphore_ReleaseSemaphore_internal
ves_icall_System_Threading_Semaphore_OpenSemaphore_icall

Another idea/thought, instead of documenting why it can't be used in various places, we could fix the GC enter/exit safe methods to be noops if called within a context where its currently not supported (during parts of init for example). If we could support that, then we could just add the transitions on all places needed and no need for additional documentation. Note, the GC enter/exit safe macros are changed/replaced by products, so the noop needs to go into underlying functions shared by all clients using Mono runtime.

**Comment by lambdageek** [comment]
@CoffeeFlux This is another good task to get familiar with the code organization in the runtime.

**Comment by CoffeeFlux** [comment]
After talking, it was decided that at least initially it would be best to evaluate and document all these functions, ensuring they behave consistently across platforms, and then evaluate the noop solution later down the line.

**Comment by CoffeeFlux** [comment]
After discussion, we decided that going through and auditing whether these functions can safely transition, ensuring it's consistent across platforms, and if not documenting why is the best approach for now. The noop solution can be evaluated at a later date.

**Comment by alexischr** [comment]
Another library that needs to be similarly audited is the CoreFX PAL as big parts of it are used via P/Invoke by the current Mono BCL (and all of it will be used with .NET 5 Mono):https://github.com/mono/corefx/tree/master/src/Native/Unix/System.Native

The biggest "hint" for a blocking call* in these functions is the `while ((syscall(..))&& errno == EINTR` motif. When such a call is found:

* The while loop needs to be broken up since we actually allow interrupting blocking calls: https://github.com/mono/corefx/commit/17804432d376b3ef6bf6db4edaa68a910b18e1b1#diff-7b3eb1dbaf8618b08b4b6cf720e4d36a

* The P/Invoke must be substituted with an icall bind + managed implementation of the broken up while loop (transitioning out of the icall processes the `EINTR` if its source by the runtime itself; if it's not caused by the runtime, the syscall does need to be retried): https://github.com/mono/mono/blob/2a5e8f0c371f6a798f1822eea5e0ee19242cd8f7/mcs/class/System/corefx/Unix/Interop.Read.cs#L31-L49

* The icall must be implemented with the GC safety transitions: https://github.com/mono/mono/blob/2a5e8f0c371f6a798f1822eea5e0ee19242cd8f7/mono/native/pal-icalls.c#L42-L51

For now, you could start from the BCL code and find which functions from the PAL are actually being used currently. In the future it is expected that all of them will be used by Mono.

**Comment by jaykrell** [comment]
Nice diligence!

I wonder if we can somehow build with read/write/etc. not available and get errors, if they don't call mono_coop_read, etc. (I just made up those names, which granted, then call read/write/etc.)

**Comment by jaykrell** [comment]
There is a GNU ld feature where it can call wrappers for you. But that might be kinda at the wrong level and not portable enough.

**Comment by lambdageek** [comment]
@alexischr @CoffeeFlux Could you folks open a new issue for the PAL audit: https://github.com/mono/mono/issues/14377#issuecomment-497247439

**Comment by jaykrell** [comment]
Is this a job for macro-produced wrappers?
` ves_icall_Interop_Sys_Read` looks like it but one would have to survey more examples.
