### ISSUE TITLE
SqlClient: Specified parameter name 'Parameter1' is not valid

### ISSUE THREAD

**Issue by danielvanmil** [mono/mono#14450]
When using mono with a database task I'm having the following issue:

https://github.com/dotnet/corefx/issues/29391

The solution is in the System.data.SqlClient 4.5.0-preview2-26406-04, but I think this is included in the System.Data package of mono, so I cannot update the package easily?

Is there another fix/workaround/solution

## Steps to Reproduce

1. https://github.com/dotnet/corefx/issues/29391

### Current Behavior

https://github.com/dotnet/corefx/issues/29391

### Expected Behavior

No error

## On which platforms did you notice this

[X] Linux

mono 5.20.1.19

**Comment by outring** [comment]
The issue was fixed in CoreFx [1.5 years ago](https://github.com/dotnet/corefx/pull/29614) and released with CoreFx 3, but the current [mono's CoreFx fork](https://github.com/mono/corefx) is way behind upstream even in master, not mentioning release branches. I'm waiting for this issue to be resolved for 2 years already, it's sad to have it fixed for 1.5 years and not yet got to mono :(

**Comment by steveisok** [comment]
The squeaky wheel gets the grease ;-)

Thanks for the nudge.
