### ISSUE TITLE
[WASM] ClientWebSocket can't use URI

### ISSUE THREAD

**Issue by netchkin** [mono/mono#14582]
## Steps to Reproduce

1. Create a new Blazor Client Side project
2. Download nuget WebAssembly.Net.WebSockets@3.0.2
3. Write the following code in "functions" segment of a Blazor view:

```csharp
protected override async Task OnInitAsync()
{
  var c = new ClientWebSocket();
  await c.ConnectAsync(new Uri("https://localhost:44330/ws"), CancellationToken.None);
}
```

### Current Behavior

Firefox 67 on Windows 10 says:

> TypeError: this.mono_string_get_utf8 is not a function

### Expected Behavior

Actual call to ws gets made

## On which platforms did you notice this

Windows

**Version Used**:

wasm

**Comment by lewing** [comment]
Someone is producing nugets using our unpublished package names but they are not from mono our team and I have no idea what is in them.

**Comment by netchkin** [comment]
oh, ok, what package should I use instead?

**Comment by kjpou1** [comment]
netchkin

Can you try `new Uri("ws://localhost:44330/ws")` or `new Uri("wss://localhost:44330/ws")` instead of `new Uri("https://localhost:44330/ws")`.

If anything you should be getting an error of `invalid protocol` when you use `http` or `https` instead of `TypeError: this.mono_string_get_utf8 is not a function`.  

Something else to try is instead of using `localhost` replace it with the actual ip address.

There is a sample application here:  https://kjpou1.github.io/websocket/

**Comment by kjpou1** [comment]
closed by https://github.com/mono/mono/pull/15274
