### ISSUE TITLE
Ephemeron tests fail on 6.0 bump

### ISSUE THREAD

**Issue by Therzok** [mono/mono#14882]
## Steps to Reproduce

1. See disabled test suite here: https://github.com/mono/monodevelop/commit/058b5f4be19db87a5b0679fb186d4bc612a5fdc8
2. Run that test suite, observe weak references are not freed
3. Did not happen in 2018-08

### Current Behavior

WeakRereferences are not freed

### Expected Behavior

Object held in memory just by WeakReference and ConditionalWeakTable should be freed.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
MonoFramework-MDK-6.0.0.281.macos10.xamarin.universal

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment]
@BrzVlad any update on this?

/cc @SamMonoRT

**Comment by BrzVlad** [comment]
Fixed monodevelop tests.

From this bug it is worthwhile to note the following scenario : Assume you have an object that is no longer referenced from anywhere and you have a weak reference for it. If you wait for the object to die by doing something like `while (weakRef.IsAlive) doSomething ();` then you can actually prevent the object from ever being collected, because weakRef.IsAlive fetches the object address so now you can be left with a reference to it on the stack.
