### ISSUE TITLE
Some shipped assemblies in mobile profile are not properly strong-named

### ISSUE THREAD

**Issue by garuma** [mono/mono#15398]
Versions:
- Xamarin.iOS 12.14.0.87 (72c4a8ab9045f809eda72bf8416043bceb036629)
- mono 2019-02

The following assemblies (at least) that are shipped as part of Xamarin.iOS are not properly strong-named but instead have been left with the delay-signed flag on which trips a sign check on the Visual Studio side:

- system.drawing.common.dll
- system.net.http.dll
- system.numerics.dll

Invoking `sn -v` on them yields:

```
Assembly ./lib/mono/Xamarin.iOS/System.Numerics.dll is delay-signed but not strongnamed
```

**Comment by marek-safar** [comment]
@akoeplinger thoughts on this?

/cc @steveisok

**Comment by akoeplinger** [comment]
I checked the assemblies on the Mono side and they are correctly strong named and not delay-signed.

What seems to happen is that Xamarin.iOS is re-signing the assemblies with their own key here: https://github.com/xamarin/xamarin-macios/blob/d16-2/builds/Makefile#L676-L678

This makes the assemblies delay-signed. What I don't understand is why only the three files are tripping up the sign check in VS since _all_ of the BCL assemblies are processed this way and have been for the last couple releases as far as I can see.

Note: this is no longer an issue for Mono in d16-3 since the BCL assemblies are consumed as-is from Mono. The Xamarin.iOS.dll however is still delay-signed.

**Comment by chamons** [comment]
This issue was moved to xamarin/xamarin-macios#6459
