### ISSUE TITLE
Debian stable-stretch version is now Mono 6.0.0 (not released yet)

### ISSUE THREAD

**Issue by onefang** [mono/mono#15778]
Last week the version of Mono in your Debian stable-stretch package repo updated to 5.20.1.34 (which is the version currently installed on my boxen).  Then the next day it was updated again to 6.0.0, which is listed on https://www.mono-project.com/docs/about-mono/releases/ as "Mono 6.0.0 (not released yet)"  and "These notes are for a current or upcoming PREVIEW RELEASE and might not reflect the final release.".  That doesn't sound like a stable release to me.

I need it to be stable.  What's going on?

**Comment by filipnavara** [comment]
The release notes were not updated yet but the version is propagated to stable.

**Comment by knocte** [comment]
Why is mono 6.0 not propagated to stable channel in macOS then?

**Comment by MattL0** [comment]
Mono 6.0.0113 was preview. 

They put it as stable when that got problem with 5.0.1.34

**Comment by MattL0** [comment]
I have installed the vs build wich is 5.18.1.28 


They update less often but you wont have problem like this

**Comment by rmunn** [comment]
See also https://github.com/mono/website/issues/452 which is a request for the release notes for 6.0. Since the Debian and Ubuntu stable channel has the packages, it's time for release notes. If the release notes aren't ready because the package wasn't actually ready for release, then it was a mistake to push it into the stable channel and that should be communicated. Either way, the website needs to have *something*. Right now https://www.mono-project.com/docs/about-mono/releases/ says "The latest stable release is 6.0.0 Stable (6.0.0.313)", but just below the page says "Mono 6.0.0 (not released yet)". This inconsistency needs to be resolved one way or the other.

**Comment by Alovchin91** [comment]
The release notes are still not there. This is Microsoft, of course, so you don't expect them to communicate in any meaningful way - they are just above the community. Still they install 6.0.0.313 with Visual Studio for Mac 2019 Update 2 - so maybe it's stable enough for most scenarios.
