### ISSUE TITLE
Adding system.drawing.common to a Blazor app causes the linker to fail.

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#15806]
_From @PhilPJL on Monday, July 22, 2019 10:48:58 PM_

### Description
Adding system.drawing.common to a Blazor app causes the linker to fail.
system.drawing.common is advertised as supporting .NET Standard 2 with no other dependencies.  system.drawing.common is a dependency of other Nuget packages such as ClosedXml which then have the same linker error.

### To Reproduce
Dotnet core 3.0.100-preview6-012264
Visual Studio 16.2.0 Preview 4.0
Create new ASP.NET Core Web Application - specify 'Blazor WebAssembly App'.
Build succeeds.

Add Nuget package system.drawing.common.  Build now results in this error message: 
[linker_error.txt](https://github.com/aspnet/AspNetCore/files/3419398/linker_error.txt)

Demo app: [WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3419400/WebApplication1.zip)

_Copied from original issue: aspnet/AspNetCore#12457_

**Comment by mkArtakMSFT** [comment]
_From @mkArtakMSFT on Tuesday, July 23, 2019 4:42:47 PM_

Thanks for contacting us.
This is not an area we control.
If you still have this problem, feel free to report it on the https://github.com/mono/mono repo.

**Comment by mkArtakMSFT** [comment]
_From @PhilPJL on Tuesday, July 23, 2019 6:25:43 PM_

@mkArtakMSFT, @SteveSandersonMS 
I'm not sure it's my job to chase disparate teams regarding an issue with Visual Studio and Blazor integration.  If you don't consider this issue important then so be it.  I guess I'll wait for Blazor 3.1 and try again.

**Comment by filipnavara** [comment]
> advertised as supporting .NET Standard 2 with no other dependencies

Advertised where? It has dependency on the native libgdiplus library which itself has dependency on Cairo, FreeType and other libraries. This native code was never ported to WebAssembly in the first place.

**Comment by PhilPJL** [comment]
@filipnavara  This is what I mean:
![image](https://user-images.githubusercontent.com/271656/61749648-24c5f500-ad9b-11e9-846a-5ae82bcd642b.png)

**Comment by marek-safar** [comment]
Could you include the actual error?

**Comment by filipnavara** [comment]
@PhilPJL Unfortuantely the NuGets only list managed dependencies, not native libraries, so it is not accurate.

**Comment by PhilPJL** [comment]
@marek-safar  The error is attached to [https://github.com/aspnet/AspNetCore/issues/12457](https://github.com/aspnet/AspNetCore/issues/12457).

**Comment by Tewr** [comment]
@PhilPJL : I just noted that the error message you attached is the exact same as for [linker #379](https://github.com/mono/linker/issues/379), and as that fix is not integrated in blazor yet. 

However, I also noted that the output build window console gives an error which is more explicit. 
For example, with EPPlus, I run into the infamous msbuild error where it drops random letters in the assembly paths (which linker 379 is supposed to solve).

However, If I reference system.common.drawing directly, I get the same old build error - but in build output I get a very explicit `Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Drawing.SizeF System.Drawing.Image::get_PhysicalDimension()' in assembly: 'System.Drawing.Common.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Drawing.SizeF`, which is an expected error I guess (compared to the one above). 

So by looking at the build output you might be able to pinpoint if this is due to the msbuild bug (if you get an error with unable to find assembly, then it is.)

I guess for now turning off the linker is our only option, too bad there is no option (at least in blazor) to turn off the linker for specific assemblies.

**Comment by bwjunkie** [comment]
Success for me, I added Nuget System.Drawing.Common to my Preview7 Blazor core3 (signalR) application and used it to Convert a Tif to a GIF, worked fine in production server (windows server).

System.Drawing.Bitmap.FromStream(ms1).Save(msPNG, System.Drawing.Imaging.ImageFormat.Png);

Because Chrome won't show TIF files.

**Comment by PhilPJL** [comment]
@bwjunkie Yes, agreed it works fine server side.  Not for the client though.

**Comment by lewing** [comment]
This should be fixed by https://github.com/aspnet/AspNetCore/pull/16808 if it wasn't already resolved

**Comment by ugumba** [comment]
Linker error is fixed, but you risk PlatformNotSupportedException (e.g. from new Bitmap(w,h)).  I had to try!  :-)

**Comment by stefanloerwald** [comment]
@ugumba How did you work around the `PlatformNotSupportedException` on `new Bitmap(w,h)`?

**Comment by ugumba** [comment]
@stefanloerwald, I didn't. I think I ended up using ImageSharp. This was just a POC, so abandoned now.
