### ISSUE TITLE
DeflateStream leaks native memory if not explicitly disposed

### ISSUE THREAD

**Issue by curia-damiano** [mono/mono#15825]
I have a small console application, that uses a managed library to create PDF.
The PDF generation is run in a loop.

In Windows, with .NET Framework, the memory stays constant.

In Mac, with Mono latest version, the same application continues to grow memory.

My suspect is that the garbage collector has some bug and is not releasing the memory.

I've also tried to allow at the end of each loop the following instructions:
                            GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
                            GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced, true, true);
                            Console.WriteLine(GC.GetTotalMemory(true));
And while in .NET Framework the total memory is absolutely constant, in Mono it is contantly growing.

FYI this issue is very similar to https://github.com/mono/mono/issues/15751, but in this case I have a simpler repro project.

## Steps to Reproduce
1. Run in Visual Studio for Mac the attached application
2. In Activity Monitor check the used memory

### Current Behavior
Bug in Mono, it is not correctly tracking the allocated memory and because of this it is constantly growing.

### Expected Behavior
In Mono the total memory stays contant like in Windows.

## On which platforms did you notice this

[X] macOS
[X] Linux
[ ] Windows

**Version Used**:
Mono 6.0.0.311
Visual Studio for Mac 8.2

**Comment by curia-damiano** [comment]
This is the repro project, to be tested on .NET Framework (Windows) and Mono (Mac/Linux)
[MemoryLeakTest.zip](https://github.com/mono/mono/files/3430638/MemoryLeakTest.zip)

**Comment by marek-safar** [comment]
Mono does not have precise stack scanning and unless you extract the tight loop into method call this is expected

**Comment by curia-damiano** [comment]
Hi Marek,
Thank you for your quick reply.
I would need a clarification: "unless you extract the tight loop into method call this is expected" -> does this mean that if I place the loop in a method call, this will fix the memory issue? Or do I need to place the content of the loop (and not the loop itself) in a method?

Do you have any reference about this topic?

**Comment by Suchiman** [comment]
> in Mono it is contantly growing

How does not having precise GC faciliate constant growing? While this will cause the stack roots to stay alive for the duration of the method, the actual variables will be rewritten on each iteration of the loop, so this should only have a constant higher memory comsumption, not constant growing memory consumption.

I would imagine that .NET would exhibit the same behavior then when running in debug since that disables eager root collection and thus keeping variables alive until the end of the method.

**Comment by curia-damiano** [comment]
Hi Marek,
I attach the revised sample project where I moved the pdf generation in an inner method.
The memory leak in Mono is still there...
[MemoryLeakTest.zip](https://github.com/mono/mono/files/3437877/MemoryLeakTest.zip)

**Comment by BrzVlad** [comment]
@curia-damiano Thanks for the report.

This is a bug in Mono's DeflateStream. A DeflateStream makes use of a DeflateStreamNative. The DeflateStreamNative object allocates a gchandle to itself, which makes the object live forever unless it is explicitly disposed. The parent DeflateStream explicitly disposes of the DeflateStreamNative only if it is explicitly disposed itself, and, because it doesn't have a finalizer, it will leak if the user code doesn't call Dispose.

Here is an even easier and clearer repro : https://gist.github.com/BrzVlad/33a5eb6f0fd004eaf91f8d80eb0cf9ec . Make sure to have an .xml file in the current folder so the there is stuff to compress/decompress.

@steveisok I'll leave it up to your team to produce a fix. I guess the easiest is to add a finalizer to DeflateStream, but maybe other ways can be explored for perf sake.

**Comment by curia-damiano** [comment]
Thank you guys for your help!
