### ISSUE TITLE
Fiddler with Mono 5.20 -   Failed to create certificate 

### ISSUE THREAD

**Issue by MarcoR83** [mono/mono#15904]
## Steps to Reproduce

1. Run Telerik Fiddler 4.6 on Mono 5.20
2. Enabled HTTPs decryption
3. Open Page with HTTPs in Browser (i.e. Firefox, does not matter)

### Current Behavior

HTTPs is not decrypted. Error is logged in Fiddler:

Failed to create certificate for www.linux.org.ru: Operation is not supported on this platform.
  at System.Security.Cryptography.X509Certificates.X509Certificate2.set_PrivateKey

### Expected Behavior

Error should not occur, so that HTTPs decryption works.

After Downgrading to 5.18 it works as expected. 
Also found this Issue on Telerik Forum:
https://www.telerik.com/forums/sll-decrypt-dont-work-on-linux#LlvgQw1ZAEOFMmIYEIXP3w

## On which platforms did you notice this

[ ] macOS
[X ] Linux
[ ] Windows

**Version Used**:

Mono 5.20.1 (not working) 
Mono 5.18.1 (working)

Mono JIT compiler version 5.18.1 (makepkg/9cb3348c311 Thu Mar 21 17:20:20 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
TLS:           __thread
SIGSEGV:       altstack
Notifications: epoll
Architecture:  amd64
Disabled:      none
Misc:          softdebug
Interpreter:   yes
LLVM:          supported, not enabled.
Suspend:       preemptive
GC:            sgen (concurrent by default)
## Stacktrace

failed to create certificate for www.linux.org.ru: Operation is not supported on this platform.
2.
  at System.Security.Cryptography.X509Certificates.X509Certificate2.set_PrivateKey (System.Security.Cryptography.AsymmetricAlgorithm value) [0x00000] in <e8eb3d7a311640f484845e45cbec8973>: 0
3.
  at BCCertMaker.BCCertMaker.CreateCertificateFromCA (System.String sCN, Org. Bouncy6Castle.X509.X509Certificate caCert, Org.BrcyCastle.Crypto.AsymmetricKeyParameter caKey) [0x00377] in <186d36066206 6 5 6 3 3 3 3 3 6 6 6 6 6 6 6 6 6 6 6 6 6 3 3 3 3 3 3 3 3 5 3 3 5 3 3 5 3 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 3 3 3
4.
  at BCCertMaker.BCCertMaker.MakeNewCert (System.String sHostname) [0x00102] in <186d138a6ba64111bc4131af9c9cbf93>: 0

**Comment by marek-safar** [comment]
@steveisok please have a look, this looks like a regressoin

**Comment by baulig** [comment]
Both `X509Certificate` and `X509Certificate2` are immutable - you cannot modify them by setting the `PrivateKey` (or any other) property.   This behavior is consistent with .NET Core: 

https://github.com/dotnet/corefx/blob/37f316e1de562bc31acab2496540a865189da918/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate2.cs#L223

See also for instance

https://github.com/dotnet/corefx/blob/37f316e1de562bc31acab2496540a865189da918/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs#L534

Since it's a third-party library that's calling the `X509Certificate2.PrivateKey` property setter, they need to change their code.
