### ISSUE TITLE
[MacOS Modern] Tests from System.Net.Security fail on mac os x modern.

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#15929]
After bumping mono 2019-06 to 17ac7d several tests in the System.Net.Security fail on Mac OS X modern YET they do pass on mac os x full. The tests have been disabled in xamarin-macios. Useful information:

Failing tests can be found here: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/10873/Test_20Report/

There are diff exceptions, but everything looks to be due to the same root cause.

**Comment by filipnavara** [comment]
Are you sure it's not just transient network errors? Most of them are "Connection timeout".

**Comment by mandel-macaque** [comment]
They are, but if that is the case, why don't they happen in Mac OS X Full?

**Comment by baulig** [comment]
Do we run these tests as part of the Mono build on OS X desktop?

**Comment by mandel-macaque** [comment]
@baulig maybe @akoeplinger knows, I know we run them on the xamarin-macios CI on the bots.

**Comment by baulig** [comment]
- [`LinkAllRegressionTest.TrustUsingOldPolicy`](https://github.com/xamarin/xamarin-macios/blob/fe8db4df2756491e12ebf58a6f0b03511bf4d4f9/tests/linker/ios/link%20all/LinkAllTest.cs#L207) is using the old `ServicePointManager.CertificatePolicy` that's been obsolete for ages.  We should probably disable or remove that test.
- `CryptoTest.TrustUsingNewCallback` should not fail with a connection failure.  Could this possibly be a transient networking issue?

**Comment by baulig** [comment]
`System.Net.Security.Tests.ClientDefaultEncryptionTest.ClientDefaultEncryption_ServerAllowNoEncryption_ConnectWithEncryption` - these and similar tests need to be disabled on Mono.

The test is here: https://github.com/mono/corefx/blob/master/src/System.Net.Security/tests/FunctionalTests/ClientDefaultEncryptionTest.cs.

We do not support the `EncryptionPolicy` argument and assume `EncryptionPolicy. RequireEncryption`.   There is no scenario that I could think of where you'd ever want to use either `AllowNoEncryption` or `NoEncryption` and allowing these values also seemed an unnecessary security risk for me when I wrote the backend code.

Any test that's using an `EncryptionPolicy` value other than `EncryptionPolicy. RequireEncryption` needs to be disabled on Mono - we can do so by adding

    [SkipOnTargetFramework(TargetFrameworkMonikers.Mono)]

**Comment by baulig** [comment]
`System.Net.Security.Tests.ClientDefaultEncryptionTest.ClientDefaultEncryption_ServerRequireEncryption_ConnectWithEncryption` - I don't understand why this one is failing.

**Comment by baulig** [comment]
`System.Net.Security.Tests.ApmSslStreamSystemDefaultTest` and everything below - those are run in the desktop profile, so those should pass.

**Comment by baulig** [comment]
Could we possibly re-enable those tests and see what happens?

**Comment by steveisok** [comment]
@mandel-macaque Can you re-enable the tests and see?  Or if you have already, let us know if this is still an issue?

**Comment by thaystg** [comment]
I enabled the tests but they continue broken, so I disabled again.

**Comment by steveisok** [comment]
@baulig see if you can clear this up fairly quick.

**Comment by baulig** [comment]
@thaystg Could you please link the failures?

**Comment by baulig** [comment]
https://github.com/xamarin/xamarin-macios/pull/7192/commits/531bd8ed7f82b11535bff9d86fabd883c43a662d

**Comment by baulig** [comment]
Okay, I finally see what's going on here - and can reproduce it locally.  This is due to those keychain dialogs that keep popping up.  When you do `make runner` locally while your keychain is unlocked, those tests will pass.

To reproduce this locally, look at `/tests/xharness/tmp-test-dir/Mac OS X BCL tests group 4-mac-modern/bin/AnyCPU/Mac OS X BCL tests group 4/Debug/com.xamarin.bcltests.Mac OS X BCL tests group 4.app/Contents/MacOS/com.xamarin.bcltests.Mac OS X BCL tests group 4`.

If you run that from a shell, you get this popup dialog.

Now to reproduce the CI setup, run it outside a login shell - for instance by doing `su martin` - and then because it's not a UI shell anymore, it can't display that dialog and immediately fails.

However, if you run it via `make runner`, then you don't get those popups.  We should investigate why that's happening.  Maybe there's some additional keychain / code sign thing happening when using the runner?

**Comment by steveisok** [comment]
@mandel-macaque Based on Martin's comment, I think this should be handled in xamarin-macios.
