### ISSUE TITLE
What is MonoStringHandle?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#16079]
I want to figure out what is MonoRawHandle such as MonoStringHandle, because I want delete or recycle some MonoString.

I have some question about MonoRawHandle：

1.What is difference between MonoStringHandle and MonoString, why define MonoStringHandle?

2.If we delete some MonoString, should we handle for free MonoStringHandle, and how can I free it?

**Comment by jaykrell** [comment]
In general FooHandle is
```
typedef struct {
  Foo** x;
} FooHandle;
```

`MonoRawHandle` is `void**`.
It is a kinda "generic" "handle".
It is kinda to "handle" what `void*` normally is to pointer.

It is larger topic though, in that, this stuff is intended for "coop", where we somewhat carefully handle managed pointers, so that we can cooperatively suspend. So that they aren't in registers.
But, there has been a refinement or two.
They can be in registers. As long as they are also in handles.

Originally they weren't pinning. So they could not be in registers.
Now they are pinning. So they can be also in registers -- their existance elsewhere, in a handle, prevents both their collection, and their movement. So copies in a register are safe.
