### ISSUE TITLE
Unable to authenticate against TFS NuGet package source

### ISSUE THREAD

**Issue by mrward** [mono/mono#16296]
## Steps to Reproduce

From Developer Community - https://developercommunity.visualstudio.com/content/problem/696532/unable-to-restore-nuget-packages-from-a-private-fe.html

Do not have a good step of steps.

1.  TFS privately hosted providing NuGet packages
2. PAT token created for the package source and registered with nuget on the Mac machine.
2. nuget restore solution.sln

### Current Behavior

Response status code does not indicate success: 401 (Unauthorized).

GSSAPI operation failed with error - An unsupported mechanism was requested (unknown mech-code 0 for mech unknown).

Downgrading from Mono 6.0 to Mono 5.18.1.21 fixes the problem.

### Expected Behavior

NuGet restores.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono 6.0 - Fails.
Mono 5.18.1.28 - OK

**Comment by marek-safar** [comment]
@steveisok this looks like another unexpected regression

**Comment by steveisok** [comment]
@mrward Any idea if there's basic auth turned on?

**Comment by mrward** [comment]
@steveisok The customer posted a screenshot of their [IIS config](https://developercommunity.visualstudio.com/content/problem/696532/unable-to-restore-nuget-packages-from-a-private-fe.html?childToView=698111#comment-698111) in a private comment.

**Comment by baulig** [comment]
I have tried this on Windows using several different NuGet versions in PowerShell and couldn't get it to work with the PAT and a private feed on DevOps.

Do you have any instructions on how to reproduce this?

**Comment by mrward** [comment]
No I do not have a way to repro it. You would need to contact the customer who posted the original developer community bug report.

**Comment by baulig** [comment]
Since I was unable to get it to work on Windows, this might also be a problem with NuGet - or DevOps not accepting those PAT's.

**Comment by squinn7** [comment]
I am the customer that reported issue on the developer community so if you need any input let me know.

Our issue is specifically on Mac OS, there we need to use the PAT but on the upgraded version of mono it fails. When troubleshooting we were able to fix this by reverting the version of Mono.

Our server is running TFS 2018 update 3

**Comment by baulig** [comment]
I'm still not convinced that this is a Mono issue and unless we can we some instructions on how to reproduce this using .NET on Windows, I don't think there's much we can do.

**Comment by squinn7** [comment]
I have worked on recreating this issue in mono running on windows but I can't. However, this issue is still present on the latest version(6.4) which I upgraded to(mono/xcode11/Visual Studio for mac) iOS 13 support. With the Xcode upgrade I am not sure I can roll back at this point.

I am not sure it is strictly a mono issue but it certainly has something to do with Mono running on mac OS and of course rolling back mono did fix the issue.

At this point, we are stopped dead, we can't restore projects in visual studio for mac so it's almost impossible to work in that environment now.

I can offer any help you might need in reproducing this or ruling it out to get to the root cause.

**Comment by squinn7** [comment]
Also, we have upgraded to Azure DevOps Server 2019 Update 1 patch 1 since reporting this issue but that hasn't seemed to change the behavior in any way.

**Comment by steveisok** [comment]
Seeing that the original error contains a reference to the GSS api, I wonder if NTLM is being used?

**Comment by steveisok** [comment]
@EgorBo Do you think it could be something w/ that?  Also might explain why downgrading works.

**Comment by squinn7** [comment]
To provide some further info, we found if we disabled anonymous authentication in the IIS and leave only windows authentication in place. We can log in from Mac OS. This however, causes a conflict. We need to have Anonymous authentication active to be able to use the build agent.

We have been working frantically to find a workable solution. At this point, we just switch off the authentication mode when we need to use mac OS.

One additional item, if a successful auth happens, it won't immediately stop working if the IIS configuration is changed. It seems that the authentication stays valid for around a day before it won't authenticate anymore.

**Comment by steveisok** [comment]
@squinn7 We're currently filling in some gaps w/ our GSS api usage.  That is something to try when it becomes available.  I'll know more once we get the fixes in.

**Comment by steveisok** [comment]
@squinn7 Our next preview (preview 3) will contain NTLM fixes that *may* solve your problem.  Once that's out (should be pretty soon), I would suggest giving it a try.

**Comment by steveisok** [comment]
@squinn7 Can you try again w/ our latest mono preview?  I'm wondering if our ntlm fixes solve the problem.

https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg

**Comment by marek-safar** [comment]
@mrward could you help us with the testing?

**Comment by mrward** [comment]
No. Would need somebody to configure TFS the same as the @squinn7 or the @squinn7 to verify the fix ideally.

**Comment by squinn7** [comment]
Sorry for the delay in response. The newest versions of mono did not resolve the issue. However, with some new computers being setup we were able to zero in on the primary cause. Since we have been running and updating Visual Studio for Mac, we had built up many version of the .Net Core SDK.

![image](https://user-images.githubusercontent.com/17345069/72357393-e4e02a80-36b8-11ea-9fd9-ed7071b872f5.png)

You can see in the above screenshot that even now, there are a few versions in there. What I had to do was clean out all the older version and the issue went away. At the time, I had around 30-40 versions going down to 2.0.x 

This is most likely why it flew under your radar as setting up a new mac with a new Visual studio would not present the issue. I think perhaps someone could suggest to the VS Mac team that there be a cleaning routine upon updating or a simple way to remove the older version. As it was, I had to do in the command line and it was 10 minutes of 'rm -rf'.

Thanks for all the effort.

**Comment by mrward** [comment]
.NET Core SDK should not have any affecting on VS Mac connecting to a TFS package source. It is not used by VS Mac when connecting to a package source - mono and Xamarin.Mac would be used.

The only way this could affect it is if `dotnet restore` was being used. That does not use Mono though. `nuget restore` and `msbuild restore` will use Mono.

Are nuget restore, msbuild restore and VS Mac working now?

**Comment by steveisok** [comment]
Is it safe to assume that you're no longer held back by this issue?  I think to dive any deeper we would need to know more info about your setup.

**Comment by squinn7** [comment]
The issue for me is resolved. Why exactly it is I can't say. I did do version downgrading which allowed restore so I can see what you are saying but all I can say is the issue doesn't happen anymore. In fact, I can't replicate the behavior anymore.

**Comment by steveisok** [comment]
Great.  Thanks for reaching out to us and feel free to reopen if you run into it again.
