### ISSUE TITLE
Stream.ReadAsync continues on different thread

### ISSUE THREAD

**Issue by mrward** [mono/mono#16759]
## Steps to Reproduce

1.  Use code: `await stream.ReadAsync (buf, 0, count);`

The above should continue on the same thread that called ReadAsync but seems to continue on a different thread.

awaiting a Task.Run works as expected.

Sample Xamarin.Mac project:

https://github.com/mrward/TestStreamReadAsync

Slightly more complicated console app with a custom synchronisation context.

https://github.com/mrward/TestStreamReadAsyncConsoleApp

Also affects VS Mac.

### Current Behavior

After the await the thread has changed.
awaiting a Task.Run works as expected.

### Expected Behavior

After the await the thread is the same as the one that called ReadAsync.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.4.0.188 (2019-06/2c3aeaf3780 Tue Sep  3 15:10:54 EDT 2019)
Mono JIT compiler version 6.0.0.327 (2019-02/f8ea05bddcb Sat Aug 10 18:47:12 EDT 2019)

**Comment by slluis** [comment]
This is causing https://devdiv.visualstudio.com/DevDiv/_workitems/edit/978857, and who know what else.

**Comment by marek-safar** [comment]
What SynchronizationContext is this with?

**Comment by slluis** [comment]
In the case of VSMac, the sync context is GtkSynchronizationContext (http://source.monodevelop.com/#MonoDevelop.Ide/MonoDevelop.Ide/DispatchService.cs,61154603aec2972a). The context is correctly set before the await, and restored after the call, but the continuation is not dispatched through the context.

**Comment by steveisok** [comment]
I can reproduce it through a console app with a single threaded sync context.  It *seems* like the SyncContext Post is never called during `await stream.ReadAsync(buf, 0, count)`

**Comment by steveisok** [comment]
I think it may have to do w/ our FileStream implementation.  If I use a FileStream with async set to true, then it'll work as expected.

`new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read, 1024, true)`

If you use File.OpenRead, async will be false.

**Comment by steveisok** [comment]
I did some digging and our fix to this issue https://github.com/mono/mono/issues/12421 caused problems.  

In this change, we made the sync context always be a reference:
 https://github.com/mono/mono/blob/1256d6c8cf149306032677fa8e060a8de9e69de2/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs#L1318-L1320

I believe this caused the continuation to be executed on the same thread as the spawned task because of:

https://github.com/mono/corert/blob/ffcd7990d87e560c63413293c8efe1d1fc4e3584/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs#L403-L407

Note the check `m_syncContext == SynchronizationContext.Current)`

If our executioncontext change is reverted, then a new sync context will be created and bound to a new task. This allows the continuation to be posted to the sync context and in this case, will ensure the continuation runs on the UI thread.

PR forthcoming.
