### ISSUE TITLE
LLVM failed for String.GetHashCode

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#16808]
`String.GetHashCode` calls `Marvin.ComputeHash32` which can not be converted to LLVM, a simple repro:

```csharp
using System;
using System.Runtime.CompilerServices;

unsafe class Program
{
    static void Main(string[] args)
    {
        byte[] a = new byte[100];
        ComputeHash32(ref a[0]);
    }
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static unsafe void ComputeHash32(ref byte data)
    {
        for (int i=0; i<1; i++)
            data = ref Unsafe.Add(ref data, 1);
            // or:
            // data = ref Unsafe.AddByteOffset(ref data, (IntPtr)1);
    }
}
```
`--llvm` output contains:

```
LLVM failed for 'Program.ComputeHash32': incoming phi arg type mismatch
```
It explains why `string.GetHashCode` is still slow even if LLVM mode (JIT) is enabled

**Comment by filipnavara** [comment]
This seems to be directly related to https://github.com/mono/mono/issues/16621. The conversion of C# `bool` to LLVM type is treated differently for variables/arguments and return values.

**Comment by filipnavara** [comment]
The mismatched types are `i64*` and `i64`. I am trying to get more details.

**Comment by filipnavara** [comment]
Maybe, just maybe, this conversion:

https://github.com/mono/mono/blob/1d324e617acf855f97c191fb9ae31605e36f68b7/mono/mini/mini-llvm.c#L5448-L5449

needs a counter-part to convert the resulting value back.

**Comment by filipnavara** [comment]
Turns out the mismatched types for `OP_PHI` come from the `data` (`i64 *`) argument and the destination register of the operation (`i64` coming from [here](https://github.com/mono/mono/blob/6908a1941b7278fe6711c75976f2434db55136f0/mono/mini/ssa.c#L440-L442)).

The key to understand why it happens is this:
```
converting llvm method void HelloWorld.Program:ComputeHash32 (byte&)
creating vars
created temp 0 (R16) of type System.IntPtr
    arg [0]:  arg R16 <-
```

Notice that the temporary variable is `IntPtr`/`i64`, as set by `mono_compile_create_var_for_vreg`. The LLVM backend however uses the native expression for the argument directly which has a different type.

I am not sure what is the proper fix. Propagating the types correctly all throughout may have unintended consequences (hack implementation at https://github.com/filipnavara/mono/commit/293c42681341246bdb0538c20a3becca35e7cae3). Adding casts for the temporary variables and properly propagating that throughout the code is more in spirit of the current code but it may impede some optimization opportunities.

**Comment by filipnavara** [comment]
@EgorBo confirmed that the second hack (https://github.com/mono/mono/commit/29ce78ce1551aefcf8eca31a88cf9baeac425df8) fixes the issue for `Marvin.ComputeHash32`. I don't feel like pursuing it as a proper fix because I am not familiar with the code.
