### ISSUE TITLE
Run CoreFX Tests for wasm BCL profile

### ISSUE THREAD

**Issue by steveisok** [mono/mono#16858]
Since Wasm now supports the xunit runner, we need to see how it stands up to the suite of corefx tests and track our findings. In addition, we should take the time to do the same w/ existing nunit tests.  

- [ ] Add all BCL xunit libraries to the makefile to run tests against 
- [ ] Enable skipped nunit tests and see what passes and fails
- [ ] Categorize all failing CoreFX / NUnit tests into the following categories
	- [ ]  File a GH issue for each failing group
	- [ ] Test bug or limitation -> make PR which fixes the test

**Comment by filipnavara** [comment]
Note that the CoreFX tests used for netcore are moving target and they are bound to specific CoreFX version and runtime. In order to use it against classic Mono you'll likely end up with huge exclusion list and it will break any time the CoreFX version dependency is updated (unless you fix it to specific one).

It's ok in combination with #16098 (#16718) but that itself will require cooperation to add back WASM targets to CoreFX and to publish the compiled NuGets.

**Comment by steveisok** [comment]
Where we're at w/ wasm, we just need to pin it on a specific version for now.

**Comment by marek-safar** [comment]
The goal of this task is to Mono BCL corefx tests not the netcore tests

**Comment by steveisok** [comment]
Well... I clearly misunderstood :-).  My bad.

**Comment by akoeplinger** [comment]
I don't think we need this anymore with our work in https://github.com/dotnet/runtime
