### ISSUE TITLE
stackalloc always zeros memory

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#16867]
CoreCLR's stackalloc is up to 10x times faster than Mono's one when it's allowed to allocate data without zeroing (but Mono always zeros it).

```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
static unsafe void Process(byte* data) {}

[MethodImpl(MethodImplOptions.NoInlining)]
static unsafe void DoWork(int size)
{
    byte* data = stackalloc byte[size];
    Process(data);
}
```

The `DoWork` method doesn't have `InitLocals` section in IL (there are no local vars).
Also .NET Core has a [linker-step](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/ILLink.targets#L83) to drop all `InitLocas` in all methods in BCL libs (at least for System.Private.CoreLib.dll)
It allows CoreCLR to stackalloc arrays without zeroing them (if InitLocals is empty).
Mono always zeros such arrays (emits @llvm.memset) and it hurts performance in some cases a bit.
According to the spec, stackalloc is not required to zero data.

So I am not saying we should not zero (memset) stackalloc, but only in cases when InitLocals is not empty just like CoreCLR does. 
BTW, when RuyJIT actually zeros data for stackalloc, our llvm.memset looks a bit more efficient for arrays > 100 items, see https://github.com/dotnet/coreclr/issues/13827#issuecomment-531947296

**Comment by EgorBo** [comment]
asm for DoWork (RuyJIT):
```asm
; Method StackAlloc_VarSize:DoWork(int)

G_M8267_IG01:
       push     rbp
       sub      rsp, 48
       lea      rbp, [rsp+20H]
       mov      rax, 0xD1FFAB1E
       mov      qword ptr [rbp+08H], rax

G_M8267_IG02:
       mov      ecx, ecx
       test     rcx, rcx
       je       SHORT G_M8267_IG04
       mov      rax, rcx
       add      rax, 15
       and      rax, -16
       add      rsp, 32
       neg      rax
       add      rax, rsp
       jb       SHORT G_M8267_IG03
       xor      rax, rax

G_M8267_IG03:
       test     dword ptr [rsp], esp
       mov      rdx, rsp
       sub      rdx, 0x1000
       mov      rsp, rdx
       cmp      rsp, rax
       jae      SHORT G_M8267_IG03
       mov      rsp, rax
       test     dword ptr [rsp], esp
       sub      rsp, 32
       lea      rcx, [rsp+20H]

G_M8267_IG04:
       call     StackAlloc_VarSize:Process(long)
       mov      rcx, 0xD1FFAB1E
       cmp      qword ptr [rbp+08H], rcx
       je       SHORT G_M8267_IG05
       call     CORINFO_HELP_FAIL_FAST

G_M8267_IG05:
       nop      

G_M8267_IG06:
       lea      rsp, [rbp+10H]
       pop      rbp
       ret      
; Total bytes of code: 125
```

**Comment by vargaz** [comment]
The coreclr version doesn't init the array.

**Comment by EgorBo** [comment]
Ah, so InitLocals is actually false for DoWork (but Mono ignores it)

**Comment by marek-safar** [comment]
I don't think the InitLocals linker step is used for the default build

**Comment by jaykrell** [comment]
Ok I have a test, that I will better automate.
C# always? outputs this flag. But C# says the contents are undefined.
I need to check ECMA.
Either do not check this flag, or C# cannot be optimized.

```
using System;

class A
{

static unsafe byte* NoInit(int size, byte value)
{
    byte* data = stackalloc byte[0x10000 + size];
    for (int i = 0; i < size; ++i)
       data [i] += value; // try to keep same form as Init function
    return data;
}

static unsafe byte* Init(int size, byte value)
{
    byte* data = stackalloc byte[0x10000 + size];
    for (int i = 0; i < size; ++i)
       data [i] = value;
    return data;
}

static void assert (int a, int b, int c, bool f)
{
  if (f)
    return;
  Console.WriteLine ("assert failed {0} {1} {2}", a, b, c);
  Environment.Exit (1);
}
  
unsafe public static void Main ()
{
  int count = 123;
  byte value = 31;
  byte * data;

  data = Init (count, value);
  for (int i = 0; i < 100; ++i)
     assert (1, i, data [i], i == 1 || data [i] == value);

  data = NoInit (count, 0);
// This previous works but we want to break it:
  for (int i = 0; i < 100; ++i)
     assert (2, i, data [i], data [i] == 0);

// Want this to work:
  for (int i = 0; i < 100; ++i)
     assert (3, i, data [i], data [i] == value);
}

}
```

**Comment by jaykrell** [comment]
ECMA blesses my fix.
So I think C# cannot be helped here, only IL.
So the bug fix is of marginal utility.
Unless maybe that linker step is done.
I assume, but could be wrong, we should honor ECMA spec here.
Perhaps C# does not always output the flag. I could dig more..

**Comment by jaykrell** [comment]
Hah. One can leverage a compiler bug perhaps.
I'll try that.
https://stackoverflow.com/questions/8679052/initialization-of-memory-allocated-with-stackalloc

**Comment by marek-safar** [comment]
No need for C# equilibristics just write the test in .il

**Comment by jaykrell** [comment]
Ok. C#, ildasm + slight edit.

**Comment by filipnavara** [comment]
@jaykrell I think the loophole is that C# doesn't generate `.initlocals` if the method has no variables. Hence, if you just `stackalloc` and pass the result to another function the C# compiler can generate the intended pattern even without ILLinker tricks. I would not depend on it though :)

**Comment by Therzok** [comment]
Related:
https://github.com/dotnet/corefx/issues/29026
https://github.com/dotnet/roslyn/issues/23951
https://github.com/dotnet/csharplang/issues/1738

**Comment by jaykrell** [comment]
Csc is very finicky what it allows with stackalloc. Seems buggy. Complains of conversions between span and byte* or even byte and byte*, if you stray from very narrow forms. Cannot even stackalloc a second time and assign to same local.

**Comment by jaykrell** [comment]
Tests in IL, based on C#, is like checking in binaries, and not maintainable, until/unless one learns to write IL directly.

**Comment by kg** [comment]
Thinking about this more, how much evidence do we have that this significantly impacts production scenarios like say Kestrel, database manipulation, etc? Even if stackalloc doesn't zero-initialize on other runtimes, I don't think that means we shouldn't do it. Exposing uninitialized stack memory is a common source of exploits, see here for example: https://twitter.com/jfbastien/status/1174456856128847872

I think attempting to skip zero-initialization for performance gains may be a bad choice in the long run unless we can be *very careful* to ensure it isn't skipped in cases where it's actually needed. It's hard to prove whether uses of stackalloc are safe, and always zero-initializing them would give us that guarantee.

If production software really needs it, I think it should be an explicit opt-in somehow. That way the author is intentionally saying "I'm not going to leak sensitive data" instead of just accidentally doing it because they're used to everything else being zero-initialized. Maybe an attribute attached to the method?

I don't personally know whether any of my past uses of stackalloc were safe. I always assumed it was zero-init.

**Comment by jaykrell** [comment]
Stackalloc zeroing does not protect sensitive data.
Stackalloc *sometimes* zeros *some* memory.
It is difficult/impossible to get it to zero data you need to protect.
It is difficult to “aim” it.

There are multiple seeming mistakes in .NET and csc here.

Init locals and “init stackalloc” probably should have been separate bits.
Or “stackalloc0” and “stackallocgarbage” should have been two instructions.

Note that I think, at least, my change matches CoreCLR semantics.

Note that it is difficult to write C# code that can see the difference, because of the csc problem. But people do it, on purpose, and maybe by accident.
