### ISSUE TITLE
File.GetCreationTimeUtc() returns the time last modified, not time created

### ISSUE THREAD

**Issue by ryanching** [mono/mono#16974]
## Steps to Reproduce

1. Create a file that was modified at a time later than it was created. 
2. In a fresh console project, call "File.GetCreationTimeUtc('path/to/file');"
3. Notice that the function returns the time that the file was last modified rather than the time at which it was created. 

### Current Behavior

Function returns time file was last modified. 
### Expected Behavior

Function should return the time the file was created. 
## On which platforms did you notice this

[X ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono 6.4.0.198

**Comment by Aguilex** [comment]
The VSMac Telemetry Monitor app reports the time of events incorrectly as a result of this bug... while this tool is only for internal use, it does impact us significantly, since we use this monitor for a significant number of VSMac issues.

**Comment by marek-safar** [comment]
@steveisok please priority this

**Comment by steveisok** [comment]
So, under the hood we call `lstat` on the file in order to get all the creation/modification details.  If the birth time is not set on the file, then we will fall back to the oldest of the two between the last modification and last status change dates.  

What's strange is that the birth time is reporting 0 in code, but I running `stat -f %SB <file>` shows a creation date.  Once I dig into our interop routine, I'll know a bit more.

**Comment by steveisok** [comment]
It looks like this is our culprit:

https://github.com/mono/corefx/blob/65712075da8062eb2d9304104c110185001f8541/src/Native/Unix/System.Native/pal_io.c#L160-L168

While it seems to be a reasonable assumption for some linux versions, osx does track the birth time. I need to validate a change and then I'll post a PR.

**Comment by akoeplinger** [comment]
@Aguilex this is fixed in Mono 6.6.0.90 from the 2019-08 branch. Do you need the fix in 2019-6 too?

**Comment by Aguilex** [comment]
@akoeplinger yes please... since 2019-06 is used for VSM 8.3, it would be good to be able to use the Telemetry Monitor, and have it report time correctly, for any 8.3 investigations the team may need to do in the coming weeks/months. This assumes that the change is low-risk and will not destabilize the product. VSM 8.3 shipped to stable yesterday, so we'd likely ship this fix in a VSM service release, which typically have much shorter test cycles (and no dogfooding or public previews). 

cc @slluis

**Comment by marek-safar** [comment]
Why the internal Telemetry Monitor app cannot run with 2019-08 Mono?

**Comment by Aguilex** [comment]
>Why the internal Telemetry Monitor app cannot run with 2019-08 Mono?

it probably can... but afaik, it runs by default with system mono used by VSM. So if we're trying to investigate an issue with VSM 8.3, it'll run with Mono 2019-06, and then the timestamps are going to be wrong. 
Again, since this is an internal tool, we can probably give folks instructions for how to run it with a different mono than what VSM is using. Doable, but more complicated for people doing investigations. 

Granted, this "investigate VSM 8.3 issue" is a hypothetical... I'm not aware of any instances where this is blocking. So perhaps it's ok to wait until 8.4/2019-08.

@slluis what's your opinion here?

**Comment by slluis** [comment]
@Aguilex I think it can wait. We should start testing 8.4 anyway.
