### ISSUE TITLE
[wasm] Blazor - Client Side Blazor iOS 13

### ISSUE THREAD

**Issue by kjpou1** [mono/mono#16986]
Well actually iOS 13 Safari version is very buggy with WASM or at least call stack size. I just tested with my iPad and even the samples doesn't work because of **2.** - Unhandled Promise Rejection: RangeError: Maximum call stack size exceeded. . Also **3.** but this is worarounded by the hint you received on another github post with "var Module;".

The only workaround i found at the moment with the current Safari / iOS 13 version is by modifying the blazor.webassembly.js file and add give some time at startup on some delegates. It work on my iPad, but i cannot test on iPhone, i only have an iPhone 6 and of course Apple dropped iPhone 6 support for iOS 13.

[blazor.webassembly.ios13.fix.zip](https://github.com/mono/mono/files/3617854/blazor.webassembly.ios13.fix.zip)

As i have no alternative, i will put it as an "Opt-in" in my plugin (mainly for iOS), but i wish Webkit will work better in the future.

Actually tested my "big" Business app with my patch, and it seem to work.

_Originally posted by @Daddoon in https://github.com/mono/mono/issues/16144#issuecomment-531921626_

**Comment by kjpou1** [comment]
There has been a PR submitted to rectify the `<script>var Module;</script>` on iOS 13 https://github.com/aspnet/AspNetCore/pull/13945

**Comment by kjpou1** [comment]
@Daddoon Hello Daddoon

Can you outline the modifications that were made to your `blazor.webassembly.io13.fix.zip` also which delegates exactly are you adding startup time?

**Comment by Daddoon** [comment]
As i have modified the minified version, it would be hard to say what is the real function name in your source code.

Considering the unminifying of the minified version, here are the two modified zone (left is original unminified, right the 'fixed' one):

![diff1](https://user-images.githubusercontent.com/23449646/65410217-0f486800-ddea-11e9-88cd-16d73aff5c57.jpg)

![diff2](https://user-images.githubusercontent.com/23449646/65410250-25562880-ddea-11e9-97b8-12167d1f800e.jpg)

Of course as you can see all the 'window.Blazor.isStarted' stuff is just an hack of my in order to not use my workaround after Blazor booter properly, preventing to slow it down unecessary.

**Comment by kjpou1** [comment]
Yeah not sure myself where those are in the Blazor source code.  Maybe we can get someone from Blazor to chime in on this as well.

Thanks for the info.

**Comment by kjpou1** [comment]
Oh one other thing.  What exactly did the mod fix?  Was it for the stack exceeded?

**Comment by Daddoon** [comment]
I don't know exactly what the mod fixed.

I assumed that it was maybe too much recursion:

- In parent Promise
- In child delegate execution

And as all theses events was chained at startup, i assumed that because of iOS 13 regression, it was exhausting the Safari call stack size.

By calling the setTimeout, because the "fixed" place does not expect a return value, i assumed it was safe to "break" the call stack chain by calling setTimeout, as i have read on the internet that delaying a Promise through a setTimeout tend to put the code to be executed on a new fresh call stack.

In this case it is not entirely true, as if i don't wait 2 seconds (on iPhone 6s), it will fail at the first or second call, very fast.

So in my opinion, maybe the global call stack of Safari is exceeded at Blazor boot. Maybe a solution would be to chain events differently, with less Promise style, and more with a procedural style. But i'm not a Javascript expert, and also, this is only related to Safari in current release.

So yes, for your second question, the fix was for the stack exceeded error. I had to had the **var Module;** trick you mentionned on another issue/pull request, in order to fix a first error on iOS (yes it's not only OSX Catalina), but the stack exceeded error happen just after this Module declaration fix.

**Comment by GerritBergen** [comment]
@Daddoon I'm in the same situation as you were. Latest iPhone I have is an iPhone 6, so I'm a kinda blind to this error.

I just want to confirm, you're able to completely load a blazor app in iOS 13.1 using your workaround file?

**Comment by Daddoon** [comment]
Hi @GerritBergen 

Yes, i have no problem using my business app on iOS 13.1 (still the beta version to be precise) with my workaround. Just be conscient that this workaround create a total additional delay of 4 seconds.

- As the original blazor.webassembly.js is also injected in your project at compile, maybe you will have to use a different name in your index.html page in order to no be overriden. But honestly i didn't tested what would be the first and/or last to be copied/overwritten.
- Also i didn't have checked since my fix if the blazor.webassembly.js code changed between the previous release and the actual shipped 2/3 days ago. You may have to make a diff between the older original and the actual original file. If something has been updated, i advise you to apply yourself the fix on the new version, as i don't have tested/updated yet to the newest release, and i'm more on a shipping plan at the moment than updating the base code.
- My fix worked on iPhone 6s (oldest/lowest device for iOS 13, even if not tested on iPhone SE)
- My fix worked on iPad (newest one).
- I was able to make my business app completly.

**Comment by Daddoon** [comment]
@GerritBergen just forgot to precise that you must also add a var Module declaration before blazor init, except if the Microsoft PR has been already done. Talking about this subject in my doc:

**Comment by GerritBergen** [comment]
@Daddoon ok thanks! I'll try this out tomorrow

**Comment by chucker** [comment]
>Yeah not sure myself where those are in the Blazor source code.

The exact code looks like an awaiter generated by the TypeScript compiler, but the symbol `shouldAutoStart` [can be found in the original TypeScript](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Web.JS/src/Boot.WebAssembly.ts#L9).

**Comment by Daddoon** [comment]
@chucker Haha, thanks to your search, i'm pretty sure that the weird behavior on IE11 with server implementation not starting automatically is because of the **document.currentScript** property not existing at all on Internet Explorer.

Sorry for the off topic!

**Comment by GerritBergen** [comment]
@Daddoon I borrowed a friends iOS 13 device and like you said, nothing worked. BUT, after applying your suggestions I was able to get up and running again. Thank you!

Just for reference I had to apply both, `<script>var Module;</script>`, as well as your workaround in the latest `blazor.webassembly.js` to get things working. Without both the app wouldn't work.

Thanks again!

**Comment by Daddoon** [comment]
Happy to hear that !

**Comment by kjpou1** [comment]
Hello all there has been a PR submitted to AspNetCore that fixes the Stack Exceeded problem.  https://github.com/aspnet/AspNetCore/pull/14605

**Comment by kjpou1** [comment]
Associated PR here: https://github.com/aspnet/AspNetCore/pull/14576

**Comment by chucker** [comment]
@Daddoon probably as part of [3.1.0-preview1](https://github.com/aspnet/AspNetCore/milestone/66), which should come out any day now.

**Comment by Daddoon** [comment]
@chucker  I'm not totally sure by reading [this issue](https://github.com/aspnet/AspNetCore/pull/14605#issuecomment-540901314), but i'm not sure if it's related or not.

@kjpou1 Sorry to bother you, but do you have any informations about that ?

**Comment by chucker** [comment]
@Daddoon oh, I see. I had assumed these would be fixed/worked around by now, but Steve makes a good point that the underlying issue should be fixed on Apple's part.

**Comment by kjpou1** [comment]
The https://github.com/mono/mono/pull/17264 is looking promising.  I am not sure of the time frame and this may miss the preview schedule that Blazor is on.

**Comment by Daddoon** [comment]
Thanks for the feedback @kjpou1 ! Greatly appreciated!

**Comment by kjpou1** [comment]
Very welcome @Daddoon.  Give a shoutout to @jaykrell who made this happen.  

Please note that we are still testing and thank your all for your patience.

**Comment by lertoo** [comment]
Will the fix be ready for .NET 3.1 release? It is a show stopper. Cannot image that Blazor will be released without iOS 13 support.

**Comment by Daddoon** [comment]
@lertoo If you are using the latest preview, did you make a try to load this blazor.webassembly.js file instead of the regular one: https://github.com/Daddoon/BlazorMobile/blob/b10c906167def8a269ce41d1d2d9b669710dcd67/src/BlazorMobile/Interop/Javascript/blazor.webassembly.js

This is **NOT** the expected fix, but if launching your app on iOS is crucial on your timeline, it can be a solution. This modified version of the script will add an additional 4 second delay at Blazor boot time at some points, but it allow to launch Blazor on iOS on the current Blazor runtime.

Otherwise Microsoft stated that Blazor WASM is considered as "preview". I think thing will be "official" in May 2020 (or something like that i read somewhere).

**Comment by radek7210** [comment]
@daddoon Your fix/workaround works fine with the ASP.NET Core version released yesterday.

**Comment by Daddoon** [comment]
Thanks for your feedback @radek7210 !

Even if it work, i will take a look on the file current released file, seeing if it changed between the previous version.

**Comment by GoranHalvarsson** [comment]
@Daddoon Thank you for the fix 👍👍

**Comment by lertoo** [comment]
Thanks @Daddoon 

Just tried the lastest SDK (VS2019 16.4.0 Preview 5.0 + 3.1 Preview 3), Blazor can be loaded on iOS 13.2 even without your fix. However I got the following error when use HttpClient:

System.IO.FileNotFoundExcpetion: Couldn not load file or assembly 'WebAssembly.Net.Http, Version=0.2.2.0, Cultrue=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.

It might be separate issue with the linking. It is working fine with Chrome on Windows 10.

**Comment by Daddoon** [comment]
@lertoo Good to know ! Thanks !

For your issue with HttpClient, it's weird as it works on another browser for you. Did you try to delete all obj and bin folder before doing your test ? Sometime i had strange issue related to some Visual Studio build cache.

**Comment by lertoo** [comment]
@Daddoon  
Thanks your remind. I did Clean the solution yesterday. I just tried again by clearing all cache (VS - delete bin & obj folders, Safari - clear history and site data, restart IIS site). It is working fine now with your fix - the original blazor.webassembly.js actually is not working. Thank you again.

**Comment by enusbaum** [comment]
I'll add myself to the list as well. Built using 3.1.100-preview3-014645 and my application will not load on iOS 13 Safari using my iPhone. Sincerely hope this gets addressed in future releases once we get closer to a RTM version of Blazor WebAssemblly.

**Comment by ericgrantholland** [comment]
Agreed, still broken for me also. Just to clarify things for my own understanding, is this a shortcoming of IOS/Apple or is this something the Mono/Blazor team needs to address? The reason I'm asking is because my apps work on IOS prior to the 13 update.

**Comment by jaykrell** [comment]
Seems like both. Apple behavior changed, Mono can workaround.

**Comment by Daddoon** [comment]
If my understanding are right, the main problem at the moment is that due to iOS 13 "evolution", the current Safari/Webkit WebAssembly call stack is pretty low now and so it explode as the maximum is rapidly reached.

As a proof, just test for example a Unity3D game with WebGL export on Safari, and launch it: Same bug it will not works because iOS 13 Webkit is totally broken.

But as Apple is very slow like usual to fix anything about their problem, surely, the 3rd party frameworks will have to workaround/fix/optimise instead.

The only good thing is that we may expect a better footprint in the future if some optimisations are taken ?

**Comment by kjpou1** [comment]
There is now a verified fix for this and should be in the next preview of Blazor.  See issue https://github.com/mono/mono/issues/17938

Thank you all for your patience.

**Comment by ericgrantholland** [comment]
Confirmed my Blazor app is working on iOS 13 with the latest update. Nice work Microsoft! 👌

**Comment by BaranOzdemir** [comment]
Hi, 
It is still not working for me.

**Comment by ericgrantholland** [comment]
Still works for me. I’m using IOS 13.3 and able to access my client side website www.csharpacademy.com 

Is my website above working on your device?
(FYI it’s somewhat slow to load first time)
If so, could you elaborate on the error you’re getting with your application?

**Comment by BaranOzdemir** [comment]
Thanks for response. Yes I can access to your client-side website on iPhone. When I create a brand new blazor client app it works OK too. However my existing business app (definitely updated to the latest) does not work. I am trying to understand why.

**Comment by Daddoon** [comment]
@BaranOzdemir For a sanity check, can you try to delete your blazor.webassembly.js file, or re-publish your app ?

Otherwise, what is your output in the browser console logs ?

**Comment by BaranOzdemir** [comment]
@Daddoon I found the issue. I created a new client-side project. I moved the code to new project page by page. It turns out one of the injected services calls another method to instantiate a class and store in the local session. When I removed it everything worked ok. What I don't understand was why it worked on desktop, android, iOS 12 etc but not on iOS13? 

![image](https://user-images.githubusercontent.com/35471414/72671719-7f1de500-3aa2-11ea-9aa7-2061907df4fc.png)

**Comment by Daddoon** [comment]
Happy to hear you find your issue.

Generally, i have seen that some weird behavior may occur if you call some services / instanciation / navigation, directly during the web application loading (so on the first page loaded). Maybe you are in a race condition like this one ?

That's why on my project, i tend to virtually delay any execution or critical logic after the initial Blazor boot, with something like a timer, to then execute the required code needed at startup, even if it's with something like 10ms.

However, as it seem the behavior is not consistent between browsers, as iOS 13 Safari seem to again be the "special snowflake", maybe it would be welcome that you report your faulty scenario as an issue on aspnetcore Github issue page, even if Microsoft team may redirect this issue in mono if required.

**Comment by HX-Javier** [comment]
I´m still having problems. With an Iphone Xs with IOS 13.3 I can not load a brand new blazor client app.  @ericgrantholland Your site www.csharpacademy.com is also not working in my iphone. It freeze showing "Fetching c# academy data"

**Comment by Daddoon** [comment]
I just tested a brand new project with Blazor 3.2.0-preview1 on iOS 13.3.1 (iPad OS) and it doesn't work. Migrating my old delayed patch with the current version seem to workaround the issue.

Am i the only one to have this kind of error ?

**Comment by mattgenious** [comment]
@Daddoon No I am getting the same issue, I thought at first it might be something specific for the app that I built but the default ASP.NET Core hosted Blazor WASM app also does not start correctly.
Side note: it also did not work for chrome(80.0.3987.88) and firefox (22.0 (17157)) on iOS 13.3.1

**Comment by Daddoon** [comment]
> 
> 
> @Daddoon No I am getting the same issue, I thought at first it might be something specific for the app that I built but the default ASP.NET Core hosted Blazor WASM app also does not start correctly.
> Side note: it also did not work for chrome(80.0.3987.88) and firefox (22.0 (17157)) on iOS 13.3.1

This behavior is normal on iOS, as Apple enforce the rule that all browsers use the OS webview engine, this mean that Firefox and Chrome use Safari/Webkit under the hood, so they are all affecteds on iOS

**Comment by mattgenious** [comment]
@Daddoon oh that makes so much sense! thanks for clearing that up for me 👍

**Comment by mobinseven** [comment]
> I just tested a brand new project with Blazor 3.2.0-preview1 on iOS 13.3.1 (iPad OS) and it doesn't work. Migrating my old delayed patch with the current version seem to workaround the issue.
> 
> Am i the only one to have this kind of error ?

Same Here. Why is this issue closed then?

**Comment by BaranOzdemir** [comment]
It worked for me but loading very slow. So I gave up on client app and switched to server app.

**Comment by mattgenious** [comment]
@BaranOzdemir what versions were you running?
Both blazor wasm, visual studio and ios?

**Comment by Daddoon** [comment]
@BaranOzdemir Does it work better if you replace the **blazor.webassembly.js** file with the one attached here ?

[blazor.webassembly.3.2.0-preview1-ios-delay.zip](https://github.com/mono/mono/files/4210385/blazor.webassembly.3.2.0-preview1-ios-delay.zip)

It's actually the same kind of fix i have submitted when this issue has been opened. It add a 4 seconds delay to Blazor to boot at startup. This modified version is base on the current Blazor 3.2.0-preview1 version.

@kjpou1 Is someone concerned about this at Microsoft ?

**Comment by Daddoon** [comment]
> > I just tested a brand new project with Blazor 3.2.0-preview1 on iOS 13.3.1 (iPad OS) and it doesn't work. Migrating my old delayed patch with the current version seem to workaround the issue.
> > Am i the only one to have this kind of error ?
> 
> Same Here. Why is this issue closed then?

Because it was fixed at some points. Don’t know if it’s a new iOS regression.

**Comment by chucker** [comment]
> Same Here. Why is this issue closed then?

Because the original issue is fixed. Please provide more information (iOS version, Blazor/.NET Core version) and ideally a test case.

**Comment by Daddoon** [comment]
> > Same Here. Why is this issue closed then?
> 
> Because the original issue is fixed. Please provide more information (iOS version, Blazor/.NET Core version) and ideally a test case.

Done in this issue here https://github.com/mono/mono/issues/16986#issuecomment-583488072 😁

**Comment by jaykrell** [comment]
This should be fixed by the combination of:
 https://github.com/mono/mono/pull/18697
 https://github.com/mono/mono/pull/18734

as well there are changes on the Apple side that also fix it.

**Comment by Daddoon** [comment]
> This should be fixed by the combination of:
> #18697
> #18734
> 
> as well there are changes on the Apple side that also fix it.

Thanks for all this work !!
Good to hear updates about that, also thanks to you i have seen that there is already an issue opened here : https://github.com/mono/mono/issues/18646

I will subscribe to this issue then.

**Comment by mobinseven** [comment]
> Because the original issue is fixed. Please provide more information (iOS version, Blazor/.NET Core version) and ideally a test case.

- iOS 13.3.1 on iPhone 7+

- Blazor 3.2.0-preview1.20073.1

- The project I'm working on is [BlazorBoilerplate](https://github.com/enkodellc/blazorboilerplate). Yes it is not a minimal app as the problem won't happen on minimal apps (Like FlightFinder sample which works flawlessly on the device mentioned above). The project has no issue on iOS 12.4.

**Comment by mobinseven** [comment]
Experts [say](https://gitter.im/aspnet/Blazor?at=5e4a5d9225f1d250fedf4d33) it is a WebKit problem:

> Status resolved, but reported as still causing issues. It's fixed in a developer preview, so will take time to land.

[WebKit Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=206436)

**Comment by chucker** [comment]
@mobinseven I took a look (tried to run BlazorBoilerplate on iOS 13.4b1 on iPhone 11), and unfortunately, this is another instance of `WASM: RangeError: Maximum call stack size exceeded.`

While #15981 is closed, this is also being visited in #18646 and https://github.com/mono/mono/issues/12357. (Though contrary to that one, BlazorBoilerplate _does_ run on Safari on macOS, which I believe has a higher call stack limit.)

@jeromelaban are you continuing to work on this? Will a future 3.2 preview include mitigations?

**Comment by joshlang** [comment]
Ditto.

`WASM: RangeError: Maximum call stack size exceeded` from `blazor.webassembly.js:1:34699` on iPhone 11 safari, but works fine on desktop Safari.  Using latest preview.

**Comment by arivera12** [comment]
Why this is closed it still doesn't work on ios iphone and ipad I am still receiving the error message WASM: RangeError: Maximum call stack size exceeded.

**Comment by chucker** [comment]
@arivera12 they‘re working on it in other issues. See my comment above.

**Comment by arivera12** [comment]
@chucker I see. Hope this gets fix ASAP. I have an app already running on production and website on iphone is broken...

**Comment by chucker** [comment]
While I understand your frustration, note that Blazor WebAssembly isn’t considered production-ready until the release in May.

But! You can patch a workaround in to make the app slower, but work alright in iOS. Check @Daddoon’s comments for a custom JS file.

**Comment by Daddoon** [comment]
@chucker Note that only the boot is slower. Then it's the regular speed.

**Comment by Daddoon** [comment]
If you take the "patch" route, you may just do some conditionnal check before booting your app.
If you detect that the browser is iOS / Safari, include my patch instead of the original blazor.webassembly.js file.

This way, your regular clients browser will not be affected with this workaround, only iOS.

**Comment by arivera12** [comment]
@Daddoon I have been working since yesterday with your project BlazorMobile seems awesome solution. Its your patch already included there?

**Comment by Daddoon** [comment]
Yes it's already included in BlazorMobile projects and actually, the modified file posted here is the one stored in my assemblies for the iOS support.

I made it more convenient (in my opinion) on BlazorMobile, as you just have to choose to opt-in or not in your project.

By default the regular blazor.webassembly.js file is loaded, but on the iOS project, in **AppDelegate.cs** you will see theses lines:

```csharp
            if (int.TryParse(UIDevice.CurrentDevice.SystemVersion.Split('.')[0], out int majorVersion) && majorVersion >= 13)
            {
                BlazorWebViewService.EnableDelayedStartPatch();
            }
```

So if you keep this line present, when iOS platform will be booted, it will replace the blazor.webassembly.js file shipped in your application by a patched one, so you don't have to modify your Blazor HTML project directly to take advantage of the fix.

If Microsoft release a fix in the future you will just have to remove this line to just continue to your regular blazor.webassembly.js file.

But beware, my patch is so always linked to the current supported Blazor version. This mean that if you update your Blazor project to a new version, but that i didn't updated my codebase for this patch, your app will likely don't work. This is the only downside of having to patch the thing externally.

This just mean that if you intent to use Blazor with BlazorMobile, try to keep the version of Blazor at the same levels as specified in the Nuget dependencies of BlazorMobile (or as stated in the project documentation).

**Comment by Daddoon** [comment]
@arivera12 Side note (but offtopic) : I will release a new version of BlazorMobile tomorrow (or in a very short future) that will add new functionnalities of course, but fix some issue you may occur at build time possibly (like build error and you have to make it build twice).

This will be fixed if it occur.

**Comment by arivera12** [comment]
@Daddoon I try and play with it until you release the new version.
![image](https://user-images.githubusercontent.com/5600102/76014505-1b376a80-5ef0-11ea-9837-02ea2931c3a8.png)

**Comment by Daddoon** [comment]
@arivera12 Update is now available (or if not visible, is on validation on nuget.org) if you want to test.
Sorry for the off-topic,

**Comment by arivera12** [comment]
> @arivera12 Update is now available (or if not visible, is on validation on nuget.org) if you want to test.
> Sorry for the off-topic,
@Daddoon 
I will test on this days.

**Comment by jeromelaban** [comment]
@chucker Apologies I missed your callout. The only workaround I found for this issue in Uno was to delay the initialization of Uno by about 5 seconds (see https://github.com/unoplatform/uno/blob/991eaf1cb29ee20893d07abb26069e6a680b0ed5/src/Uno.UI.Wasm/ts/CoreDispatcher.ts#L58).

Not waiting arbitrarily this long will inevitably fall in some sort of a very *very* short stack, on all safari versions (macOS included). From what I could find out, it _seems_ that Safari is doing some sort of `setTimeout(0)` reentrancy optimization during the first few seconds of a page run, instead of dispatching those (and reset the stack).

**Comment by curia-damiano** [comment]
Hi,
I have a OOTB Blazor-client project and it is not working on iPhone/iPadOS 13.3, using Blazor 3.2.0-preview1.20073.1.
Is there any workaround I can put to make it work?

**Comment by chucker** [comment]
@curia-damiano yes — you can manually replace `blazor.webassembly.js` with the one from @Daddoon.

**Comment by Daddoon** [comment]
> @curia-damiano yes — you can manually replace `blazor.webassembly.js` with the one from @Daddoon.

Haha you just posted before I click on comment myself.

@curia-damiano , @chucker is talking about this comment : https://github.com/mono/mono/issues/16986#issuecomment-586731231 . Also the workaround route taken is similar to the Uno project as I see from @jeromelaban

**Comment by curia-damiano** [comment]
Hi all,
I can confirm the script of @Daddoon works correctly in all environments, including iPhone and iPadOS.
The drawback is that during initialization there is a delay of 4 seconds...
I hope the next version of Blazor will fix it.

**Comment by Daddoon** [comment]
You may rename the specific blazor.webassembly.js file, and switch it only if WebKit is detected ? This way you will only load this patch when Safari / WebKit is detected, therefore other browsers will not be affected.

**Comment by curia-damiano** [comment]
Currently I have post-build (for local debugging) and post-publish scripts that replace the file entirely.
I really hope in a fix by GA time.

**Comment by Daddoon** [comment]
Issue is maybe fixed ! See https://github.com/mono/mono/issues/18646#issuecomment-597772473

For anyone using my patch, please remove it if using the new version !

**Comment by curia-damiano** [comment]
Hi @Daddoon and co., I confirm that Preview 2 works fine now even on iPhone and iPad :-)
