### ISSUE TITLE
I have some amateurish question, may you help me?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17109]
We are embeding mono with UE4 as scripting. So I have to learn more about mono source code.

As I read some mono code, I have some questions, thay are:
1. I found there are many function which are start with **monoeg_g_** (monoeg_set_print_handler, monoeg_set_printerr_handler) defined in <eglib-remap.h>
But I can't found where are they define, and Why we should redefine them?

2. how do you debug mono source code on macos or ios platform? I am always use xcode for debug, but the mono code can't generated xcode project. how or what tools can I use to debug mono?

**Comment by jaykrell** [comment]
It might be easier to answer one at a time. But sure.

1. This is because every non-static function in mono must start with a "fairly unique" prefix, in order to not clash with "user symbols". The acceptable prefixes are `mono` and `ves_icall`. `g_` in particular had historical use within mono, so is `#define`d away. I kind think some `mono_` form should be pushed out into the tree, and the `#define`s removed, but that is just me and it is minor.

The functions in glib.h and eglib-remap.h like you found.

2. lldb or gdb (gdb can be a problem on Mac these days)

**Comment by srxqds** [comment]
Thank you for reply @jaykrell 

I got it
