### ISSUE TITLE
Investigate heavy stack from System_Threading_Interlocked_Exchange_T_REF_T_REF__T_REF

### ISSUE THREAD

**Issue by fanyang-mono** [mono/mono#17335]
## Steps to Reproduce
Follow the instructions on the following page to collect the trace on MacOS
https://paper.dropbox.com/doc/Profile-Mono-with-TechEmpower-benchmarks--AmsEtz3lCaMVH~kMyVQxA1CBAg-ryHeobv8okzUs1Fa9TfBG

### Current Behavior
Heavy stack from System_Threading_Interlocked_Exchange_T_REF_T_REF__T_REF
<img width="1352" alt="Screen Shot 2019-10-15 at 12 28 32 PM" src="https://user-images.githubusercontent.com/52458914/66850961-ccd8fd80-ef47-11e9-94f3-81b38dc0e452.png">

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
mono/master on Oct 7, 2019

**Comment by jaykrell** [comment]
Ought to be inlined, is the thing.

**Comment by jaykrell** [comment]
Or rather, intrinsic, kinda the same thing.

**Comment by lambdageek** [comment]
I don't think `Exchange<T>` is intrinsic - if I'm reading intrinsics.c correctly: https://github.com/mono/mono/blob/3b56247afd8b76bce7e13886a24b4d10536c74b0/mono/mini/intrinsics.c#L1160

One problem.  The first argument is `ref T` and to me it looks like `mini_type_is_reference` will return FALSE here, because `mini_type_get_underlying_type ("ref T")` (where T is not the generic sharing constraint type) will just return `ref T`, and `mono_type_is_reference` will return FALSE.   (if it was just "T", I think `mini_type_get_underlying_type` would return `object`)

**Comment by filipnavara** [comment]
Just guessing ... would `gboolean is_ref = mini_type_is_reference (m_class_get_byval_arg (mono_class_from_mono_type_internal (fsig->params [0])));` work ?

**Comment by vargaz** [comment]
Should be fixed now.

**Comment by lambdageek** [comment]
From https://github.com/mono/mono/pull/17341#issuecomment-543274236:

> From Nathan, with this fix and this one [1] Mono/LLVM/.NET5 configuration stands like this:
> 
> > Mono/LLVM/.NET5 before change (req/sec):  1,478,095.55
> > Mono/LLVM/.NET5 after chang (req/sec) :   5,414,536.91
> > .NET Core 3/RyuJIT (req/sec):             6,626,015.90

Detecting and using the intrinsics was a big win.
