### ISSUE TITLE
What does "Bundled NuGet version has been upgraded" mean exactly?

### ISSUE THREAD

**Issue by dcasota** [mono/mono#17417]
In the Mono releases pages it is often described "Bundled NuGet version has been upgraded to x.y RTM".
As example, see https://www.mono-project.com/docs/about-mono/releases/6.4.0/
"Bundled NuGet version has been upgraded to 5.2 RTM."

What I've learned so far the tool called nuget.exe is Windowsx86-commandline-only. See https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools
"The nuget.exe CLI, nuget.exe, is the command-line utility for Windows that provides all NuGet capabilities; it can also be run on Mac OSX and Linux using Mono with some limitations."

Run ```mono /usr/local/bin/nuget.exe``` implies 1) installed Mono 2) downloaded nuget.exe and 3) version matching of Mono and Nuget.exe

Does "Bundled NuGet version has been upgraded" mean "3)" ?
It does not mean Mono is delivered WITH a mkbundled Nuget.exe right?

It would be nice simply to download a published Linux/MacOSX/.. version of nuget.exe or to use a recipe how to build it.

Thank you for clarifying.

**Comment by directhex** [comment]
Mono for Mac (which is the "main" version since it's part of Visual Studio for Mac) bundles a nuget.exe, as specified in this component of the build system: https://github.com/mono/mono/blob/master/packaging/MacSDK/nuget.py

Mono for Linux doesn't bundle it, but ships it as a separate package, "source" (really binary with packaging metadata) at https://github.com/mono/linux-packaging-nuget. Because it's out of tree it only gets updated when someone reminds me that it's in need of updating.

Mono for Windows, I honestly don't remember! Let me check...

**Comment by directhex** [comment]
![Windows 10 x64-2019-10-18-16-20-02](https://user-images.githubusercontent.com/308992/67125603-344eb180-f1c3-11e9-8eb4-8be0958e1414.png)

Looks like yes for Windows.

**Comment by directhex** [comment]
In all cases, "bundle" means "Mono includes this binary" and has nothing to do with `mkbundle`
