### ISSUE TITLE
Await within method with return type Task<T> makes debugging fail

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#17569]
## Steps to Reproduce

1. Download and open [AsyncBug-v3.zip](https://github.com/xamarin/xamarin-macios/files/3765057/AsyncBug-v3.zip).
2. Put a breakpoint on App.xaml.cs:46 (the `string url = "https://jsonplaceholder.typicode.com/todos/1";` line).
3. Run on an iOS device.
4. When the breakpoint is hit (there might already be a breakpoint on a similar line further up in the line: make sure you're testing the right breakpoint), hit step-over.

### Current Behavior

After the breakpoint is hit (there may already be a breakpoint on a similar line further up the page), and after doing a 'step-into' or 'step-over', nothing else happens.

### Expected Behavior

Being able to step over the line of code where the breakpoint is; the process should stop on the next line.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

https://gist.github.com/rolfbjarne/fdb3f0da83e59be22eed42cf25b9f687

## Stacktrace

N/A

**Comment by lauxjpn** [comment]
Has this fix been shipped yet? I am still getting the following error with VS 16.4.4 when stepping over a line in an Android project with the debugger:

`Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mono/mini/debugger-agent.c:4571, condition ``is_ok (error)' not met, function:set_set_notification_for_wait_completion_flag, Could not execute the method because the containing type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder``1[T_REF]', is not fully instantiated. assembly:<unknown assembly> type:<unknown type> member:(null)`
