### ISSUE TITLE
pedump crashing on .NET 2.0 assemblies

### ISSUE THREAD

**Issue by jbevain** [mono/mono#17916]
This is breaking running the Cecil test suite.

1. Download simplemdb.exe from https://github.com/jbevain/cecil/tree/master/symbols/mdb/Test/Resources/assemblies
2. pedump --verify code,metadata simplemdb.exe 

### Current Behavior

Segfault, that seems related to a recent change (https://github.com/mono/mono/commit/1dc63ced73eefe7c19cbe51efd6b1b85026e8b0a#diff-34ddcfc99bebbe2859c2bafcd20a2ac4 ?) on how runtimes are decided.

In pedump.c:473, doing a `mono_init_version ("pedump", NULL)` instead of passing the image version (which is v2.0.50727) fixes it, but I'm not sure if it's the right fix.

### Expected Behavior

No crash, falling back on .net 4.0 default profile.

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

cd190481bdfae9d241e87f9701eeb821275b5a7c

**Comment by lambdageek** [comment]
Pretty interesting, actually. Looks like there are a couple of differnet things wrong here:
1. In `mono_init_internal` we're iterating over `runtimes` using a `tmp` array, but then we're looking at `runtimes->data` instead of `tmp->data`, so we never get to the fallback.
2. Somehow if the image version is "v2.0.50727" we end up with a runtimes list entry with a NULL data field and then we dereference it without a check and end up segfaulting.
pedump caught some nice runtime bugs.
