### ISSUE TITLE
[llvm][netcore] Invalid output for Debug configuration for a simple shift

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#17928]
```csharp
using System;
using System.Runtime.CompilerServices;

public static class PP
{
    static void Main()
    {
        Console.WriteLine(Convert.ToString(Foo(), 2));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static long Foo()
    {
        int i1 = 0x10;
        return (long)i1 << 27;
    }
}
```
Mono-LLVM-JIT (when app is compiled in Debug mode):
```
1111111111111111111111111111111110000000000000000000000000000000
```
In all other cases (e.g. Mono-LLVM-JIT with `Release` or CoreCLR-debug, Mono-JIT-debug, etc):
```
10000000000000000000000000000000
```

`MONO_VERBOSE_METHOD=Foo` output for Mono-LLVM-JIT-Debug: https://gist.github.com/EgorBo/6510f7304d2037df1953dab3707d95eb
(Unoptimized LLVM IR already contains the invalid value)

**Comment by EgorBo** [comment]
Two observations:
1) We don't run `mono_optimize_branches` for LLVM (it's disabled)
2) analyze_liveness_bb kills some variables for LLVM and doesn't kill anything for regular Mono-JIT-Debug.

**Comment by EgorBo** [comment]
NOTE: doesn't reproduce when MONO_OPT_CONSPROP and MONO_OPT_COPYPROP are disabled.

**Comment by naricc** [comment]
This seems to be an issue in LLVM constant propagation. 

It looks like this sign extend here: https://github.com/mono/mono/blob/5cbb1f4be8a0434ad92c39dfcece15f51f920e5b/mono/mini/cfold.c#L262  should be dest->opcode = OP_I8CONST instead of OP_ICONST, since sign extend has a 64 bit output.  

Making that change fixes the issue, but I am not sure if it is going to also promote things unnecessarily to 64 bit.   I am investigating to see if there is a better way to fix it. 

 @vargaz   Any insight on if that change would result in unneeded 64 bit stuff happening (you seem to have made the changes here)?

**Comment by naricc** [comment]
PR for fix: https://github.com/mono/mono/pull/18222
