### ISSUE TITLE
RFC: remove Sparc port from master after 2019-12 branch

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#17923]
# Proposal 

After we branch for 2019-12 (Mono 6.10) we should remove the Sparc support source code from the repo.

## Rationale

It will simplify maintenance going forward.  We don't have any CI for Sparc, so we don't know whether it builds and runs on a day to day basis.  We're not aware of any Linux distributions that ship Mono on Sparc, or officially support Sparc at all.

**Comment by directhex** [comment]
I'm not aware of a single distribution officially supporting SPARC. Debian removed SPARC from the official arches list in 8.0 (latest stable is 10.0)

**Comment by lewurm** [comment]
Also see https://github.com/mono/mono/issues/9300

I don't think we need to wait for `2019-12`. Just do it 🙂

**Comment by directhex** [comment]
Chatted with @lambdageek offline, and I think there may be some value to keeping MIPS for a while longer, maybe. MIPS matters in China.

SPARC's pretty dead though.

**Comment by jaykrell** [comment]
Gentoo? Solaris?

**Comment by NattyNarwhal** [comment]
I could see if the runtime even still compiles on latest Solaris, but no guarantees :thinking:

**Comment by jaykrell** [comment]
I tried compiling over a year ago on Solaris and it didn't, but it was easy to make progress.

**Comment by directhex** [comment]
I have very little interest in maintaining ports with no community porters, no CI infrastructure, and a death sentence from the silicon vendors.

PPC64 we can maintain because we can actually buy CI hardware, for a (fairly acceptable) 4 figures. What are we meant to do about SPARC? Dumpster diving for 20-year-old Sunfires? What's the business case?

**Comment by NattyNarwhal** [comment]
Fujitsu is still developing new CPUs and Solaris has another decade worth of patches, but you're right that without the community interest, there's little point in buying a new SPARC64 system for $LARGE_FIGURE.

PPC64 is probably more realistic now due to the fact it's in the same open ISA club as RISC-V (for real, unlike MIPS) and IBM is actively developing new systems which helps the community interest; i.e [Talos II](https://www.raptorcs.com/) users seem to ping me about Mono every so often. And as you state - you can get boxes reasonably.

**Comment by jaykrell** [comment]
I used to use the opencsw machines for Solaris work, all four architectures.
I wonder if Mono could.

**Comment by directhex** [comment]
Fujitsu hasn't updated their roadmap since 2017, with a vague promise of a new chip later. Buying a SPARC M12-1 would run us over 15 grand. https://www.cdwg.com/product/oracle-sparc64-m12-1-server-6-core/4758555?pfm=srh

**Comment by migueldeicaza** [comment]
If someone wants to ever do a sparc port, using the existing skeleton in the code would allow them to do so.   Removing it just moves the needle from having to do some local C/ASM work to sort out all the logistics of plumbing it out.

I would keep the code for that reason.

**Comment by lambdageek** [comment]
We ended up keeping the sparc code.

**Comment by jaykrell** [comment]
We should port to Solaris x86 and AMD64, which should be easy, same calling convention, very Posix conformant, and then bring back SPARC.
