### ISSUE TITLE
[WASM] WasmHttpMessageHandler doesn't call diagnostic API like HttpMessageHandler in core 

### ISSUE THREAD

**Issue by RemiBou** [mono/mono#18153]
Hi,

I am trying to implement MiniProfiler for Blazor. 
In netcore we can diagnostic HttpClient via DiagnosticListeners like explained here : https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/HttpDiagnosticsGuide.md

I tried to use this in a Blazor/Wasm project but it doesn't work (https://github.com/aspnet/AspNetCore/issues/17790). The reason seems to be that the implementation of HttpClientHandler doesn't call the Diagnostic API. And I think that's the case for all the mono runtimes (DiagnosticListener isn't used in this repo). DiagnosticListener doesn't use any non managed code (AFAIK), so I think it can be used without worry about platform compatibilities.

Is there any chance we can get the same diagnostic capabilities here ? If it's approved, I can work on the WASM implementation.

Not sure if I understood the problem correctly so I might miss something big here.

**Comment by baulig** [comment]
In all of the BCL, whenever we pulled in more CoreFX code throughout the past two years, we generally did not enable the diagnostics code.  This was mostly due to size concerns on mobile, but also lack of features in Mono; to get diagnostics working in a "higher-level" module, you need to first enable it in all the "lower-level" code.

For HttpClient, there wasn't any real benefit in pulling in the diagnostics code because it's generally better to debug and investigate problems in .NET Core version, upstream those and then cherry-pick into Mono.  While it may not have any native dependencies, there are quite a few managed dependencies that it would pull in (some of which are not fully implemented in Mono AFAIK), and we didn't have any good solution to make that conditional on mobile (ie. have the linker easily remove it).

For Web Assembly in particular, we've been trying very damn hard to reduce it's size over the past couple of months, so adding diagnostics code would be very counter-productive to that effort.

Is there any specific reason why you need the diagnostics listener?  Maybe there's a better way of doing that without paying a huge overhead in assembly sizes.

**Comment by kg** [comment]
Could using off-the-shelf tracing tooling to instrument the relevant types in the .dll solve your problems instead? That would potentially get you into a position where you can troubleshoot this in a span of days instead of needing major changes to the BCL.

**Comment by RemiBou** [comment]
I understand your reason and it makes sense. 

I am trying to implement MiniProfiler for Blazor (this could be executed on monowasm or netcore), so basically I'm trying to implement a tracing tool :). My biggest problem now is that I want to suround every http call with MiniProfiler timer and call serv3r side profiling results when some response headers are present. Currently there is no extension point (on netstandard) on http client that would enable this : there is no non-internal virtual SendAsync method in the callstack. So I found the Diagnostic feature but this will work only for Blazor server side (and http call are much seldom in blazor server side).

So now I'm stuck. The only solution is to wrap fetch calls client side for wasm and use diagnostic for blazor server side. Or provide a wrapping class but that wouldn't be nice for my users.

**Comment by gregkalapos** [comment]
I also ran into this problem. Similarly, I also work [on a tracing tool](https://github.com/elastic/apm-agent-dotnet) and we try to offer as much “auto instrumentation” as possible - meaning capturing things for our users without the need for them to write code.

For a “typical” web application (HTML+JavaScript on the client + let’s say ASP.NET Core on the backend) we have a very good story - with basically almost no code if there is an HTTP call from JavaScript into the backend we can capture it end-to-end and correlate client&server side.

I was prototyping something similar for Blazor WebAssembly, but the missing DiagnosticSource events make this very hard if not impossible.

Observability is getting more popular these days and there are also emerging standards like [W3C Trace Context](https://www.w3.org/TR/trace-context/) or OpenTelemetry. `HttpClient` on other non-mono based implementations works for us (observability/tracing tool devs) very well - on those implementations with `DiagnosticListener.AllListeners` we just subscribe to `HttpHandlerDiagnosticListener` (or the equivalent on Full Framework) and we get notified for every outgoing HTTP request and we also have access to the `HttpRequestMessage` to add necessary  headers  to implement W3C TraceContext and correlate client and server side calls.

Something like that would be awesome here, too. Or is there any alternative way to do this?

Of course, I also totally understand the challenge with optimizing `.dll` sizes for web and mobile - just trying to give more input on why this missing feature makes things for us hard.

**Comment by RemiBou** [comment]
@gregkalapos you can trace at the js level, HttpClient in mono wasm uses fetch api for http calls

**Comment by kjpou1** [comment]
This will be handled in the .net 5 API. 

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L31
