### ISSUE TITLE
Can't see managed stack frames in mono crash dumps

### ISSUE THREAD

**Issue by alex-jay91** [mono/mono#18469]
Hi,

I'm having trouble viewing managed (c#) call stack frames in a mono crash dump using visual studio 2017. All native (c++) call stack frames are visible but managed stack frames just show their addresses. Is it even possible to view both mixed stack frames in mono crash dumps ?. Do I have to build/run my application with some special flags ? 

minidump,
embeded mono,
Windows 10, 
Mono JIT compiler version 5.12.0 (Visual Studio built mono)

Thanks

**Comment by lateralusX** [comment]
This is possible with crash dumps from a Mono process running in full AOT mode since then we will generate matching PDB files for native compiled C# code. When running in that mode you should be able to get mixed callstacks with both managed and native frames when analyzing crash dumps using VS or WinDBG. I assume this is just regular JIT, under regular JIT there is not PDB files generated since all code is generated when running the managed code. The mapping between an address and a managed function exists in internal tables, but when open a crash dump, Visual Studio or WinDBG doesn't know how to map this information. If you however break into a running process, you will be able to either call methods like mono_pmip to translate address -> Managed symbols, there is also a Visual Studio plugin that can be used to automatically translate callstacks when running live debugging (https://github.com/jbevain/PmipMyCallStack), but for post mortem debugging there is currently no way to translate address -> Managed symbol if you run using JIT. If you run full AOT you will get this for free, since we will generate needed PDB files needed by debugger to translate addresses to symbols when analyzing crash dumps.

There migh

**Comment by lateralusX** [comment]
There might be solutions for this, but what we probably should do on Windows is to implement the native crash reporter (currently not ported to Windows) that will dump callstacks of all managed threads into a text file. That way you will be able to have a look into that file to get a better overview around what threads are doing and you could use that information when analyzing the crash dump. There might also be a way to extend our DAC to read out needed information from the crash dump (if you have a dump with heap included the table mapping JIT:ed methods -> addresses is available), but that needs further investigation to discover what capabilities exists in that area.

**Comment by alex-jay91** [comment]
Thanks! @lateralusX . I'm trying to build/run my app in full AOT mode with below code. 

mono.exe --aot=full myApp.exe

```
mono_jit_set_aot_mode(MONO_AOT_MODE_FULL);
domain = mono_jit_init("myApp");
```

This causes an exception in mono "Attempting to allocate from the global code manager while running in aot-only mode". Any idea what I'm doing wrong ?

**Comment by lateralusX** [comment]
You will need to do full AOT of all assemblies before you can run. When you set the runtime to run in full AOT mode, it disable JIT meaning that you can't do codegen.

You can have a look at a couple of test scripts to get the idea:
https://github.com/mono/mono/tree/master/msvc/scripts/tests

But base line is that you will need to full AOT compile all assemblies that will be loaded and executed in the app. NOTE, full AOT on Windows is x64 only and our full AOT compiler depends on VS2017 Clang/C2 being installed an in the path (the scripts above does that as part of setting up the toolchain).

You can have a look at this for overall AOT information:
https://www.mono-project.com/docs/advanced/aot/

There is also the option of mkbundle that supports full AOT compile into a single "ready to run" binary.

If you do have a local repro that you could get to crash in native debugger (not being dependent on analyzing a crash dump), you could get mixed callstacks in native debugger using the above plugin or by manually translate the frame addresses to managed symbols using mono_pmip, for details on how mono_pmip could be used in a live process, have a look here:

https://www.mono-project.com/docs/debug+profile/debug/#debugging-with-visual-studio-on-windows

**Comment by alex-jay91** [comment]
Great, this gives me enough info to go on. Thanks for taking the time to reply.
