### ISSUE TITLE
Unable to construct System.Reflection.AssemblyName from a file path under Linux

### ISSUE THREAD

**Issue by CallumDev** [mono/mono#18508]
## Steps to Reproduce

1. Start the csharp REPL
2. Execute the statement `new System.Reflection.AssemblyName("/usr/lib/mono/gac/System.Runtime.Serialization/4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll");`                                                                                                                                          
3. FileLoadException will be thrown

### Current Behavior
`System.IO.FileLoadException: The assembly name is invalid.` is thrown.

### Expected Behavior
An AssemblyName object should be created, the ToString() method returning `/usr/lib/mono/gac/System.Runtime.Serialization/4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll`.

## On which platforms did you notice this

- Linux (Ubuntu 19.10)

**Version Used**:
Mono JIT compiler version 6.8.0.96 (tarball Wed Jan 15 10:08:18 UTC 2020)

**Comment by CallumDev** [comment]
This seems to be a side-effect of #16446 trying to solve #15021.

**Comment by CoffeeFlux** [comment]
This doesn't seem to have ever been supported in Framework, both looking at the docs and testing manually. I guess it was a Mono-specific extension? I don't see it documented anywhere though...

The problem is that AssemblyName parsing explicitly prohibits using a path separator in the string, and there's even a test for this in CoreFX. If this was intended functionality in Mono we want to continue to support, I guess I can check if the path is valid and otherwise throw, but I'll have to look more into this. If no one other than CodeAnalysis was using this behavior, it might be easier to just change that. (And even if we do want to support this moving forward, it's still probably worth changing on their end.)

**Comment by lambdageek** [comment]
This is a bug in Roslyn.  In fact it is a fixed bug in Roslyn https://github.com/dotnet/roslyn/pull/39369.  The issue with path names is discussed in https://github.com/dotnet/roslyn/pull/39369#issuecomment-545970358

Standalone repro (except that it depends on a Microsoft.CodeAnalysis.CSharp.Scripting nuget): 
[scrumpt.zip](https://github.com/mono/mono/files/4100050/scrumpt.zip)

**Comment by lambdageek** [comment]
My sample doesn't throw an exception if I change it to use the preview release of Roslyn:
```
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="3.5.0-beta1-final" />
```
