### ISSUE TITLE
apt install libapache2-mod-mono fails with unmet dependencies

### ISSUE THREAD

**Issue by kobruleht** [mono/mono#18864]
## Steps to Reproduce

1.  Add mono repositories to Debian 10

add file mono-official-stable-list

with contents

    deb https://download.mono-project.com/repo/debian stable-buster main

to  /etc/apt/sources.list.d  directory.

2. Install latest mono:

apt update
apt install mono-complete mono-dbg
apt upgrade

3.  Try to install mod_mono :

apt install libapache2-mod-mono

### Current Behavior

Error:

    > The following packages have unmet dependencies:  libapache2-mod-mono :
    > Depends: mono-apache-server (< 4.6) but 4.7.1-0xamarin2+debian10b1 is
    > to be installed or
    >  mono-apache-server4 (< 4.6) but 4.7.1-0xamarin2+debian10b1 is to be installed or
    > mono-apache-server2 (< 4.6) but it is not installable
    > E: Unable to correct problems, you have held broken
    > packages.

Expected Behavior:

mod_mono should be installed

On which platforms did you notice this:

Debian 10

**Version Used**:

Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:20:43 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by gustav-heinrich** [comment]
I am facing the same issue when trying to install libapache2-mod-mono on a Debian 10 server we are currently preparing to migrate some of our web applications to. Are you confident that this issue might be fixed sometime in the near future? Or do you recommend installing the proper (older) versions of the packages manually for the moment?

**Comment by ginoskotheon** [comment]
I'm also facing this issue with Ubuntu 18.04.4 LTS.

**Comment by Manjey73** [comment]
All the action from the root

1. download the package — `apt-get download libapache2-mod-mono --download-only`
2. To see what you have there in the name of the package turned out, I have this —` libapache2-mod-mono_3.13-0xamarin5+raspbian9b1_armhf.deb`
`dpkg-deb -x libapache2-mod-mono_3.13-0xamarin5+raspbian9b1_armhf.deb /root/deb` — in /root got the deb folder with the package contents
3. `dpkg-deb --control libapache2-mod-mono_3.13-0xamarin5+raspbian9b1_armhf.deb /root/deb/DEBIAN` 
Got another /DEBIAN folder in the /deb folder
4. edit in the folder /root/deb/DEBIAN file control string
`Depends: debconf (>= 1.2.0), libc6 (>= 2.4), apache2.2-common (>= 2.2) | apache2 (>= 2.4), mono-runtime (>= 2.10), mono-apache-server (>= 4.2) | mono-apache-server4 (>= 4.2) | mono-apache-server2 (>= 4.2), mono-apache-server (<< 4.6) | mono-apache-server4 (<< 4.6) | mono-apache-server2 (<< 4.6)`
At the very end, change all << 4.6 to << 4.8
5. putting it back together `dpkg -b /root/deb libapache2-mod-mono_new.deb`
6. Install as if nothing had happened `dpkg -i libapache2-mod-mono_new.deb`

If you do this from scratch, it should work, but you may need initialization
`a2enmod mod_mono_auto`

`service apache2 restart`

Sorry for my english

**Comment by directhex** [comment]
Urgh, sorry y'all, this fell off my radar. I am currently building a fixed mod-mono

**Comment by directhex** [comment]
Fixed in 3.13-0xamarin6 which is published to preview, and currently publishing to stable.
