### ISSUE TITLE
Change in SslStream.BeginRead/BeginWrite behavior

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#18865]
PR #17393 removed the custom `BeginRead`/`BeginWrite` overloads from `SslStream`. The previous implementation allowed both of them to be called simultaneously just as `NetworkStream` does (and NetFX implementation of `SslStream` does). The default implementation in `Stream`, however, allows only one of them to run simultaneously. This causes deadlock in our application when `BeginRead` is used to wait for server responses while `BeginWrite` is used to send commands to the server at the same time.

/cc @baulig

**Comment by baulig** [comment]
That's actually quite fascinating - and I think I need to give you a little bit of historic background on this topic.  A topic which has been in the center of many heated debates in the past.

Historically, there have been two sets of API Contracts for SslStream.  The first has always applied universally and taken precedent over any other interpretations, ideas or concepts that might have been around.  And it still does today.

The API Contract is **I am a Stream, do with me whichever you would do with a Stream and use me in whichever way you would use a Stream**.

The second API Contract is what various people - me included - have thought how a Stream should or should not behave.  I don't think there has ever been any final agreement on this topic.

And quite interestingly, there have also been disagreements about what the inner stream that's being passed into `SslStream` may or may not do during`Read()` or `Write()`.  At some point, I even made the argument that if somebody wants to implement the `Write()` method in such way that it builds a physical house as output - that that should be a legitimate use case.

The major problem with my interpretations and my ideas is that those stem from a time long before Task-async was nearly as widely used as it is used today and the code that I had written years ago was not very robust against those scenarios because it was not written with performance or massive async threading in mind.  There were a lot of issues that got band-aided over the years and the code became increasingly harder and harder to maintain.

Eventually, we made the decision to give it a general overhaul, to simplify it and reuse as much code from the base class as was possible.  The assumption was that by relying on the base class to do all the work, we could never break the First API Contract - the base class was, after all, a Stream (as the intermediate `AuthenticatedStream` doesn't override any of the I/O related methods)!

**Comment by baulig** [comment]
Now to be honest, I had absolutely no idea that the base implementation in `Stream` would not allow `BeginRead` or `BeginWrite` to be used at the same time.  This probably stems from the fact that for quite a long time now, the `Begin/End` async methods are only consumed via those helper APIs that turn them into Task-async.

I was also not aware of the differences between `Stream` and `NetworkStream` or of any differences between NETFX and .Net Core.  How does the .NET Core version of `Stream` behave?

How big of an issue is this for you?  I am very reluctant to ever tough that code in `SslStream` again - simply because it is so complex and therefore contains a high risk of breaking something else.

Maybe we could somehow find a workaround for you that wouldn't require us to make large structural changes to the `SslStream` class?  And if changes are required, then I strongly believe that we should discuss these with the .NET Core team first, rather than cooking a Mono-only band-aid of some sort.

**Comment by filipnavara** [comment]
> I was also not aware of the differences between Stream and NetworkStream or of any differences between NETFX and .Net Core. How does the .NET Core version of Stream behave?

As far as I am aware `Stream` itself has the same BeginRead/BeginWrite limitation in .NET Core. On the other hand, `SslStream` does not.

> How big of an issue is this for you? I am very reluctant to ever tough that code in SslStream again - simply because it is so complex and therefore contains a high risk of breaking something else.

It is not a huge issue for us, per se, since we have control over the source code and we can use the ReadAsync API directly as workaround. However, it is almost guaranteed to break someone else's code too. The code in question comes from a fork of some Jabber.Net library which was around since the NetFX 2.0 timeframe. Luckily we didn't hit the issue elsewhere in our codebase because it was already converted to the new Async APIs which are not affected.

> Maybe we could somehow find a workaround for you that wouldn't require us to make large structural changes to the SslStream class? And if changes are required, then I strongly believe that we should discuss these with the .NET Core team first, rather than cooking a Mono-only band-aid of some sort.

The same code that failed on Mono was already working fine on .NET Core 3.0 and 3.1. I assume they have explicit implementation of BeginRead/BeginWrite on NetworkStream and SslStream, but it definitely warrants a double check.

**Comment by filipnavara** [comment]
Here's the relevant .NET Core code in `SslStream`:

https://github.com/dotnet/runtime/blob/a0ae6619929e811a7f2440f371b8ed6db85bc6ec/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs#L763-L773

**Comment by baulig** [comment]
We removed these custom overloads because they were broken and causing a lot of trouble with leaking unobserved tasks and the new code is also much cleaner and easier to understand.

It also looks like that .NET Core code that you linked to is also broken in that regard - they need to either remove those overloads in their code or fix them.

As a general rule, throwing any exception prior to calling `TaskToApm.End()` is unacceptable and such throws must be removed.  If you call `TaskToApm.Begin()` you **must always** call `TaskToApm.End()`.

Since you mentioned that there is an easy workaround for you, I am going to close this.

**Comment by filipnavara** [comment]
It's easy workaround for me only because I have control over the whole code base, including the 3rd-party library where it caused deadlock. I don't think the current behavior is acceptable and I still believe this is very much a real issue that is going to be hit in practice.

**Comment by filipnavara** [comment]
Note that the same code pattern as used by the library is actually encouraged in the documentation for `SslStream.BeginRead` (https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.beginread?view=netframework-4.8):

```csharp
static void ReadCallback(IAsyncResult ar)
{
    // Read the  message sent by the server.
    // The end of the message is signaled using the
    // "<EOF>" marker.
    SslStream stream = (SslStream) ar.AsyncState;
    int byteCount = -1;
    try 
    {
        Console.WriteLine("Reading data from the server.");
        byteCount = stream.EndRead(ar);
        // Use Decoder class to convert from bytes to UTF8
        // in case a character spans two buffers.
        Decoder decoder = Encoding.UTF8.GetDecoder();
        char[] chars = new char[decoder.GetCharCount(buffer,0, byteCount)];
        decoder.GetChars(buffer, 0, byteCount, chars,0);
        readData.Append (chars);
        // Check for EOF or an empty message.
        if (readData.ToString().IndexOf("<EOF>") == -1 && byteCount != 0)
        {
            // We are not finished reading.
            // Asynchronously read more message data from  the server.
            stream.BeginRead(buffer, 0, buffer.Length, 
                new AsyncCallback(ReadCallback),
                stream);
        } 
        else
        {
            Console.WriteLine("Message from the server: {0}", readData.ToString());
        }
    }
    catch (Exception readException)
    {
        e = readException;
        complete = true;
        return;
    }
    complete = true;
}
```

**Comment by filipnavara** [comment]
We just hit the same issue again on a different part of the code. Please reopen it and fix it.

**Comment by NexusMobile** [comment]
Hi Guys,

With the latest release of VS 2019 16.5.x, with Mono 16.5.514 using Xamarin SslStream.BeginRead is **now blocking** after an SslStrean.Send is done.
Using VS 2019 with 16.4.5 everything was working fine.

If I run SslStream.BeginRead before using SslStream.Send it works fine but SslStream.Send is now blocking. 
Looks like it is always the 2nd of the two who is blocking.
If we add in the send callback SslStream.ReadAsync, we get the expected data from the back end.

We've loaded the same code in VS 15.9.21 and it works
We've loaded the same code in VS for Mac 8.4.4 using Mono 6.6.0.1555 and it works also

**Comment by steveisok** [comment]
@baulig please give this attention

**Comment by NimbusHex** [comment]
I hate to poke my head in and speak while the adults are talking but is there a concrete "ruling" on this whether it's going to be fixed for backwards compatibility or we just need to change the code?  If it's the latter, does anyone have a good resource they can point me to for changing to the async/wait pattern for SslStream without potentially breaking code that has been stable for 3 years now?  I have an app that's pretty much out of commission when it comes to updates because when I fall back to the versions of VS/Mono where this worked correctly, Xamarin.iOS fails to compile with the dsymutil issue that doesn't seem fixable without completely removing Xcode and reinstalling (I don't run into this issue with latest VS/VS for Mac, but of course, the communication is completely broken).

**Comment by steveisok** [comment]
I would prefer this be fixed for backwards compat, but @baulig needs to determine how that's going to happen.  We were fixing other issues, which unfortunately created this one, so it's also a pill to just roll back.

**Comment by hwd71** [comment]
Us too, would be good to maintain backward compat here, IMO, even if it means the library is not so neat :(

**Comment by akoeplinger** [comment]
We backported the fix to the 2020-02 branch which is what Xamarin.iOS/Android are using so it will show up in some future release.

**Comment by hwd71** [comment]
Hurray, great news I think. Any idea when that makes it into the wild? I'm not sure whether to continue looking into fixing this, as it's not easy, the way that we use things, or whether to recommend we wait for the fix. As long as we don't upgrade the build server, it's just devs affected.. but that puts us at risk in other ways.

**Comment by brendanzagaeski** [comment]
*Release status update*

New preview versions of Xamarin.Android and Xamarin.iOS have now been published that include the fix for this item. The fix is not yet included in Release versions. I will update this again when Release versions are available that include the fix.

Fix included in Xamarin.Android 10.3.99.230.
Fix included in Xamarin.iOS 13.20.0.20.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 1. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
_Release status update for Xamarin SDKs_

New Release versions of the Xamarin.Android and Xamarin.iOS SDKs have now been published that include the fix for this item.

Fix included in Xamarin.Android SDK version 11.0.0.3.
Fix included in Xamarin.iOS SDK version 13.20.2.2.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
