### ISSUE TITLE
Explicit interface property ignored when there is a default implementation

### ISSUE THREAD

**Issue by dan3988** [mono/mono#18917]
## Steps to Reproduce

When running a xamarin app, I was getting a crash with the following message:
```
02-18 18:34:34.760 F/        ( 7136): * Assertion: should not be reached at /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mono/mini/mini-trampolines.c:590
02-18 18:34:34.760 F/libc    ( 7136): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 7136 (rmmodel.android), pid 7136 (rmmodel.android)
```

The crash stopped when I removed a default interface property. When trying to isolate the issue, I found the following, possibly related issue. With the following class structure:

```csharp
public interface IInterface
{
	IConvertible Value { get; }
}

public interface IInterface<T> : IInterface where T : IConvertible
{
	new T Value { get; }

	IConvertible IInterface.Value => 56;
}

public abstract class AbstractClass : IInterface
{
	IConvertible IInterface.Value => GetValueInternal();

	internal abstract IConvertible GetValueInternal();
}

public abstract class AbstractClass<T> : AbstractClass, IInterface<T> where T : IConvertible
{
	T IInterface<T>.Value => GetValue();

	protected abstract T GetValue();

	internal sealed override IConvertible GetValueInternal() => GetValue();
}

public class Class<T> : AbstractClass<T>, IInterface<T> where T : IConvertible
{
	private T _value;

	public T Value
	{
		get => _value;
		set => _value = value;
	}

	protected override T GetValue() => _value;
}
```

Call this code:

```
var var0 = new Class<int> { Value = 55 };
var var1 = var0.Value;
var var2 = (Test.IInterface)var0;
var var3 = var2.Value;
```

### Expected Behavior

when getting var3, the explicit implementation of IInterface on AbstractClass will be called and 55 will be returned. This happens on a .net core console app.

### Current Behavior

The default implementation is called, and 56 is returned

## On which platforms did you notice this

Android

**Version Used**:

v4.0.30319

**Comment by brendanzagaeski** [comment]
*Release status update*

A Preview version of Xamarin.Android has now been published on Windows that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

The fix is not yet available in Xamarin.Android on macOS. I will update this item again when a Preview version of Xamarin.Android with the fix is available on macOS.

Fix included in Xamarin.Android 10.3.0.74.

Fix included in Xamarin.Android on Windows in Visual Studio 2019 version 16.6 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

**Comment by brendanzagaeski** [comment]
*Release status update*

A Preview version of Xamarin.Android has now been published on macOS that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.3.0.74.

Fix included in Xamarin.Android on macOS in Visual Studio 2019 for Mac version 8.6 Preview 2. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.3.1.0.

Fix included on Windows in Visual Studio 2019 version 16.6. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.6. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
