### ISSUE TITLE
tSystem.Runtime.Serialization.SerializationException detected: Error in line 1 position 216. Expecting element 'ExceptionDetail' from namespace 'http://schemas.datacontract.org/2004/07/System.ServiceModel'.. Encountered 'Element'  with name 'ApiFault', namespace 'https://bingads.microsoft.com/Customer/v11'.. Thrown from: ExceptionDispatchInfo.Throw().\t0\t0\t1\tOnRetrying\tRetryPolicy\t

### ISSUE THREAD

**Issue by chamons** [mono/mono#18996]
_From @yingfangdu on Fri, 21 Feb 2020 20:07:10 GMT_

### Steps to Reproduce

When Editor gets some fault exception from [a wcf service ](https://github.com/yingfangdu/TempFolder/blob/master/Reference.cs), It will will throw the errors like [this](https://github.com/yingfangdu/TempFolder/blob/master/exception.txt).
The fault response body is like the below image, while System.ServiceModel cannot de-serialize the fault exception to the proper one on Mac which should be 

`FaultException<Microsoft.AdvertisingDesktop.Sync.BingAds.CustomerManagementServiceV13.ApiFault`

In fact, it looks like trying to convert into 

`FaultException<ExceptionDetail>`

Response body from the service.
![image](https://user-images.githubusercontent.com/9310605/75067007-f16a5680-54a0-11ea-9c14-f6f63613bae1.png)

### Expected Behavior
Should convert to the proper exception.

### Environment
The latest Xamarin.Mac build I can get. Xamarin.Mac 6.18

```
```

### Example Project (If Possible)

_Copied from original issue xamarin/xamarin-macios#7957_

**Comment by chamons** [comment]
_From @yingfangdu on Fri, 21 Feb 2020 20:07:50 GMT_

It is similar issue reported [here](https://forums.xamarin.com/discussion/72425/how-to-handle-fault-in-wcf-service-call).

**Comment by chamons** [comment]
@yingfangdu will be e-mailing @steveisok private steps to reproduce.

**Comment by steveisok** [comment]
When we're doing fault processing, we look for both the `<ApiFault>` node as well as the namespace.  The namespace is gathered from the datacontract attribute over top the ApiFault class -> [here](https://msasg.visualstudio.com/DefaultCollection/Bing_Ads/_git/BAE?path=%2Fsrc%2Fapi%2FSync.BingAds%2FService%20References%2FCustomerManagementServiceV13%2FReference.cs&version=GC763772c18d843dc684a5f0a3d080242e064476fa&line=195&lineEnd=200&lineStartColumn=1&lineEndColumn=1&lineStyle=plain).

After running through this a bunch of times, I noticed the ns on the datacontract is `https://bingads.microsoft.com/Customer/v13/Exception`, but the ns in the soap response is `https://bingads.microsoft.com/Customer/v13`.  I'm speculating, but wcf must use the NS in the service contract here.

If you can adjust the ns in your proxy, then it'll work as it should.  `ExceptionDetail` is the default type in the event we don't have a match with your fault xml.  

Since there's a workable solution, I'm going to close this issue.
