### ISSUE TITLE
Crash by hitting NOT_IMPLEMENTED assert during managed debugging

### ISSUE THREAD

**Issue by UnityAlex** [mono/mono#19146]
Note: I'm using the Unity debugger that's built into Visual Studio to connect here

https://issuetracker.unity3d.com/issues/crash-when-declaring-a-replacement-variable-with-using-that-encompasses-any-kind-of-dictionary

## Steps to Reproduce

1.  mcs -debug Program.cs
2. mono --debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:56900 Program.exe
3. Open Visual Studio -> Debug -> Attach Unity Debugger
4. Click "Input IP"
5. Input 127.0.0.1:56900 and press Ok
6. Put breakpoint on line 11 :: `int anyVariable = 0;`
7. Hit any key in terminal that mono was executed in to trigger breakpoint.
8. Hover on anyVariable. If this doesn't trigger the crash hover Main and then anyVariable again. It should be pretty quick to get the `CMD_ASSEMBLY_GET_TYPE` to trigger

```
using System;
using dictionaryReplacement = System.Collections.Generic.Dictionary<double, float>;

namespace DictionaryCrash
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.ReadLine();
            int anyVariable = 0;
        }
    }
}
```

### Current Behavior

```
>"C:\Program Files\Mono\bin\mono.exe" --debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:56900 Program.exe

* Assertion: should not be reached at ..\mono\mini\debugger-agent.c:7715
```

### Expected Behavior

No crash

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x ] Windows

**Version Used**:
`Mono JIT compiler version 6.8.0 (Visual Studio built mono)`

**Comment by lambdageek** [comment]
Looks like that `NOT_IMPLEMENTED` happens when `CMD_ASSEMBLY_GET_TYPE` is sent with an assembly-qualified type name, instead of a regular full name.  Might be something in debugger-libs or in the VS Unity integration.

(Using VS Mac if I build a console app with Mono 6.8.0, debug it, and hover over the variable or over Main and then the variable, I don't get a crash)

**Comment by jbevain** [comment]
I've had a look at this. There's definitely an issue in our debugger client (Windows and macOS) when the file contains a using with an alias.

So that's going to be fixed on our side. Regardless of that, the debugger server should not (actually almost never) abort and gracefully let the client know of the error. Thanks @thaystg for fixing this!
