### ISSUE TITLE
Consider adding [Obsolete] to ServicePointManager.ServerCertificateValidationCallback

### ISSUE THREAD

**Issue by chamons** [mono/mono#19346]
The iOS and Mac SDK has had a number of customers "hit" by the changes to 

ServicePointManager.ServerCertificateValidationCallback

Example: https://github.com/xamarin/xamarin-macios/issues/8176

If this API is dead, and it [sounds like it is](https://github.com/mono/mono/issues/17125#issuecomment-563449127), can we at least Obsolete it?

**Comment by baulig** [comment]
Let me try to explain and clear up the confusion here.

The `ServicePointManager.ServerCertificateValidationCallback` API itself is perfectly valid and in active use by the `System.Net.HttpWebRequest` based web stack.  In fact, it is the only official way (other than the undocumented `Mono.Security` alternatives) of providing custom validation in that code.

Or in other words, if you use the [HttpWebRequest](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest?view=netframework-4.8) API, then you use `ServicePointManager.ServerCertificateValidationCallback`.

The problem is that the [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.8) API is not using `HttpWebRequest` in the backend anymore.  And therefore, the `ServicePointManager.ServerCertificateValidationCallback` is not used by `HttpClient` anymore.

However, since it is still in active use by the non-obsolete `HttpWebRequest`, we cannot make it obsolete.
