### ISSUE TITLE
[Debugging] Watch window shows evaluation only for local variables and `this`

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#19385]
Everything else shows up as `Unable to evaluate`:

![image](https://user-images.githubusercontent.com/34246760/77983179-25684100-72c3-11ea-8007-7442f14bdd06.png)

**Comment by lewing** [comment]
@thaystg can you triage this and talk to @radical about what you find?

**Comment by thaystg** [comment]
Yes! I will do this today!

**Comment by lewing** [comment]
This is appears to be the result of the VS frontend always using `Debugger.evaluateOnCallFrame` for this case instead of (in addition to?) using the other property inspection methods.  We'll do what we can to handle this but we should also check with them why they are using this pattern.

/cc @digeff

**Comment by lewing** [comment]
this is looks like essentially the same issue as #19384 on the backend

**Comment by thaystg** [comment]
Basic expressions are working now, for example:
-this.property
-local variables
-constants
-arithmetic operation with the values above
Not working:
- assignment
- method calls
- nested property
