### ISSUE TITLE
Memory leak in mini_get_rgctx_entry_slot -> lookup_or_register

### ISSUE THREAD

**Issue by Therzok** [mono/mono#21035]
## Steps to Reproduce

1. https://github.com/mono/mono/blob/bdd772531d379b4e78593587d15113c37edd4a64/mono/mini/mini-generic-sharing.c#L2843
2. if the data is found in the lookup aka it is registered, the does nothing to ensure it frees `data`.
3. `data` is always newly allocated before passed to the method

### Current Behavior

Leak

### Expected Behavior

No leak

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.12.0.125 (2020-02/8c552e98bd6 Mon Mar  8 13:06:52 EST 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

## Stacktrace

```
Please paste the stack trace here if available.
```

![image](https://user-images.githubusercontent.com/109974/116279585-62398c80-a790-11eb-8f14-bf20496583a5.png)

**Comment by marek-safar** [comment]
@vargaz can you please investigate?

**Comment by lambdageek** [comment]
The screenshot is the wrong one (it's from the dllmap leak that Ryan fixed).

But the problem is real.  In `mini_get_rgctx_entry_slot` there are several cases that call `g_malloc0` to allocate `entry_data` which is then passed to `lookup_or_register_info`.  If it ends up registering the data, everything is ok.  if it does a lookup and the info is already registered, it will return the index of the old info, and the new `entry_data` will leak.

`lookup_or_register_info` needs a `did_register` out-param, and if it comes back `FALSE`, we should `g_free (entry_data)` if it was allocated.

**Comment by Therzok** [comment]
<img width="1724" alt="Screenshot 2021-04-27 at 19 55 27" src="https://user-images.githubusercontent.com/109974/117241221-59555480-ae3b-11eb-981a-adc973326b85.png">

That is correct, this is the right screenshot.

**Comment by Therzok** [comment]
@vargaz can this be fixed? It's coming up pretty often in vsmac.

**Comment by SamMonoRT** [comment]
@fanyang-mono to take a look. Please work with @vargaz and @lambdageek
