### ISSUE TITLE
The "nuget restore" command fails

### ISSUE THREAD

**Issue by MaksimZhukov** [mono/mono#21180]
The `nuget restore` command fails with new Mono version `6.12.0.140` and `6.12.0.147` on macOS 10.15 Catalina image with the following error:
```
/Users/runner/work/xamarin-forms-samples/xamarin-forms-samples/Todo/Todo.UWP/Todo.UWP.csproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/qxkilfkb.j5z.nugetrestore.targets(315,5): warning : Skipping restore for project '/Users/runner/work/xamarin-forms-samples/xamarin-forms-samples/Todo/Todo.UWP/Todo.UWP.csproj'. The project file may be invalid or missing targets required for restore. [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/hczm5041.2wn.nugetinputs.targets]
```

## Steps to Reproduce

We forked the [xamarin/xamarin-forms-samples](https://github.com/xamarin/xamarin-forms-samples) repository and created a [workflow file](https://github.com/MaksimZhukov/xamarin-forms-samples/blob/main/.github/workflows/test-todo-app.yml) to test mono with different applications. We specified the following mono versions for each app: `6.12.0.125` (default on hosted images), `6.12.0.140` and `6.12.0.147`. 

All builds with mono 6.12.0.125 are successful. Builds with other mono versions failed with the error that I mentioned above except 1 application. Please find details in the [build logs](https://github.com/MaksimZhukov/xamarin-forms-samples/actions/runs/1097592796).

### Current Behavior

The `nuget restore` command fails

### Expected Behavior

The `nuget restore` command passes successfully

## On which platforms did you notice this

macOS

**Version Used**: `6.12.0.140` and `6.12.0.147`

**Comment by MaximLipnin** [comment]
I asked @MaksimZhukov to check whether NuGet.targets shipped with Mono 6.12.0.147 (`/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/Current/bin/NuGet.targets`) on Github-hosted runner contains the `_IsProjectRestoreSupported` target and according to `Get content of the NuGet.targets` build step it definitely does.
Another interesting observation here is that NuGet fails to restore only for *.UWP-projects.

**Comment by MaximLipnin** [comment]
@rainersigwald sorry for bothering here - could you help identify any recent changes in MSBuild which could lead to such a problem? Perhaps, there is some gap between mono/msbuild and dotnet/msbuild but I wasn't able to track down the difference.
Was it unification of the restore process for any supported types of projects? It's interesting that *.Android or *.iOS projects can restore as usual on Mono `6.12.0.147` and *.UWP-projects are the only failing. On the earlier version of Mono (`6.12.0.125`) UWP-projects seemed to be skipped for restoring on macOS so that they didn't fail the whole build.

**Comment by rainersigwald** [comment]
I don't know of any recent changes that would result in something like this. Was there a `nuget.exe` change in that Mono version range, or only MSBuild?

**Comment by MaximLipnin** [comment]
As far as I can see, there was a version bump for both NuGet and MSBuild - https://github.com/mono/mono/commit/cc8b25a7d865e55bdf8189ca6e73d0c1c4a21272

**Comment by MaximLipnin** [comment]
Maybe @radical, based on his experience, could point us out to the right direction? :)

**Comment by MaximLipnin** [comment]
@mrward @KirillOsenkov in case you guys know anything about such a problem

**Comment by mrward** [comment]
Mono 6.12.0.147 has:

- nuget 5.9.0.7134
- MSBuild 16.10.1 (NuGet 5.9.1.8)

Does `msbuild /t:restore` work instead of using nuget restore?

**Comment by MaximLipnin** [comment]
@MaksimZhukov Does this option work for you?

**Comment by mgierlasinski** [comment]
@MaksimZhukov @MaximLipnin @nikolai-frolov @mrward 

Any updates on this?

**Comment by nikolai-frolov** [comment]
@mgierlasinski I described above that it's not a Mono issue but a difference in how "nuget restore" in different mono versions deals with failure during package restoring. Our failure is related to project where we tried to restore packages.

**Comment by MaximLipnin** [comment]
@nikolai-frolov thanks for diving into this!  I'm just wondering if ignoring UWP-projects during restoring on MacOS works for you?

**Comment by mgierlasinski** [comment]
@nikolai-frolov This change of behaviour seems to have impact on AppCenter builds, suddenly they just started to fail because of Mono 6.12.* update. It seems that they need some scripted workaround.

**Comment by MaximLipnin** [comment]
Removing UWP-projects is definitely a workaround here, e.g. https://github.com/jonathanpeppers/boots/issues/87#issuecomment-961242550

**Comment by nikolai-frolov** [comment]
@MaximLipnin Yes, we temporary disabled UWP subproject until it be fixed. Probably this issue can be resolved in case changing of "nuget restore" behavior is expected.
@mgierlasinski I don't own Mono, I only provided result of our internal investigation. If you have similar issue please make sure that you project restores all subprojects correctly, since for 6.12.0.140+ all ignored issues become a terminating alerts. As a workaround you can use "msbuild /t:restore" which throws warnings instead of errors.

**Comment by MaximLipnin** [comment]
> Probably this issue can be resolved in case changing of "nuget restore" behavior is expected.  

Perhaps. something like 
```
<PropertyGroup>
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB4057</MSBuildWarningsAsMessages>
</PropertyGroup>
```
would help as well. However, there might be a problem as related code base doesn't seems to be in Mono's MSBuild fork but in some NuGet repo we're pulling in.

**Comment by MaksimZhukov** [comment]
@MaximLipnin, do you know if there are plans to change this behavior in future versions of Mono, or will it remain the default?

**Comment by mgierlasinski** [comment]
@nikolai-frolov @MaximLipnin Thanks guys for explanation and help, removing UWP from solution in AppCenter script did the job, as described here:
https://github.com/jonathanpeppers/boots/issues/87#issuecomment-963947168

**Comment by MaximLipnin** [comment]
> @MaximLipnin, do you know if there are plans to change this behavior in future versions of Mono, or will it remain the default?

I wouldn't expect any changes in the behavior. One can remove UWP-projects from the solution and use `msbuild /t:restore`, which practically solves the problem, so we can close this issue.

**Comment by MaximLipnin** [comment]
In total:
- one may want to switch over to the latest official stable Mono `6.12.0.140`
- to avoid Xamarin forms solution restoring failure, remove UWP-project from the solution;
- to make restoring not to fail build due to error, use `msbuild /t:restore` instead of `nuget restore`, it'll treat errors as warnings.

Since the workaround was successfully applied, I'm closing this issue. In case you guys have questions or need clarification on any Mono aspects, feel free to open another issue.

**Comment by skadookkunnan** [comment]
> In total:
> 
> * one may want to switch over to the latest official stable Mono `6.12.0.140`
> * to avoid Xamarin forms solution restoring failure, remove UWP-project from the solution;
> * to make restoring not to fail build due to error, use `msbuild /t:restore` instead of `nuget restore`, it'll treat errors as warnings.
> 
> Since the workaround was successfully applied, I'm closing this issue. In case you guys have questions or need clarification on any Mono aspects, feel free to open another issue.

Yes. It works! Updated the pipeline.
