### ISSUE TITLE
Inlining code size

### ISSUE THREAD

**Issue by Therzok** [mono/mono#6397]
## Current Behavior

https://github.com/mono/mono/blob/7a5df3c524d5eb4cf70744dc69c4803eb70b283b/mono/mini/method-to-ir.c#L81

Currently, methods of IL code size < 20 are probed for inlining.

## Expected Behavior

From this [article](https://blogs.msdn.microsoft.com/davidnotario/2004/11/01/jit-optimizations-inlining-ii/) linked by @alexischr, it seems that .NET on Windows inlines methods < 32, (or 0x20).

CoreCLR has a different algorithm to decide whether inlining is [profitable](https://github.com/dotnet/coreclr/blob/ef74ed68fdb108ed9432c40eb2acae4bf7c35bd3/src/jit/inlinepolicy.cpp#L2014)

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.11.0.26 (pull-request-6203/f74a01add57 Tue Dec 12 18:08:19 EST 2017)

**Questions**:
Should the inlining limit be bumped to 0x20?

Would this impact mobile and AOT in code size?

**Comment by lewurm** [comment]
In my opinion increasing code size isn't that much of an issue on targets where we JIT, so I would be okay with increasing that number for JIT-only scenario. We shouldn't increase it for AOT/FullAOT though, because that would increase the size of binaries that we have to ship (or our customers).

But then again: We shouldn't arbitrarily tweak that number without running proper experiments. CoreCRL, as you said, uses a completely different heuristic to do the inlining decisions. Some implications of changing that number:
- A higher threshold means that we would inline more methods, and done naively, this can lead to trashing of the instruction cache.
- More inlining means more work to do for the compiler, thus it increases the compilation time of that specific method.

**Comment by alexischr** [comment]
I do agree with @lewurm, the original value may have been a typo (or not!) but this is a far-reaching change. 

On the other hand, a very low "max length" value may be severely handicapping inlining, and CoreCLR (in the non-`LEGACY_BACKEND` configuration, which I assume is the current one), set the default max size to 100 (https://github.com/dotnet/coreclr/blob/ef74ed68fdb108ed9432c40eb2acae4bf7c35bd3/src/jit/compiler.h#L9302)

I think opening a PR and profiling performance in XS could be useful and fun (and AOT sizes matter less on desktop), and that can result in the inline length limit becoming a runtime or build option.

**Comment by migueldeicaza** [comment]
PR with the proposed change opened:

https://github.com/mono/mono/pull/6404

**Comment by kumpera** [comment]
There's no need to make a PR or change the code. We have an env var called MONO_INLINELIMIT that controls that limit.

Inlining limits and heuristics are not a simplistic measure of how much extra code bloat we want. 
Inlining, to be a performance win, depends heavily on other parts of the JIT to take advantage of more code. The register allocator, in particular, struggles with the extra variables inlining introduces.

As a quick experiment, I built corlib with the default and with 100. Here are the results:

```
= default:
real	0m7.878s
user	0m28.659s
Max native code in a domain         : 6256971
Total time spent JITting (sec)      : 13.3129

= max size=100:
real	0m8.783s
user	0m29.970s
Max native code in a domain         : 6859678
Total time spent JITting (sec)      : 18.9125

deltas:
real: +11.5%
user: +5%
code size: +9.6%
time jitting: +42%
```

Time JITing should be taken with a gain of salt as it includes time running static ctors and other chores.

But, overall, it was a net loss.

Let's see user time of inlining values in increments of 10
```
0 -> 0m8.494s
10 -> 0m8.450s
20 -> 0m7.878s
30 -> 0m7.881s
40 -> 0m8.185s
50 -> 0m8.145s
60 -> 0m8.321s
70 -> 0m8.470s
80 -> 0m8.445s
90 -> 0m8.632s
100 -> 0m8.783s
```

**Comment by Therzok** [comment]
What is the exact test case you ran? I want to experiment with a few values locally, maybe the env var would benefit us in some cases. (i.e. how did you get total time spent jitting)

**Comment by kumpera** [comment]
I ran compiling corlib with AOT disabled to stress compilation time changes. To do so I ran the build in mcs/class/corlib with `make V=1` to get the full command line.

After that I used the MONO_INLINELIMIT  env var to control inlining limits and `-O=-aot` to ensure AOT was not enabled.

Finally, I ran it with `--stats` to collect internal metrics such as JIT time and generated code size.

Measurement was done by running 5 times and picking the lowest times.

Here are a few useful changes to inlining that would be great to have:

- Make the heuristics smarter, like having execution path aware inlining quotas (IE, inline a lot less on branches ending with an exception and a lot more on loop bodies).

- Improve our register allocator so more variables don't cause a net loss in perf.

- Improve our alias-analysis pass to catch more cases triggered by inlining.

- Improve our long & value type handling so they emit less indirect loads/volatile accesses both which defeats inlining benefits.

- Improve our type propagation pass during method-to-ir so we can devirt more sites and thus have more inlining candidates.

- Move call lowering to a later pass to reduce indirection due to ABI details. This will reduce pressure on our register allocator.

- Experiment with tiered compilation on desktop, this should allow us to use LLVM for hot methods and thus get better perf.

- Experiment with compile-time heuristic tiered-compilation instead of execution-time tiered compilation. IE, decide during compilation whether to use mini's backend or LLVM's instead of waiting for execution feedback.
