### ISSUE TITLE
Generate icall table from the managed linker 

### ISSUE THREAD

**Issue by kumpera** [mono/mono#6809]
Problem:

This is an improvement upon https://github.com/mono/mono/issues/6808. The solution proposed in that issue causes all icalls to stay in the binary regardless of what the managed linker did. This contributes to undesired bloat in the final binary.

Proposed solution:

Add a pass to the managed linker that generates a C file with the icall table, which can be later compiled and included in the final binary. This will allow the native linker to properly remove unused functions.

**Comment by lewurm** [comment]
Some more context: When enabling the interpreter on iOS, we not only add the interpreter to the linking step, but also the full icall table: https://github.com/xamarin/xamarin-macios/blob/729e241e4a05b9ffe0c1e045bdd69b208a09a6f5/tools/mtouch/Target.cs#L1587-L1594

With FullAOT it happens automagically: Since the native linker sees the "whole world" it can remove unused icalls safely from final binary. For the interpreter, we need something that understands what icalls are used by the managed code, that's where the managed linker comes in. So the idea would be that instead of including the complete icall table in `libmono-icall-table.a`, the table content should be driven by the managed linker.

I think it's not worth it because:
1. `libmono-icall-table.a` is 140k for iOS arm64 currently (from `2019-02`) with `-O0 -g` (!).
2. The hard part would be to make the whole pipeline working. It would require changes in the managed linker, in the runtime build, and in `mtouch`.
3. It would only work if no code is generated/loaded dynamically, which is the opposite reason we have introduced the interpreter.
