### ISSUE TITLE
Mono AOT assembly resolver is failing to resolve the proper assembly

### ISSUE THREAD

**Issue by Therzok** [mono/mono#6888]
## Steps to Reproduce

Not sure of a self-contained repro, but from my analysis, I had the following:

```
$root/a/Microsoft.CodeAnalysis.dll (2.0.0.0)
$root/b/Microsoft.CodeAnalysis.dll (2.6.0.0)
$root/b/Microsoft.CodeAnalysis.CSharp.dll (2.6.0.0)
```

`MONO_PATH=$root/a:$root/b mono --aot --debug $root/*/*.dll`

## Current Behavior

Microsoft.CodeAnalysis.CSharp.dll reference to Microsoft.CodeAnalysis resolves to Microsoft.CodeAnalysis.dll (2.0.0.0)

## Expected Behavior

Microsoft.CodeAnalysis.CSharp.dll reference to Microsoft.CodeAnalysis resolves to Microsoft.CodeAnalysis.dll (2.6.0.0)

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.11.0.270 (master/6a04dc64516 Thu Jan 18 09:04:29 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

### Stacktrace

```
Please paste the stacktrace here if available.
```

**Comment by lambdageek** [comment]
could you try with `mono --assembly-loader=strict` and see if you get the right behavior?

Either way, output from `MONO_LOG_LEVEL=info MONO_LOG_MASK=asm mono ...` would be helpful.

**Comment by Therzok** [comment]
Output here:
https://gist.github.com/Therzok/90379415fa10a4dabefcf2c67c78c2f1

**Comment by Therzok** [comment]
For both versions

**Comment by lambdageek** [comment]
@Threzok thanks for the gists - I can't tell from the logs if it's working or not.

It looks like in the `--assembly-loader=strict` version it correctly asked for the `2.7.0.0` version of `Microsoft.CodeAnalysis` and then skipped over the `2.0.0.0` version and then successfully referenced the `2.7.0.0` version.  Is that what you wanted to happen?

**Comment by Therzok** [comment]
Yup, that's what we need. Should we be doing that when probing for AOT assemblies?

**Comment by lambdageek** [comment]
I think you shoudl use `--assembly-loader=strict` when you AOT, yes.

The culprit is `MONO_PATH` which has historically not respected strong names (versions and public key tokens).  So if an assembly is in the `MONO_PATH` multiple times (or if it's both in the `MONO_PATH` and in the GAC or in the application base directory) mono would just pick the first one on the path that had the right filename.  This is clearly not what you want.  `--assembly-loader=strict` enables an additional version check - before we commit to an assembly that has the right filename, we check that it also has the expected strong name.  This lets us skip over older or wrongly signed assemblies earlier in the `MONO_PATH`.

I'm going to close this issue.  If you run into problems with `--assembly-loader=strict`, feel free to reopen.
