### ISSUE TITLE
Implement CLR 2.0 memory model

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7313]
Roslyn and CoreFX libraries are written with the assumption of CLR2.0 memory model (as in http://joeduffyblog.com/2007/11/10/clr-20-memory-model) but Mono has a weaker model matching ECMA. This is causing us random issue when running Roslyn.

CLR model has additional safety rules

1. Objects cannot be seen in the unconstructed state.
1. CLR releases on stores of reference types to the heap as part of GC barriers – to guarantee 1. above.

We need to assess the performance impact of switching to CLR model on ARM before switching.

**Comment by marek-safar** [comment]
The results [MonoMembarStats.xlsx](https://github.com/mono/mono/files/1764193/MonoMembarStats.xlsx) of comparing default Mono against a Mono that uses a store release inside the write barrier (The numbers are relative wall clock time). There are some weird results where Mono with memory barrier was faster than the default (like objinst on arm or Health on arm64) but I haven’t been able to reproduce those cases again.
    
Overall it seems that we can get up to 30-40% slower in worst case scenario, with overall bigger performance penalty on arm (likely due to the fact that we need to do full barrier all the time, since the arch doesn’t provide load acquire / store release instructions like arm64’s ldar / stlr).

**Comment by kumpera** [comment]
Vlad applied this patch to mono that changed the card table store to use a store-release instead of a plain store. That gives us a decent estimate of the cost.

The patch didn't include fences for other ref-type stores like static variables and byrefs. They are infrequent so the additional cost shouldn't be significant.

Besides that, this change would allow us to remove some of the fences we have in the managed allocator as there will always be a store-release on the path of making an object globally visible.

**Comment by kumpera** [comment]
As a side note, we could improve how emit ACQ ops on arm.

On 32bits armv8 we can use ldar/stlr.
Besides that I believe we can use weaker forms of dmb that we currently do.

**Comment by kumpera** [comment]
Even thought this causes big regressions on some benchmarks, I think we should move to it.

The main reason is that making other team adopt our memory model is not practical and we want to widen compatibility with the CLR.

**Comment by vargaz** [comment]
I don't think we should slow down things for every user for the sake of a few users who write lock free code without proper barriers. Also, why is this an arm/arm64 problem ? Can't other cpus also do such reordering ?

http://csharpindepth.com/Articles/General/Singleton.aspx

**Comment by jaykrell** [comment]
It hard to quantity "a few users". It is an arm problem because x86/amd64 have such weak memory models already, and implement it, well, sort of efficiently -- using more power and probably more transistors and probably more dollars. And those 4 processors are the bulk of the market. Not that PowerPC and Alpha and IA64 don't also have weak memory models -- .NET also pessimizes for IA64.

**Comment by kumpera** [comment]
@vargaz x86 and sparc are the only two CPUs that don't suffer from this as they implement Total Store Ordering.

The problem is not as much of a few users but existing teams at MS writing concurrent code. Both CoreFx and Roslyn teams program against the CLR memory model and for us to not follow it means we'd need to carefully review every piece of lock-free code they do. Which is not practical.

The good news is that the arm32 perf hit can be improved upon and basically eliminated on modern hardware.

**Comment by migueldeicaza** [comment]
Before we consider this, I think we need to get on the same page about whether this fixes the issues that were initially identified or not, and whether this is the real fix for all the scenarios that we think this fixes, and perform a proper audit.

One of the topics worth researching is where this happens today, if this is happening in a few key spots, like `Lazy`, then we should look into whether this should be the recommended programming model.

**Comment by jaykrell** [comment]
"Lazy" aka "OnDemand" aka "JustInTime" aka "Once" aka "Singleton" aka "StaticInitializer" aka "Delay" aka "Defer" etc.

**Comment by vargaz** [comment]
For the benchmarks, the write barrier used by the runtime code needs to be changed as well.

**Comment by marek-safar** [comment]
There are no easy spots where this shows up to fix and I think we need to support both models if we cannot make the speed differences negligible.

@kumpera could you asses how doable that is and if not could we have runtime switch (e.g. --memory-model=clr) for this without penalty?

**Comment by jaykrell** [comment]
Does this fix ARM CI or my ARM64 Chromebook?

**Comment by kumpera** [comment]
For further reference, here's a list of task I believe need to be done in order for us to have a full implementation for further performance validation:

- add runtime switch `--memory-model=mono|clr`
- change the write barrier code we emit in the JIT
- AOT compiler/runtime must track MM & refuse mismatched images at runtime
- change object allocators to not fence under `clr`
- change native write barrier to fence under `clr`
- detect & use v8a store-release on arm32
- experiment with replacing outlined write barrier [1]
- experiment with memory model pass to eliminate over-fencing [2]
- experiment with stack-guarded outlined WB [3]

[1] Smaller code and spread of fencing instructions might help with perf
[2] We can omit a fence if there's no publishing in between two stores
[3] This is a variant that checks if the store is against the stack and don't WB/fence in that case. We'd need the JIT to classify locations as possibly-on-stack for this to be useful.

**Comment by akoeplinger** [comment]
Some initial work landed in https://github.com/mono/mono/pull/15019

**Comment by jaykrell** [comment]
The plan of having users specify a memory model on command lines was thankfully ultimately rejected and the CLR 2.0 model is now the only one.

It isn’t just CoreFX but all codebases developed mainly on x86 but also used on ARM.

Close this, as completed?
Any more work lingering?

**Comment by akoeplinger** [comment]
The default was switched with https://github.com/mono/mono/pull/17136, closing this.
