### ISSUE TITLE
I installed mono in windows 2012 server machine but i don't know the exact steps how to configure and integrate with Apache web server to run the apsx page 

### ISSUE THREAD

**Issue by angadalasunilyadav** [mono/mono#7616]
## Steps to Reproduce

1.  After installing the mono what i will need to do in windows machine?
 Windows

**Comment by akoeplinger** [comment]
We have some documentation for the mod_mono Apache module here but it is Linux specific (though you should be able to adapt it if you try): http://www.mono-project.com/docs/web/mod_mono/

In general I wouldn't recommend doing this when you're on a Windows Server machine anyway since you could just use IIS/.NET.
