### ISSUE TITLE
git tags not in sync with download tarballs

### ISSUE THREAD

**Issue by anthraxx** [mono/mono#7660]
There seem to be some git tags missing compared to the tarballs available on the website:

https://download.mono-project.com/sources/mono/

It would be great to have those tarballs in sync with commits in github to be able to know which release exactly matches which commit.

**Comment by akoeplinger** [comment]
We recently started doing regular builds of upcoming release branches and pushing them to the www.mono-project.com Preview release channel, that's why there are a lot of 5.10.x tarballs.

We usually only tag stable releases.

@directhex would it be possible to publish the preview release tarballs into e.g. https://download.mono-project.com/sources/mono/preview so that they aren't mixed with the stable release tarballs?

**Comment by anthraxx** [comment]
I see, but actually the website says:

The latest Stable Mono release is: 5.10.0 Stable (5.10.0.160)

Cheers

**Comment by akoeplinger** [comment]
Ah I see, that's a mistake.

@directhex why did 5.10.0.160 not get tagged when we pushed it to stable?

**Comment by directhex** [comment]
Tagging in the pipeline happens on the tarball build job, not on repo promotion. Not a big job to fix. Can you add the missing tag post-hoc while I get the ARM builders back online?

**Comment by akoeplinger** [comment]
Ok, created the 5.10.0.160 tag.

**Comment by akoeplinger** [comment]
Preview tarballs are now published to https://download.mono-project.com/sources/mono/preview/

The publishing pipeline has been updated to create tags on GitHub when pushing to the stable channel. I think we're done here :)

**Comment by directhex** [comment]
.226 was supposed to be stable. Website rewrite is what got missed

**Comment by directhex** [comment]
Running the website job

**Comment by anthraxx** [comment]
Cool, thx for clarification
