### ISSUE TITLE
VBCS compiler server support on Mac

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7879]
It looks like we are unblocked on this one, the VBCSCompiler starts without error with master Mono but we need to test if it actually works and enable it in x-platform msbuild

**Comment by radical** [comment]
Just adding info: I had tested this two months back and it did work on small projects. But when I tried to build vsmac with this enabled, it took forever with nodes consuming CPU even when the project builds were done and the whole build seemed stuck "somewhere". I didn't investigate more due to other constraints at the time.

**Comment by kg** [comment]
Should we consider this the overall tracking task for all platforms or do we only care about Mac?

**Comment by marek-safar** [comment]
We primary care about Mac but once we get it working there most other platforms should not be hard to get working as well
