### ISSUE TITLE
Assembly.LoadFile and Assembly.LoadFrom have same behavior

### ISSUE THREAD

**Issue by LePtitDev** [mono/mono#8149]
https://github.com/mono/mono/blob/8b5d58285518bf509dcd21fd299114009cb1e908/mcs/class/corlib/System.Reflection/Assembly.cs#L578

I try to load 2 different assemblies but when I call Assembly.LoadFile twice, the second returned assembly is the first (locations are same).

https://blogs.msdn.microsoft.com/suzcook/2003/09/19/loadfile-vs-loadfrom/

"Use the LoadFile method to load and examine assemblies that have the same identity, but are located in different paths.LoadFile does not load files into the load-from context, and does not resolve dependencies using the load path, as the LoadFrom method does. LoadFile is useful in this limited scenario because LoadFrom cannot be used to load assemblies that have the same identities but different paths; it will load only the first such assembly."

**Comment by lambdageek** [comment]
@LePtitDev to clarify: the issue here is that you wish to call `LoadFile` multiple times with the same path.  And in between you update the on-disk assembly?  Something like:

```csharp
   var a = Assembly.LoadFile ("dir1/Lib.dll");
   File.Copy ("dir2/Lib.dll", "dir1/Lib.dll");
   var b = Assembly.LoadFile ("dir1/Lib.dll");
   // error is here - no new library loaded - b is the same as a
```

**Comment by lambdageek** [comment]
This is happening for the same reason as https://bugzilla.xamarin.com/show_bug.cgi?id=11199 and has to do with how Mono caches loaded assemblies.

**Comment by jairbubbles** [comment]
No the issue is more:
```csharp
var a = Assembly.LoadFile ("CompilationCache/Dir1/Lib.dll");
var b = Assembly.LoadFile ("CompilationCache/Dir2/Lib.dll");
// we expect a != b
```
We rely on this CLR implementation which is well documented by Microsoft:
> Use the LoadFile method to load and examine assemblies that **have the same identity, but are located in different paths**

Our scenario is I guess not that commo: we use Roslyn compiler to compile C# code on the fly. We do not want to use app domains so we load new assemblies each time we recompile.

**Comment by LePtitDev** [comment]
The problem is that I use Roslyn to compile assemblies but if I write this code :
```csharp
var content = @"
use System;
class MyProgram
{
    public static void Main(string[] args)
    {
        Console.WriteLine(""test1"");
    }
}";
compiler.CompileAndSave(content, "dir1/assembly.dll");
compiler.CompileAndSave(content.Replace("test1", "test2"), "dir2/assembly.dll");

var assembly1 = Assembly.LoadFile("dir1/assembly.dll");
var assembly2 = Assembly.LoadFile("dir2/assembly.dll");

Assert.AreNotEqual(assembly1.Location, assembly2.Location); // Error : same paths
```

I think it's because assemblies here are similar but in this case I want to load assemblies without `LoadFrom` context.

**Comment by lambdageek** [comment]
@jairbubbles @LePtitDev Okay, thank you for the clarifications. Makes sense.

**Comment by jairbubbles** [comment]
@lambdageek Can you point us the code responsible for caching the assemblies? It would help us find a workaround when running with mono, We tried for instance generating a new identity by updating version number for each new assembly but it had some limitations.

**Comment by lambdageek** [comment]
Not an easy question. There are a couple of layers of caching that are getting in your way.

First thing to know: Mono doesn't really have separate load contexts like .NET Framework documentation describes - there are basically only two - the normal load context and the reflection-only load context.  They are not explicit data structures, they're just

Each AppDomain has a list of assemblies that it loaded and it basically compares by full name (after remapping using policy and bindings, etc) to decide if an assembly has already been loaded.  (There's also a `ref_only` flag on each assembly so in principle you can have two different assemblies loaded - one as reflection only, one not).

Next we need to talk about `MonoAssembly` and `MonoImage`.

A `MonoImage` corresponds approximately to a single loaded .netmodule (or in the case of a single-module assembly - the .dll) - usually somewhere on disk.  A `MonoImage` has a `name` which is the full path of that module on disk.  Until the `MonoImage` `assembly` field is set, it isn't really loaded into any appdomain.

A `MonoAssembly` is a container for one (or more, but usually one) `MonoImage`.  Each `MonoAssembly` has a `MonoAssemblyName` which is the full assembly name  and can belong to one or more AppDomains in which case it is considered loaded.

Mono will load at most one `MonoImage` per absolute path name (and separately at most one for reflection-only).

Each `AppDomain` will load at most one `MonoAssembly` per full assembly name (simple name, 4 element version, and public key token if present).

----

Loading using `LoadFrom` works by calling `mono_assembly_open_predicate` which works roughly like this:

1. Call `mono_image_open_a_lot` on the absolute path name, which will resolve symlinks and then look for a `MonoImage` cached with that absolute path name. If one isn't already loaded, we go ahead and create a new `MonoImage` and associate it with that absolute path name.  [code here](https://github.com/mono/mono/blob/master/mono/metadata/image.c#L1752)
2. Now that we have a `MonoImage`, let's "load" an assembly - `mono_assembly_load_from_predicate` - we read out the full assembly name from the `MonoImage` and invoke the search hook for the appdomain to see if it already opened an assembly with that full name.  If it has, return that.  Otherwise, try to create a new `MonoAssembly` and add it to the appdomain. But we also check if some other thread (whether in the same  [code here](https://github.com/mono/mono/blob/master/mono/metadata/assembly.c#L2287).
3. At this point whatever image and assembly we ended up with is what we return.

Note that there's caching at both steps: if we've seen the same absolute path name before, we assume we already loaded that `MonoImage` and don't bother loading it again, then later if we already loaded that full assembly name into the appdomain, we re-use the loaded `MonoAssembly`.

For completeness, here's `Load(String)` and `Load(byte[])`:

`Load(String)` - calls `ves_icall_System_AppDomain_LoadAssembly`:

1.  Call `mono_assembly_load_full_nosearch` and if it fails, invoke the managed Resolve event on the appdomain. [code here](https://github.com/mono/mono/blob/master/mono/metadata/assembly.c#L3702)
2. `mono_assembly_load_full_nosearch` first checks if the assembly is already loaded in the appdomain (by invoking `mono_domain_assembly_search` through a hook), then calls the appdomain preload hook which looks through the application path (`mono_domain_assembly_preload`).  The preload will put together some filenames from the application path and the wanted assembly name and call `mono_assembly_open_predicate`.
3. If it wasn't already loaded, look in the gac, the appdomain search path and the `MONO_PATH`.  All 3 basically end up calling `mono_assembly_open_predicate` after putting together some path from the provided assembly name components and the relevant search path.
4. In both 2 and 3, `mono_assembly_open_predicate` is what we described for `LoadFrom` above.

`Load(byte[])` - calls `ves_icall_System_AppDomain_LoadAssemblyRaw`

1. Call `mono_image_open_from_data_full` which creates a `MonoImage*` from the raw bytes
2. Call `mono_assembly_load_from_full` which calls `mono_assembly_load_from_predicate`.
3. `mono_assembly_load_from_predicate` is step (2) in `LoadFrom`, above.

----

So to fix this we need finer control of 1. the absolute path name to `MonoImage` cache; and 2. the `MonoAssemblyName` to `MonoAssembly` per-`AppDomain` cache.

Right now the first cache is completely filesystem unaware and has no way to trigger an invalidation if a file changed.  (Actually there are two caches - one for reflection only loads and the other for normal loads, but still - it's global for the entire Mono process).

The second cache only considers two assemblies different if their full names are different or if one is reflection only and the other isn't.  This needs to be changed to be aware of all the different sorts of load contexts: certainly the default and reflection-only contexts, but also `LoadFrom` seems like it needs one load context per dirname of the fullpath that is being loaded, and finally, to support `LoadFile` and `Load(byte[])` properly we need one-off load contexts so that each call gets a new assembly back.

**Comment by lambdageek** [comment]
@jairbubbles probably the easiest hacky workaround is to `Load(byte[])` an assembly with a slightly different full assembly name every time.

**Comment by jairbubbles** [comment]
@lambdageek Thank you for the detailed explanations. We'll let you know if the workaround works.

**Comment by lambdageek** [comment]
@jairbubbles No problem.  If I explain it a few more times maybe I'll finally understand it enough to rewrite it. 😃

**Comment by jairbubbles** [comment]
> Right now the first cache is completely filesystem unaware and has no way to trigger an invalidation if a file changed. 

I don't know with Mono but with CLR if you load an assembly it's locked by the process so you can write to the same path file. That's one of the reason why we alway generate new file at each compilation.

For `Assembly.LoadFile` to work like CLR I feel like only the cache 2 must be bypassed, i.e. always load a new `MonoAssembly` from a given `MonoImage` (if it does not already exist for the given path).

**Comment by jairbubbles** [comment]
See https://github.com/mono/mono/issues/11319
