### ISSUE TITLE
Assembly.LoadFrom behaves differently in Mono as with Microsoft's CLR WRT binding redirect

### ISSUE THREAD

**Issue by louis-z** [mono/mono#8152]
## Steps to Reproduce
[BindingRedirectTest.zip](https://github.com/mono/mono/files/1895031/BindingRedirectTest.zip)

1. Using the attached ZIP file, build the provided solution in Debug with VS2017.
2. Successively run the resulting executable with Microsoft's CLR and with Mono.
3. Notice differences in the console output.

_Note: The executable will explicitly invoke nuget.exe. Make sure it can be found in the PATH._

## Current Behavior

The executable has a .config file that should redirect to version 1.2.2.0 any request for a System.Collections.Immutable version smaller than 1.2.2.0:

```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.2.0" newVersion="1.2.2.0" />
      </dependentAssembly>
    </assemblyBinding>
```

Mono does not seem to take this into account when `Assembly.LoadFrom` is called.

## Expected Behavior

The _right_ behavior should be that of the Microsoft CLR's. In other words, Mono should not load version 1.2.1.0 of the System.Collections.Immutable assembly but simply redirect towards version 1.2.2.0.

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:

Mono JIT compiler version 5.10.0 (Visual Studio built mono)

**Comment by lambdageek** [comment]
Related #8149: Mono's `LoadFrom` really has the semantics of `LoadFile` - just load the assembly from the given path without probing.  we should keep the existing mechanism as `LoadFile` and add a proper `LoadFrom`.

**Comment by jairbubbles** [comment]
@lambdageek Well in #8149 the issue is that `LoadFile` do return an already loaded assembly from a different location while it shouldn't. So I would say neither of them do behave like CLR!

**Comment by lambdageek** [comment]
@jairbubbles You're right. I didn't read the other one closely enough.

Our current `LoadFrom` is closer to what `LoadFile` is supposed to do, but still wrong.

**Comment by lambdageek** [comment]
@jairbubbles @louis-z Mono's `LoadFrom` doesn't know about binding redirects at all.

----

`Load(String)` understands binding redirects.

There's a complication.

Using Mono's default legacy behavior - redirects work best for GAC assemblies that are not otherwise in the application's path or other probing directories.  Otherwise Mono's legacy behavior is to just load the first assembly with the right filename that it finds among the application path and probing paths, even if the version is wrong.   (For example: `app.exe.config` says it wants all versions of `Lib` mapped to version `1.1.0.0`.  On disk, `Lib.dll` version 0.0.1.0 is in the same directory as `app.exe`, and `Lib.dll` version 1.1.0.0 is in some directory that's later in the probing path.  If you say `Load("Lib, Version=0.2.0.0")` mono will apply the bindings and go looking for Lib version 1.1.0.0, but it will still take the 0.0.1.0 DLL even though it knows it has the wrong version just because it happens to be the first `Lib.dll` that it found on disk).

If you use `mono --assembly-loader=strict`, Mono will only load strongly-named assemblies if they have the correct version (after applying binding redirects).  In the above example, it will try to load Lib.dll 0.0.1.0, see that the version is not the wanted (1.1.0.0) one, and keep looking for a different DLL, eventually finding the one with the correct version.


You can get more info from the loader by running Mono with the `MONO_LOG_MASK=asm` and `MONO_LOG_MASK=debug` environment variables set.

**Comment by louis-z** [comment]
I suspect you meant `MONO_LOG_LEVEL=debug` in your last sentence, right?
