### ISSUE TITLE
[wasm] Safari issues

### ISSUE THREAD

**Issue by kumpera** [mono/mono#8374]
This meta-issue is to collect external bug reports to WebKit/Safari WRT our usage of WebAssembly.

Mobile Safari crash: https://bugs.webkit.org/show_bug.cgi?id=184827

**Comment by kumpera** [comment]
Safari Tech Preview crash: https://bugs.webkit.org/show_bug.cgi?id=184829

**Comment by kumpera** [comment]
JSC crash: https://bugs.webkit.org/show_bug.cgi?id=184830

**Comment by kumpera** [comment]
Fixed and shipped on STP 60:
https://bugs.webkit.org/show_bug.cgi?id=184829
https://bugs.webkit.org/show_bug.cgi?id=184830

**Comment by kjpou1** [comment]
Safari is working as of `Mojave`.  @kumpera can this issue be closed?

**Comment by jfizz** [comment]
@kjpou1 I just updated Mojave to the latest version and am getting `Maximum call stack size exceeded` in Safari (works for Chrome/Firefox). Maybe a regression?

I can provide a demo if you are unable to reproduce.

**Comment by kjpou1** [comment]
@jfizz Yes please provide as small a demo as you can.  Can not reproduce it.

**Comment by jfizz** [comment]
Here is a demo https://github.com/jfizz/mono-wasm-safari-issue.
- Download the repo as a zip, unzip, then run `python server.py`
- Go to http://localhost:8000/index.html
- Use the file input to choose `doc.docx` (included in the repo)
- Wait a few seconds for the `Maximum call stack size exceeded`

A few things to note:
- The demo works in Chrome/Firefox/Edge
- The demo worked in Safari when ran outside the worker context (main thread). So maybe the issue is related to Safari Web Workers.
- Oddly, adding a `debugger;` statement in `_mono_wasm_invoke_method` resolved the issue (with the devtools open and breakpoints enabled)

**Comment by kjpou1** [comment]
@jfizz How did you create the worker.js file?

The actual error seems to be coming from `using (WordprocessingDocument wDoc = WordprocessingDocument.Open(memoryStream, true)) {` inside the code from WordprocessingDocument.  Is there any way to actually see what is failing in there?

**Comment by GerritBergen** [comment]
Having some issues using the mono runtime in iOS safari (Blazor Client Side): #15989
