### ISSUE TITLE
Redirecting process output when Console.SetOut set gives strange output

### ISSUE THREAD

**Issue by chamons** [mono/mono#8417]
## Steps to Reproduce

1. Download https://gist.github.com/chamons/8aed519dbc9fb32452c91caa2f2f91e9 as example.cs
2. csc example.cs && mono example.exe
3. Not the differences between the echo command and what you get back

## Current Behavior

        /bin/echo who am i
Captured:桷⁯     浡椠         

## Expected Behavior

The behavior when USE_REDIRECT is commented out up above:

	/bin/echo who am i
Captured:who am i

### On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

 $ mono --version
Mono JIT compiler version 5.10.1.38 (2017-12/b4e428d7c41 Thu Apr  5 19:49:28 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

**Comment by migueldeicaza** [comment]
This bug is caused by the changes here:

https://github.com/mono/mono/pull/3730

What happens is that we allocate a StringBuilder with 4 bytes, which contain garbage, then on the EndRead callback, for Mono, we detect that the stream has been disposed, and do not clear the contents, because the stream has been disposed, so we return this garbage.

It looks like we tried to work around a premature dispose on the stream, but likely the bug is that the consumer of the AsyncStreamReader.cs class is misusing the code in the first place.

I am generally suspicious of the two changes that were done for the sake of hardening, we probably should undo both, and find the root reason for Dispose() on the AsyncStreamReader for being called before the data has finished reading.

cc @kumpera

**Comment by migueldeicaza** [comment]
The source for the disposing of the streams was this patch:

https://github.com/mono/mono/pull/3714

I could not find the associated bug, only this discussion:

https://xamarinhq.slack.com/archives/C03CELHQQ/p1475620056007948

But did not see the original report from @rolfbjarne in the days surrounding that message.

I suspect we should undo both series of changes, and track down the source of the problem.

**Comment by migueldeicaza** [comment]
Comment from Rolf:

> file descriptors weren't freed until the GC ran
> and there was no way for the Process user to free them either

Perhaps what we should explore is waiting for the streams to close on Dispose()?

**Comment by rolfbjarne** [comment]
This is the source: https://bugzilla.xamarin.com/show_bug.cgi?id=43462

Comment 9 contains a test case: https://bugzilla.xamarin.com/show_bug.cgi?id=43462#c9

**Comment by kumpera** [comment]
Here's what I found so far, this is not a race condition or a byproduct of the stream disposal/hardening patches.

This is an encoding problem.  The redirected stream is, for some reason, being read a UTF16 instead of UTF8. If you add this line it works:
```
p.StartInfo.StandardOutputEncoding = System.Text.Encoding.UTF8;
```

Now I have no idea on why the stream encoding is changing due to SetOut. Might be a bug or might the expected behavior.

**Comment by kumpera** [comment]
Fix: https://github.com/mono/mono/pull/8438
