### ISSUE TITLE
Can't dynamically replace method by changing MethodHandles

### ISSUE THREAD

**Issue by lordmampf** [mono/mono#8499]
In .Net you can simply change the content of any method;

long* inj = (long*)methodToInject.MethodHandle.Value.ToPointer()+1;
long* tar = (long*)methodToReplace.MethodHandle.Value.ToPointer()+1;
*tar = *inj;

More information:
https://stackoverflow.com/questions/7299097/dynamically-replace-the-contents-of-a-c-sharp-method

With mono I get an:
* Assertion at metadata.c:1157, condition `idx < t->rows' not met 
error

Has anyone success with getting this working with just replacing the pointers?

I tried it on debian mono 5.12.0.222

**Comment by luhenry** [comment]
Please provide a reproducible test case so that we can more easily reproduce it locally.

**Comment by lordmampf** [comment]
Do you need a sln?
You can get test code from here: https://stackoverflow.com/a/36415711

**Comment by luhenry** [comment]
I tried to reproduce https://stackoverflow.com/a/36415711 with Mono 5.14.0.69 (2018-04/12a21428529) and I didn't get the crash.

The reproduction steps are the following:
1. `wget https://gist.githubusercontent.com/luhenry/8433c0ca60f766e0e57ef9a5286ac159/raw/9380419d7a751821851df80b9f59ae4d723ae1b3/repro.cs`
1. `csc /unsafe repro.cs`
1. `mono repro.exe`

@lordmampf could you please confirm if it works with the [Preview](http://www.mono-project.com/download/preview/) version of Mono? 

Thank you

**Comment by lambdageek** [comment]
In my opinion we don't and should not support this - AFAICT the code attempts to overwrite a word in a MonoMethod in order to affect calls to the given method.

1. Mono does not lay out its internal data structures the same was as .NET
2. Even if we did, our JIT doesn't behave the same way as the .NET Framework (for example we may JIT earlier or later than .NET, we may inline more or fewer methods, etc).

That it happens to work on .NET Framework is an accident. There should be no expectation that it will work in Mono.

Crashing is a perfectly reasonable response to random bytes being written over Mono's internal data structures, IMO.

**Comment by marek-safar** [comment]
I agree that you are poking too deep to expect reliable behaviour. There seem to be better solutions used by other IL weaving tools you could try to explore instead.
