### ISSUE TITLE
AttributeTest.DebuggerTypeProxy_24203 failing under XI/XM with 2018-04

### ISSUE THREAD

**Issue by alexischr** [mono/mono#8625]
Example: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/7083/testReport/(root)/AttributeTest/DebuggerTypeProxy_24203

**Comment by akoeplinger** [comment]
The AttributeTest.DebuggerTypeProxy_24203 are expected because we're now using `Dictionary<T>` from corefx which uses [`IDictionaryDebugView<,>`](https://github.com/mono/corefx/blob/34e0d8b15c78140f71a68c1816e97e62a81d709e/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs#L33) instead of [`Mscorlib_DictionaryDebugView<,>`](https://github.com/mono/mono/blob/1c91423be383634995b2b0a1484ec9b1b951c4f9/mcs/class/referencesource/mscorlib/system/collections/generic/dictionary.cs#L55).

The test needs to be fixed.

**Comment by akoeplinger** [comment]
Just saw that this test lives in the XI repo so you'll need to fix it there.

**Comment by marek-safar** [comment]
@alexischr could you update their test to check for correct value

**Comment by alexischr** [comment]
Fixed by https://github.com/xamarin/xamarin-macios/pull/4070
