### ISSUE TITLE
Debian Package Conflict with csc binary name

### ISSUE THREAD

**Issue by hrittich** [mono/mono#9056]
## Steps to Reproduce

1. Install Debian Stretch and add the repository

        deb https://download.mono-project.com/repo/debian stable-stretch main

2. Install the package `chicken-bin`.
3. Try to install the package `mono-roslyn` (or any package that depends on it).

### Current Behavior

Mono, especially mono-roslyn, cannot be installed along with chicken scheme.

The package wants to override the file

    /usr/bin/csc

which is the chicken scheme compiler.

### Expected Behavior

It should be possible to install chicken scheme and mono at the same time.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version**: 5.12

**Comment by directhex** [comment]
Similar issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=754259

**Comment by kekekeks** [comment]
Debian has a tendency to "reserve" short names for some not widely used software. A good example is the old [node](https://packages.debian.org/wheezy/node) package which conflicted with nodejs. Fortunately, `usr/bin/node` was replaced by the actial node js.

The name `csc` is being used by CSharp compiler since 2001, so its clearly an issue on Debian side.

**Comment by hrittich** [comment]
Well, if your argument for it being an issue on the Debian side is, that the C# compiler is older, that it is 
not an argument. The name `csc` is being used by Chicken since the year 2000. Although, I find a who-came-first-discussion rather pointless.

The problem is, I probably cannot file a bug agains a Debian package, that it has a name clash with a package in an unofficial repository. Which means, that the problem will persist, if the name is not changed in the mono repository for Debian. The official Debian mono packages have renamend csc to mono-csc, which should also be done in the unofficial repositories. IMHO, an unofficial repository should ensure to play nicely with the official ones and not expect the official ones to change.

**Comment by kekekeks** [comment]
`csc` is being widely used by xplat scripts that run on windows/osx/linux and don't care about particular particular linux distro having some conflicting chickens. Changing the name would introduce issues for .NET build ecosystem and cause issues for .NET developers in xplat environments who are the primary users of the compiler.

**Comment by hrittich** [comment]
I can understand that this bug will persist, if it is too hard/too much work to be fixed.

I would be wondering, though, if you could not execute these scripts in a special environment, where `csc` is mapped to the C# compiler and otherwise it is not. A little bit like Python's virtualenv. All you have to do is, to place the `csc` executable somewhere else and then adjust the `PATH` variable when needed. In general, a short executable name, is always in danger to have a name clash with other software. Hence, it might be a good idea to provide a safe environment anyways.

I think there are ways to fix the problem. I cannot, however, estimate the amount of work needed, and I understand if this problem is not your top priority (if any). However, you might have a better idea than virtual environments, which is more easy to implement?

**Comment by directhex** [comment]
Actually, the reason it conflicts in these Xamarin packages but not in official Debian, was a conscious effort to resolve a conflict with Chicken. Specifically, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=509367

The `node` situation was only resolved because the `node` package was removed - Debian has a "I was here first so it's mine" approach to these conflicts, and popularity doesn't factor in (similarly, `epiphany` is a clone of Boulder Dash, not the GNOME Epiphany web browser). In fact, the official ruling of the Debian Technical Committee largely _caused_ the Node mess, by trying to resolve it in a Debian-only way: https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html

There's no _good_ answer, because any answer we take runs the risk of being partially broken when not patched on a per-app basis (the way so many Node apps had to be patched to try both `/usr/bin/node` and `/usr/bin/nodejs` just to accommodate Debian's ham radio app). I would feel extremely uncomfortable with trying to do that (again), given the years of user confusion at the Debian-specific `mono-csc` command.

I could add a `Conflicts: chicken-bin` to `mono-roslyn`. It wouldn't _fix_ anything, but at least would give a graceful error at the apt level, not a messy one at the dpkg level.

**Comment by hrittich** [comment]
In the current situation, I could use [dpkg-divert](https://linux.die.net/man/8/dpkg-divert) to move either chicken or mono to a different location. Adding a conflicts tag would make this process harder, although it would improve the error message.

How about the following idea: Instead of placing `csc` into `/usr/bin` place it in `/usr/lib/mono/bin`. Then, add a file to `/etc/profile.d/` which adds `/usr/lib/mono/bin` to the `PATH` variable. Alternatively, one could place `csc` into `/usr/local/bin`. In both cases the C# compiler would be the default and could be installed along with chicken, and whoever wants his/her chicken can alter the `PATH` variable.

I know, it is kind of an ugly solution, but it might work.

**Comment by FernandoGarcia** [comment]
Hi!
There's any solution for this problem?
I'm facing this problem with Ubuntu 18.04.
Best regards.

**Comment by knocte** [comment]
> I could add a Conflicts: chicken-bin to mono-roslyn. It wouldn't fix anything, but at least would give a graceful error at the apt level, not a messy one at the dpkg level.

That sounds like a massive win to me?

**Comment by directhex** [comment]
Sigh. Stupid workaround added. It'll be part of anything newer than 6.7.0.717-0nightly2 or 6.4.0.198-0xamarin1

**Comment by Xyene** [comment]
Since this issue comes up when you Google for this problem, here's a silly workaround for the next person to run into this for allowing Mono C# and Chicken Scheme to be installed side-by-side:

```
mkdir chicken-csc && cd chicken-csc &&
apt-get download chicken-bin &&
dpkg-deb -R *.deb . && rm *.deb &&
mv usr/bin/csc usr/bin/chicken-csc &&
mv usr/bin/csi usr/bin/chicken-csi &&
dpkg-deb -b . fixed-chicken-bin.deb &&
sudo dpkg -i ./fixed-chicken-bin.deb &> /dev/null || sudo apt -f -y --no-install-recommends install &&
cd ..
```

This makes Chicken's `csc` available at `/usr/bin/chicken-csc`.
