### ISSUE TITLE
Use CoreFX SafePasswordHandle

### ISSUE THREAD

**Issue by baulig** [mono/mono#9416]
For my ongoing work on the `System.Security.Cryptography.X509Certificates` namespace, I need `SafePasswordHandle` from CoreFX to be added for corlib.

There is one version for Unix and one for Windows and this also depends on `SecureStringMarshal` (tiny static helper class) that's currently in `System.dll`.

**Comment by baulig** [comment]
This needs to be added to corlib, not System, to allow it to be used in `X509Certificate`.

**Comment by filipnavara** [comment]
Technically it's not a big issue. The `SecureStringMarshal` methods exist in `Marshal` too and that one is in mscorlib. The Unix and Windows versions differ in Ansi/Unicode calls. I guess it's only matter of how to reference this code cleanly. In my private repository I chose to change CoreFX code with "#if MONO" and use `Marshal` directly instead of `SecureStringMarshal`. May not be the best option, but gets the job done. Alternatively it's possible to use the CoreFX files as-is and add small `SecureStringMarshal` shim into Mono code that will implement the methods by calling `Marshal`. Any thoughts? (@marek-safar)

**Comment by baulig** [comment]
Awesome, thanks a lot for this!

**Comment by marek-safar** [comment]
There should be no issue to have it in mscorlib, we can even have it as internal due to already existing IVT to System

**Comment by filipnavara** [comment]
Should be a non-issue once we cherry pick the CoreFX change linked above. Unless someone beats me to it I will submit a cherry pick PR in a few days with all the upstream System.Security changes. I am waiting for couple of patches to go in.

**Comment by baulig** [comment]
I already have a PR ready for this, just waiting for https://github.com/mono/corefx/pull/94.

**Comment by baulig** [comment]
PR is up: https://github.com/mono/mono/pull/9468.
