### ISSUE TITLE
Proposal: environment variable + configure flag to gate experiments

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#9729]
## Summary ##

Let's add `MONO_EXPERIMENTS=*comma-separated-keywords*` and `./configure --with-experiments=*command-separated-keywords*` which have no stability/backward compatibility or deprecation guarantees.

## Motivation ##

We have a lot of development going on in Mono on features that could use regular testing on CI, or with brave customers, but which are not ready for prime time.

We've occasionally gated these features with one-off environment variables: `MONO_ENABLE_COOP` was one, for example.  What we've done in the past is add the variable and then document it in the man page.  And it's been understood that customers may begin to rely on the environment variable, so retiring the environment variable or changing its semantics requires ample notification and a period of transition.

But we should test earlier - before we're ready to commit to supporting something.

Other features only make sense on some platforms, but ones that are harder for us to test.  For example #9666: we only really need to copy stack data on watchOS and tvOS, but we don't test Mono on those platforms in nightly CI, so it would be useful to periodically run a CI configuration on Linux/amd64 or some other common platform for sanity checking.

## Proposal ##

We add an environment variable and a configure flag that can be used to selectively enable experiments.  The variable and flag will have no stability or deprecation guarantees.

The environment variable and configure flag should use the same keywords and the environment variable should take priority over the configure flags. 

(Optional: maybe every flag also has a "no-flag" in the environment variable to turn _off_ something that the configure flag turned on?)

Each experiment flag should have an open GitHub Issue associated with it.  The issue is closed when the experiment is retired.

**Comment by jaykrell** [comment]
Agreed, except, where affordable, either:
1. Runtime ifs not preprocessor ifs, so we can test one binary with runtime switches.
2. Or maybe a compromise, just one preprocessor if to gate all experimental code, and then runtime switches to enable/disable individual experiments?

I really don't like to configure and build so many times, and imagine a customer is willing to experiment. He shouldn't have to reconfigure/rebuild.

I realize it is messy -- anything here is messy. Either a mess of pound-if or regular-if. Configure does have an advantage of tunnelling through settings most automatically, i.e. if can't place the command line switch in the pipeline. So, lots of options make sense and have advantages and disadvantages.

There is also risk of runtime-if polluting mainline behavior, not just bloat.

Another idea is to make it cheap/easy to duplicate CI for an alternative branch, including all the way to debian packages and monodevelop. Then experiments would go in branches instead of mainline.
There is strong argument for and against this as well. It is kinda what long lived branches are for, but then you do have to take the time to rebase or merge somewhat often. This keeps master pure.
As bad as "polluting mainline" sounds, it really is also common practise.

**Comment by lambdageek** [comment]
We've done this - #10878.

See [mono/utils/mono-experiments.def](https://github.com/mono/mono/blob/master/mono/utils/mono-experiments.def) for instructions on adding a new experiment. ([commit 6161324]( https://github.com/mono/mono/blob/61613246290ab634a02ba56c22b0d809f840fa0a/mono/utils/mono-experiments.def))
