### ISSUE TITLE
MonoAotOffsetsDumper fails because could not find the target build directory

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#9868]
## Steps to Reproduce

1. build XA for 2018-04
2. Full build log at https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3657/consoleText

### Current Behavior

```
 Processing triple: armv5-none-linux-androideabi
  
  Unhandled Exception:
  System.Exception: Could not find the target build directory: /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/external/mono/sdks/builds/android-armeabi-debug
    at CppSharp.MonoAotOffsetsDumper.SetupMono (CppSharp.Driver driver, CppSharp.MonoAotOffsetsDumper+Target target) [0x00128] in <0835e3e645b24ee4aabe6f49aa31fd16>:0 
    at CppSharp.MonoAotOffsetsDumper.Setup (CppSharp.Driver driver, CppSharp.MonoA
```

### Expected Behavior

No build error

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by luhenry** [comment]
This has nothing to do with Mono, and all to do with XA build of Mono /cc @jonpryor 

The problem here is if you specify `/p:AndroidSupportedTargetAotAbis=armeabi` without `/p:AndroidSupportedTargetJitAbis=armeabi`, it will **not** build `armeabi`, but it will build `cross-arm` which _depends_ on `armeabi`.

@jonpryor where should you fix it? Are you going to fix it on `xamarin-androuid:master` which we then merge into `xamarin-android:mono-2018-04` or should you push a fix straight to `xamarin-android:mono-2018-04`?

**Comment by luhenry** [comment]
Fixed in https://github.com/xamarin/xamarin-android/pull/1503
