### ISSUE TITLE
WASM: Use BrowserHttpMessageHandler when available

### ISSUE THREAD

**Issue by SteveSandersonMS** [mono/mono#9941]
As just discussed with @kumpera, @marek-safar, @kjpou1

Rodrigo's proposal is that the Mono WebAssembly BCL can use reflection to check at runtime whether the assembly `Microsoft.AspNetCore.Blazor.Browser` is loadable, and if so, load the type `Microsoft.AspNetCore.Blazor.Browser.Http.BrowserHttpMessageHandler` from it, and use that as the default `System.Net.Http.HttpMessageHandler` subclass for `HttpClient`. It doesn't take any constructor params, so you can just `Activator.CreateInstance(thatType)` it.

For reference, the sources for `BrowserHttpMessageHandler` are at https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor.Browser/Http/BrowserHttpMessageHandler.cs

More difficult alternative: if you want, Mono could take the `BrowserHttpMessageHandler` sources and use them directly in the Mono WebAssembly BCL. However if you follow this approach, it will necessitate having a reference from the BCL to [the `Mono.WebAssembly.Interop` package](https://www.nuget.org/packages/Mono.WebAssembly.Interop/) (or @kjpou1's version of that assembly, if it's now ready to use). This is fine with me, but it's a more involved solution than Rodrigo's proposal above to reference `BrowserHttpMessageHandler` dynamically via reflection. It also still would only work in the context of Blazor, unless you also extract the [corresponding JS-side code](https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor.Browser.JS/src/Services/Http.ts) and merge that into Mono WebAssembly too. Plus you'd want to get all the tests and have a way of running them too. So I think in the short term at least, the simple dynamic-reflection-loading technique may be much better!

cc @danroth @rynowak

**Comment by Suchiman** [comment]
Related to #7933

**Comment by jeromelaban** [comment]
This direction is a bit too tied to a specific framework/library implementation. Could the implementation be based on something like this instead: 

https://github.com/mono/mono/blob/0bcbe39b148bb498742fc68416f8293ccd350fb6/mcs/class/System.Net.Http/System.Net.Http/HttpClient.android.cs#L18

The source of the issue is still that the default `HttpHandler` cannot be changed globally in the .net (or .NET standard) API, and it should be possible to do so (/cc @terrajobst). Many .NET Standard compatible libraries don't provide a way to change the default handler used when making http calls, and this can complicate portability.

Also, Uno implements its own handler this way [WasmHttpHandler.cs](https://github.com/nventive/Uno/blob/master/src/Uno.UI.Wasm/WasmHttpHandler.cs), used [like this in apps](https://github.com/nventive/Uno.Playground/blob/6aa5a222c5ee37f7df7a8ff91cce6d229cc99d93/src/Uno.Playground.Shared/Samples/Playground.xaml.cs#L508).

**Comment by SteveSandersonMS** [comment]
@jeromelaban Yes, we know it's specific to one implementation. It's just a quick and simple tactical fix we already discussed with the Mono team (@kumpera etc.).

**Comment by carldebilly** [comment]
A nicer solution would be to add a "default handler provider" in mono, allowing any wasm framework (blazor, Ooui, Uno, ...) to inject appropriate factory in its bootstrapping.

**Comment by dr1rrb** [comment]
"tactical fix" ... I would'd rather say "big hack so we don't have to provide a real API to other frameworks"

**Comment by kumpera** [comment]
We're working on a solution that would provide a HttpClient that works OOTB.
We can make this change in such a way that it would work for everyone else as well.

**Comment by kumpera** [comment]
cc  @kjpou1

**Comment by kjpou1** [comment]
@SteveSandersonMS and @kumpera can this issue be marked as resolved?

**Comment by SteveSandersonMS** [comment]
Yes, thanks!
