### ISSUE TITLE
Mono application with dark GTK+ themes do not look good and no override available

### ISSUE THREAD

**Issue by BlackDex** [mono/mono#9998]
## Steps to Reproduce

1. Use a Linux OS (Ubuntu 16.04)
2. Use a dark theme (Arc-Dark/Arc-Darker)
3. Start a mono application (Keepass2)
4. Doesn't look well.

Extra steps:
Most (if not all native GTK+) application support the GTK_THEME or GTK2_RC_FILES Environment variables to override the theme to be used for that application.
1. start the application like `GTK_THEME=Arc keepass2` or `GTK_THEME=Adwaita:light keepass2`
This should give you a light variant of the theme, but it doesn't.

### Current Behavior
Keeps most elements as dark theme and no way to override like other GTK+ applications.

### Expected Behavior
Use the correct theme which is selected during start of the application by using GTK_THEME=.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**: 5.14.0.177

**Comment by migueldeicaza** [comment]
I do not think that this issue is related to Mono, that is an issue of your enviroment.

**Comment by Jeansen** [comment]
I agree. And even with the help of lxappearance there was no luck. Mono apps simply look totally broken when using a dark GTK theme.

**Comment by HubKing** [comment]
I am using the latest Ubuntu (18.10), and all I changed was installing the Gnome Tweak tool and changed the theme to the in-built dark theme, "Yaru-dark".  I installed the latest MonoDevelop (7.6.9) and MonoDevelop itself and a dummy default GTK# form application I created looked like Windows 98. If I change the theme to the default bright "Yaru", then it looked all right. Have you found any solution for this?

Yaru-Dark
![dark](https://user-images.githubusercontent.com/10900489/49039251-9ba5f080-f202-11e8-88e7-ff631f5e3cf4.png)

Yaru 
![bright](https://user-images.githubusercontent.com/10900489/49039262-a2ccfe80-f202-11e8-8fe5-16df1fccd90c.png)

**Comment by filipnavara** [comment]
Monodevelop doesn't use System.Windows.Forms, so it's unrelated to this issue.

**Comment by darkgallium** [comment]
I can also reproduce the problem.
I can also confirm that it is not related to the environment because, as it was already said, Mono seems to override the default GTK behaviour that allows people to use per-applications themes by setting environment variables.
Could you please take a closer look at the issue @migueldeicaza ?

**Comment by showthreadx** [comment]
Did you solve this problem? @BlackDex 
I would be very grateful if you can help me.

**Comment by ArniDagur** [comment]
@migueldeicaza Any word on this bug?

**Comment by judemille** [comment]
It's been over three years. Even just an option for Mono to pretend my GTK theme doesn't exist would help.

**Comment by solstice0** [comment]
I found a workaround to force the classic win32 theme, which is good enough for me because in my case the app I need was basically unusable with dark theme.

Just set the `GTK_DATA_PREFIX` env variable to empty before invoking mono from the terminal and the app will start with the win32 theme. 

from the terminal:
```
GTK_DATA_PREFIX= mono <your app>.exe
```

If you want, you can actually set this env var and try to get a theme to work. See here https://askubuntu.com/a/427440/1629631

**Comment by xBZZZZ** [comment]
> ```
> GTK_DATA_PREFIX= mono <your app>.exe
> ```
still broken dark theme current working directory is `/usr`:
```
cd /usr
GTK_DATA_PREFIX= mono <your app>.exe
```
